import type { TerminologyDefinition } from "./schema.ts";
export default [
    {
        aliases: ["07th Expansion"],
        label: "07th Expansion",
        page: "07th Expansion",
        categories: ["07th Expansion遊戲"],
    },
    {
        aliases: ["1-Up Studio"],
        label: "1-Up Studio",
        page: "1-Up Studio",
        categories: ["1-Up Studio遊戲"],
    },
    {
        aliases: ["11 Bit Studios"],
        label: "11 Bit Studios",
        page: "11 Bit Studios",
        categories: ["11 Bit Studios遊戲"],
    },
    {
        aliases: ["17-Bit"],
        label: "17-Bit",
        page: "17-Bit",
        categories: ["17-Bit遊戲"],
    },
    {
        aliases: ["1C Company"],
        label: "1C Company",
        page: "1C Company",
        categories: ["1C Company遊戲"],
    },
    {
        aliases: ["2015 (company)"],
        label: "2015 (company)",
        page: "2015 (company)",
        categories: ["2015 (company)遊戲"],
    },
    {
        aliases: ["21st Street Games"],
        label: "21st Street Games",
        page: "21st Street Games",
        categories: ["21st Street Games遊戲"],
    },
    {
        aliases: ["22cans"],
        label: "22cans",
        page: "22cans",
        categories: ["22cans遊戲"],
    },
    {
        aliases: ["2K Australia"],
        label: "2K Australia",
        page: "2K Australia",
        categories: ["2K Australia遊戲"],
    },
    {
        aliases: ["2K中国", "2k-china", "2K China"],
        label: "2K中国",
        page: "2K中国",
        categories: ["2K中國遊戲"],
    },
    {
        aliases: ["2K Games", "2k-company", "2K (company)"],
        label: "2K Games",
        page: "2K Games",
        categories: ["2K Games遊戲"],
    },
    {
        aliases: ["2K Czech"],
        label: "2K Czech",
        page: "2K Czech",
        categories: ["2K Czech遊戲"],
    },
    {
        aliases: ["2K Los Angeles"],
        label: "2K Los Angeles",
        page: "2K Los Angeles",
        categories: ["2K Los Angeles遊戲"],
    },
    {
        aliases: ["2K Marin"],
        label: "2K Marin",
        page: "2K Marin",
        categories: ["2K Marin遊戲"],
    },
    {
        aliases: ["31st Union"],
        label: "31st Union",
        page: "31st Union",
        categories: ["31st Union遊戲"],
    },
    {
        aliases: ["三七互娱", "37games"],
        label: "三七互娱",
        page: "三七互娱",
        categories: ["三七互娛遊戲"],
    },
    {
        aliases: ["38 Studios"],
        label: "38 Studios",
        page: "38 Studios",
        categories: ["38 Studios遊戲"],
    },
    {
        aliases: ["3D Realms"],
        label: "3D Realms",
        page: "3D Realms",
        categories: ["3D Realms遊戲"],
    },
    {
        aliases: ["4A Games"],
        label: "4A Games",
        page: "4A Games",
        categories: ["4A Games遊戲"],
    },
    {
        aliases: ["4J Studios"],
        label: "4J Studios",
        page: "4J Studios",
        categories: ["4J Studios遊戲"],
    },
    {
        aliases: ["4mm Games"],
        label: "4mm Games",
        page: "4mm Games",
        categories: ["4mm Games遊戲"],
    },
    {
        aliases: ["505游戏", "505-games", "505 Games"],
        label: "505游戏",
        page: "505游戏",
        categories: ["505遊戲遊戲"],
    },
    {
        aliases: ["5th Cell"],
        label: "5th Cell",
        page: "5th Cell",
        categories: ["5th Cell遊戲"],
    },
    {
        aliases: ["704Games"],
        label: "704Games",
        page: "704Games",
        categories: ["704Games遊戲"],
    },
    {
        aliases: ["7th Level"],
        label: "7th Level",
        page: "7th Level",
        categories: ["7th Level遊戲"],
    },
    {
        aliases: ["8-4"],
        label: "8-4",
        page: "8-4",
        categories: ["8-4遊戲"],
    },
    {
        aliases: ["989 Studios"],
        label: "989 Studios",
        page: "989 Studios",
        categories: ["989 Studios遊戲"],
    },
    {
        aliases: ["ABA Games"],
        label: "ABA Games",
        page: "ABA Games",
        categories: ["ABA Games遊戲"],
    },
    {
        aliases: ["ABS-CBN Digital Media"],
        label: "ABS-CBN Digital Media",
        page: "ABS-CBN Digital Media",
        categories: ["ABS-CBN Digital Media遊戲"],
    },
    {
        aliases: ["Absolute Entertainment"],
        label: "Absolute Entertainment",
        page: "Absolute Entertainment",
        categories: ["Absolute Entertainment遊戲"],
    },
    {
        aliases: ["Absurd Ventures"],
        label: "Absurd Ventures",
        page: "Absurd Ventures",
        categories: ["Absurd Ventures遊戲"],
    },
    {
        aliases: ["Access Games"],
        label: "Access Games",
        page: "Access Games",
        categories: ["Access Games遊戲"],
    },
    {
        aliases: ["Access Software"],
        label: "Access Software",
        page: "Access Software",
        categories: ["Access Software遊戲"],
    },
    {
        aliases: ["Acclaim Entertainment"],
        label: "Acclaim Entertainment",
        page: "Acclaim Entertainment",
        categories: ["Acclaim Entertainment遊戲"],
    },
    {
        aliases: ["Accolade", "accolade-inc", "Accolade, Inc."],
        label: "Accolade",
        page: "Accolade",
        categories: ["Accolade遊戲"],
    },
    {
        aliases: ["ACE Team"],
        label: "ACE Team",
        page: "ACE Team",
        categories: ["ACE Team遊戲"],
    },
    {
        aliases: ["Acornsoft"],
        label: "Acornsoft",
        page: "Acornsoft",
        categories: ["Acornsoft遊戲"],
    },
    {
        aliases: ["Acquire", "acquire-company", "Acquire (company)"],
        label: "Acquire",
        page: "Acquire",
        categories: ["Acquire遊戲"],
    },
    {
        aliases: ["Action Button Entertainment"],
        label: "Action Button Entertainment",
        page: "Action Button Entertainment",
        categories: ["Action Button Entertainment遊戲"],
    },
    {
        aliases: ["Action Forms"],
        label: "Action Forms",
        page: "Action Forms",
        categories: ["Action Forms遊戲"],
    },
    {
        aliases: ["Active Enterprises"],
        label: "Active Enterprises",
        page: "Active Enterprises",
        categories: ["Active Enterprises遊戲"],
    },
    {
        aliases: ["动视", "activision"],
        label: "动视",
        page: "动视",
        categories: ["動視遊戲"],
        stubTags: ["Activision-stub"],
    },
    {
        aliases: ["动视暴雪", "activision-blizzard", "Activision Blizzard"],
        label: "动视暴雪",
        page: "动视暴雪",
        categories: ["動視暴雪遊戲"],
    },
    {
        aliases: ["Actual Entertainment"],
        label: "Actual Entertainment",
        page: "Actual Entertainment",
        categories: ["Actual Entertainment遊戲"],
    },
    {
        aliases: ["AdHoc Studio"],
        label: "AdHoc Studio",
        page: "AdHoc Studio",
        categories: ["AdHoc Studio遊戲"],
    },
    {
        aliases: ["ADK (游戏公司)", "adk-corporation", "ADK Corporation"],
        label: "ADK (游戏公司)",
        page: "ADK (游戏公司)",
        categories: ["ADK (遊戲公司)遊戲"],
    },
    {
        aliases: ["Adult Swim Games"],
        label: "Adult Swim Games",
        page: "Adult Swim Games",
        categories: ["Adult Swim Games遊戲"],
    },
    {
        aliases: ["Adventure International"],
        label: "Adventure International",
        page: "Adventure International",
        categories: ["Adventure International遊戲"],
    },
    {
        aliases: ["Adventure Soft"],
        label: "Adventure Soft",
        page: "Adventure Soft",
        categories: ["Adventure Soft遊戲"],
    },
    {
        aliases: ["Aftershock PC"],
        label: "Aftershock PC",
        page: "Aftershock PC",
        categories: ["Aftershock PC遊戲"],
    },
    {
        aliases: ["Agate (game company)"],
        label: "Agate (game company)",
        page: "Agate (game company)",
        categories: ["Agate (game company)遊戲"],
    },
    {
        aliases: ["Agatsuma Entertainment"],
        label: "Agatsuma Entertainment",
        page: "Agatsuma Entertainment",
        categories: ["Agatsuma Entertainment遊戲"],
    },
    {
        aliases: ["AGD Interactive"],
        label: "AGD Interactive",
        page: "AGD Interactive",
        categories: ["AGD Interactive遊戲"],
    },
    {
        aliases: ["AGEod"],
        label: "AGEod",
        page: "AGEod",
        categories: ["AGEod遊戲"],
    },
    {
        aliases: ["Agetec"],
        label: "Agetec",
        page: "Agetec",
        categories: ["Agetec遊戲"],
    },
    {
        aliases: ["Aggro Crab"],
        label: "Aggro Crab",
        page: "Aggro Crab",
        categories: ["Aggro Crab遊戲"],
    },
    {
        aliases: ["Aicom"],
        label: "Aicom",
        page: "Aicom",
        categories: ["Aicom遊戲"],
    },
    {
        aliases: ["AirG Inc."],
        label: "AirG Inc.",
        page: "AirG Inc.",
        categories: ["AirG Inc.遊戲"],
    },
    {
        aliases: ["Airship Syndicate"],
        label: "Airship Syndicate",
        page: "Airship Syndicate",
        categories: ["Airship Syndicate遊戲"],
    },
    {
        aliases: ["Airtight Games"],
        label: "Airtight Games",
        page: "Airtight Games",
        categories: ["Airtight Games遊戲"],
    },
    {
        aliases: ["Akabeisoft2"],
        label: "Akabeisoft2",
        page: "Akabeisoft2",
        categories: ["Akabeisoft2遊戲"],
    },
    {
        aliases: ["Akella"],
        label: "Akella",
        page: "Akella",
        categories: ["Akella遊戲"],
    },
    {
        aliases: ["Aksys Games"],
        label: "Aksys Games",
        page: "Aksys Games",
        categories: ["Aksys Games遊戲"],
    },
    {
        aliases: ["Akupara Games"],
        label: "Akupara Games",
        page: "Akupara Games",
        categories: ["Akupara Games遊戲"],
    },
    {
        aliases: ["Alawar"],
        label: "Alawar",
        page: "Alawar",
        categories: ["Alawar遊戲"],
    },
    {
        aliases: ["Alcachofa Soft"],
        label: "Alcachofa Soft",
        page: "Alcachofa Soft",
        categories: ["Alcachofa Soft遊戲"],
    },
    {
        aliases: ["Alchemist", "alchemist-company", "Alchemist (company)"],
        label: "Alchemist",
        page: "Alchemist",
        categories: ["Alchemist遊戲"],
    },
    {
        aliases: ["Alfa System"],
        label: "Alfa System",
        page: "Alfa System",
        categories: ["Alfa System遊戲"],
    },
    {
        aliases: ["Aliasworlds Entertainment"],
        label: "Aliasworlds Entertainment",
        page: "Aliasworlds Entertainment",
        categories: ["Aliasworlds Entertainment遊戲"],
    },
    {
        aliases: ["Alice & Smith", "alice-and-smith"],
        label: "Alice & Smith",
        page: "Alice & Smith",
        categories: ["Alice & Smith遊戲"],
    },
    {
        aliases: ["All in! Games"],
        label: "All in! Games",
        page: "All in! Games",
        categories: ["All in! Games遊戲"],
    },
    {
        aliases: ["Allods Team"],
        label: "Allods Team",
        page: "Allods Team",
        categories: ["Allods Team遊戲"],
    },
    {
        aliases: ["AlphaDream"],
        label: "AlphaDream",
        page: "AlphaDream",
        categories: ["AlphaDream遊戲"],
    },
    {
        aliases: ["AlphaSim"],
        label: "AlphaSim",
        page: "AlphaSim",
        categories: ["AlphaSim遊戲"],
    },
    {
        aliases: ["Alvion"],
        label: "Alvion",
        page: "Alvion",
        categories: ["Alvion遊戲"],
    },
    {
        aliases: ["Amanita Design"],
        label: "Amanita Design",
        page: "Amanita Design",
        categories: ["Amanita Design遊戲"],
    },
    {
        aliases: [
            "亞馬遜遊戲工作室",
            "amazon-game-studios",
            "Amazon Game Studios",
            "亚马逊游戏工作室",
        ],
        label: "亞馬遜遊戲工作室",
        page: "亞馬遜遊戲工作室",
        categories: ["亞馬遜遊戲工作室遊戲"],
    },
    {
        aliases: ["Ambrella"],
        label: "Ambrella",
        page: "Ambrella",
        categories: ["Ambrella遊戲"],
    },
    {
        aliases: ["Ambrosia Software"],
        label: "Ambrosia Software",
        page: "Ambrosia Software",
        categories: ["Ambrosia Software遊戲"],
    },
    {
        aliases: ["American Game Cartridges"],
        label: "American Game Cartridges",
        page: "American Game Cartridges",
        categories: ["American Game Cartridges遊戲"],
    },
    {
        aliases: ["AmnesiaGames"],
        label: "AmnesiaGames",
        page: "AmnesiaGames",
        categories: ["AmnesiaGames遊戲"],
    },
    {
        aliases: ["Amplitude Studios"],
        label: "Amplitude Studios",
        page: "Amplitude Studios",
        categories: ["Amplitude Studios遊戲"],
    },
    {
        aliases: ["Amsoft"],
        label: "Amsoft",
        page: "Amsoft",
        categories: ["Amsoft遊戲"],
    },
    {
        aliases: ["Ancient (company)"],
        label: "Ancient (company)",
        page: "Ancient (company)",
        categories: ["Ancient (company)遊戲"],
    },
    {
        aliases: ["Animoca Brands"],
        label: "Animoca Brands",
        page: "Animoca Brands",
        categories: ["Animoca Brands遊戲"],
    },
    {
        aliases: ["Anino Games"],
        label: "Anino Games",
        page: "Anino Games",
        categories: ["Anino Games遊戲"],
    },
    {
        aliases: [
            "安纳布尔纳互动",
            "annapurna-interactive",
            "Annapurna Interactive",
        ],
        label: "安纳布尔纳互动",
        page: "安纳布尔纳互动",
        categories: ["安納布爾納互動遊戲"],
    },
    {
        aliases: ["Antimatter Games"],
        label: "Antimatter Games",
        page: "Antimatter Games",
        categories: ["Antimatter Games遊戲"],
    },
    {
        aliases: ["Apex Computer Productions"],
        label: "Apex Computer Productions",
        page: "Apex Computer Productions",
        categories: ["Apex Computer Productions遊戲"],
    },
    {
        aliases: ["Apogee Entertainment"],
        label: "Apogee Entertainment",
        page: "Apogee Entertainment",
        categories: ["Apogee Entertainment遊戲"],
    },
    {
        aliases: ["AQ Interactive"],
        label: "AQ Interactive",
        page: "AQ Interactive",
        categories: ["AQ Interactive遊戲"],
    },
    {
        aliases: ["Aquaplus"],
        label: "Aquaplus",
        page: "Aquaplus",
        categories: ["Aquaplus遊戲"],
    },
    {
        aliases: ["Aquria"],
        label: "Aquria",
        page: "Aquria",
        categories: ["Aquria遊戲"],
    },
    {
        aliases: [
            "亞克系統",
            "arc-system-works",
            "Arc System Works",
            "亚克系统",
        ],
        label: "亞克系統",
        page: "亞克系統",
        categories: ["亞克系統遊戲"],
    },
    {
        aliases: ["Arcadia Systems"],
        label: "Arcadia Systems",
        page: "Arcadia Systems",
        categories: ["Arcadia Systems遊戲"],
    },
    {
        aliases: ["Arcen Games"],
        label: "Arcen Games",
        page: "Arcen Games",
        categories: ["Arcen Games遊戲"],
    },
    {
        aliases: ["Archetype Entertainment"],
        label: "Archetype Entertainment",
        page: "Archetype Entertainment",
        categories: ["Archetype Entertainment遊戲"],
    },
    {
        aliases: ["Archimage"],
        label: "Archimage",
        page: "Archimage",
        categories: ["Archimage遊戲"],
    },
    {
        aliases: ["ArenaNet"],
        label: "ArenaNet",
        page: "ArenaNet",
        categories: ["ArenaNet遊戲"],
    },
    {
        aliases: ["Argonaut Games"],
        label: "Argonaut Games",
        page: "Argonaut Games",
        categories: ["Argonaut Games遊戲"],
    },
    {
        aliases: ["Arika"],
        label: "Arika",
        page: "Arika",
        categories: ["Arika遊戲"],
    },
    {
        aliases: ["Ariolasoft"],
        label: "Ariolasoft",
        page: "Ariolasoft",
        categories: ["Ariolasoft遊戲"],
    },
    {
        aliases: ["Arkane Studios"],
        label: "Arkane Studios",
        page: "Arkane Studios",
        categories: ["Arkane Studios遊戲"],
    },
    {
        aliases: ["Arkedo Studio"],
        label: "Arkedo Studio",
        page: "Arkedo Studio",
        categories: ["Arkedo Studio遊戲"],
    },
    {
        aliases: ["Armature Studio"],
        label: "Armature Studio",
        page: "Armature Studio",
        categories: ["Armature Studio遊戲"],
    },
    {
        aliases: ["Armor Games"],
        label: "Armor Games",
        page: "Armor Games",
        categories: ["Armor Games遊戲"],
    },
    {
        aliases: ["Arrowhead Game Studios"],
        label: "Arrowhead Game Studios",
        page: "Arrowhead Game Studios",
        categories: ["Arrowhead Game Studios遊戲"],
    },
    {
        aliases: ["Arsys Software"],
        label: "Arsys Software",
        page: "Arsys Software",
        categories: ["Arsys Software遊戲"],
    },
    {
        aliases: ["Art Data Interactive"],
        label: "Art Data Interactive",
        page: "Art Data Interactive",
        categories: ["Art Data Interactive遊戲"],
    },
    {
        aliases: ["Artdink"],
        label: "Artdink",
        page: "Artdink",
        categories: ["Artdink遊戲"],
    },
    {
        aliases: ["Artech Digital Entertainment"],
        label: "Artech Digital Entertainment",
        page: "Artech Digital Entertainment",
        categories: ["Artech Digital Entertainment遊戲"],
    },
    {
        aliases: ["ArtePiazza"],
        label: "ArtePiazza",
        page: "ArtePiazza",
        categories: ["ArtePiazza遊戲"],
    },
    {
        aliases: ["Artificial Studios"],
        label: "Artificial Studios",
        page: "Artificial Studios",
        categories: ["Artificial Studios遊戲"],
    },
    {
        aliases: ["Artix Entertainment"],
        label: "Artix Entertainment",
        page: "Artix Entertainment",
        categories: ["Artix Entertainment遊戲"],
    },
    {
        aliases: ["Artoon"],
        label: "Artoon",
        page: "Artoon",
        categories: ["Artoon遊戲"],
    },
    {
        aliases: ["Arush Entertainment"],
        label: "Arush Entertainment",
        page: "Arush Entertainment",
        categories: ["Arush Entertainment遊戲"],
    },
    {
        aliases: ["Arzest"],
        label: "Arzest",
        page: "Arzest",
        categories: ["Arzest遊戲"],
    },
    {
        aliases: ["Ascaron"],
        label: "Ascaron",
        page: "Ascaron",
        categories: ["Ascaron遊戲"],
    },
    {
        aliases: ["ASCII Corporation"],
        label: "ASCII Corporation",
        page: "ASCII Corporation",
        categories: ["ASCII Corporation遊戲"],
    },
    {
        aliases: ["Asobo工作室", "asobo-studio", "Asobo Studio"],
        label: "Asobo工作室",
        page: "Asobo工作室",
        categories: ["Asobo工作室遊戲"],
    },
    {
        aliases: ["Asobu"],
        label: "Asobu",
        page: "Asobu",
        categories: ["Asobu遊戲"],
    },
    {
        aliases: ["Asphere Innovations"],
        label: "Asphere Innovations",
        page: "Asphere Innovations",
        categories: ["Asphere Innovations遊戲"],
    },
    {
        aliases: ["Aspyr"],
        label: "Aspyr",
        page: "Aspyr",
        categories: ["Aspyr遊戲"],
    },
    {
        aliases: ["Astra Logical"],
        label: "Astra Logical",
        page: "Astra Logical",
        categories: ["Astra Logical遊戲"],
    },
    {
        aliases: ["Astragon"],
        label: "Astragon",
        page: "Astragon",
        categories: ["Astragon遊戲"],
    },
    {
        aliases: ["雅达利游戏", "atari-games", "Atari Games"],
        label: "雅达利游戏",
        page: "雅达利游戏",
        categories: ["雅達利遊戲遊戲"],
        stubTags: ["Atari-stub"],
    },
    {
        aliases: ["雅達利公司", "atari-inc", "Atari, Inc."],
        label: "雅達利公司",
        page: "雅達利公司",
        categories: ["雅達利公司遊戲"],
        stubTags: ["Atari-stub"],
    },
    {
        aliases: ["Atari, Inc. (formerly GT Interactive)"],
        label: "Atari, Inc. (formerly GT Interactive)",
        page: "Atari, Inc. (formerly GT Interactive)",
        categories: ["Atari, Inc. (formerly GT Interactive)遊戲"],
        stubTags: ["Atari-stub"],
    },
    {
        aliases: ["雅達利SA", "atari-sa", "Atari SA", "雅达利SA"],
        label: "雅達利SA",
        page: "雅達利SA",
        categories: ["雅達利SA遊戲"],
        stubTags: ["Atari-stub"],
    },
    {
        aliases: ["Ateam Inc."],
        label: "Ateam Inc.",
        page: "Ateam Inc.",
        categories: ["Ateam Inc.遊戲"],
    },
    {
        aliases: ["Atelier 801"],
        label: "Atelier 801",
        page: "Atelier 801",
        categories: ["Atelier 801遊戲"],
    },
    {
        aliases: ["Athena (game developer)"],
        label: "Athena (game developer)",
        page: "Athena (game developer)",
        categories: ["Athena (game developer)遊戲"],
    },
    {
        aliases: ["Atlus"],
        label: "Atlus",
        page: "Atlus",
        categories: ["Atlus遊戲"],
    },
    {
        aliases: ["Atod"],
        label: "Atod",
        page: "Atod",
        categories: ["Atod遊戲"],
    },
    {
        aliases: ["Atomic Games"],
        label: "Atomic Games",
        page: "Atomic Games",
        categories: ["Atomic Games遊戲"],
    },
    {
        aliases: ["Attic Entertainment Software"],
        label: "Attic Entertainment Software",
        page: "Attic Entertainment Software",
        categories: ["Attic Entertainment Software遊戲"],
    },
    {
        aliases: ["AudioGaming"],
        label: "AudioGaming",
        page: "AudioGaming",
        categories: ["AudioGaming遊戲"],
    },
    {
        aliases: ["Audiogenic"],
        label: "Audiogenic",
        page: "Audiogenic",
        categories: ["Audiogenic遊戲"],
    },
    {
        aliases: ["Audiokinetic"],
        label: "Audiokinetic",
        page: "Audiokinetic",
        categories: ["Audiokinetic遊戲"],
    },
    {
        aliases: ["Auroch Digital"],
        label: "Auroch Digital",
        page: "Auroch Digital",
        categories: ["Auroch Digital遊戲"],
    },
    {
        aliases: ["Autumn Games"],
        label: "Autumn Games",
        page: "Autumn Games",
        categories: ["Autumn Games遊戲"],
    },
    {
        aliases: ["Avalanche Software"],
        label: "Avalanche Software",
        page: "Avalanche Software",
        categories: ["Avalanche Software遊戲"],
    },
    {
        aliases: [
            "雪崩工作室",
            "avalanche-studios-group",
            "Avalanche Studios Group",
            "雪崩工作室集团",
        ],
        label: "雪崩工作室",
        page: "雪崩工作室",
        categories: ["雪崩工作室集團遊戲"],
    },
    {
        aliases: ["Avalon Hill"],
        label: "Avalon Hill",
        page: "Avalon Hill",
        categories: ["Avalon Hill遊戲"],
    },
    {
        aliases: ["Avantgarden"],
        label: "Avantgarden",
        page: "Avantgarden",
        categories: ["Avantgarden遊戲"],
    },
    {
        aliases: ["Avatar Reality"],
        label: "Avatar Reality",
        page: "Avatar Reality",
        categories: ["Avatar Reality遊戲"],
    },
    {
        aliases: ["Aventurine SA"],
        label: "Aventurine SA",
        page: "Aventurine SA",
        categories: ["Aventurine SA遊戲"],
    },
    {
        aliases: ["Awem"],
        label: "Awem",
        page: "Awem",
        categories: ["Awem遊戲"],
    },
    {
        aliases: ["B2B Games"],
        label: "B2B Games",
        page: "B2B Games",
        categories: ["B2B Games遊戲"],
    },
    {
        aliases: ["Backbone Entertainment"],
        label: "Backbone Entertainment",
        page: "Backbone Entertainment",
        categories: ["Backbone Entertainment遊戲"],
    },
    {
        aliases: ["BAM! Entertainment"],
        label: "BAM! Entertainment",
        page: "BAM! Entertainment",
        categories: ["BAM! Entertainment遊戲"],
    },
    {
        aliases: ["萬代", "bandai", "万代"],
        label: "萬代",
        page: "萬代",
        categories: ["萬代遊戲"],
    },
    {
        aliases: [
            "万代南梦宫娱乐",
            "bandai-namco-entertainment",
            "Bandai Namco Entertainment",
        ],
        label: "万代南梦宫娱乐",
        page: "万代南梦宫娱乐",
        categories: ["萬代南夢宮遊戲"],
        stubTags: ["BandaiNamco-stub"],
    },
    {
        aliases: ["Bandai Namco Forge Digitals"],
        label: "Bandai Namco Forge Digitals",
        page: "Bandai Namco Forge Digitals",
        categories: ["萬代南夢宮遊戲"],
        stubTags: ["BandaiNamco-stub"],
    },
    {
        aliases: [
            "万代南梦宫工作室",
            "bandai-namco-studios",
            "Bandai Namco Studios",
        ],
        label: "万代南梦宫工作室",
        page: "万代南梦宫工作室",
        categories: ["萬代南夢宮遊戲"],
        stubTags: ["BandaiNamco-stub"],
    },
    {
        aliases: ["Banpresto"],
        label: "Banpresto",
        page: "Banpresto",
        categories: ["Banpresto遊戲"],
    },
    {
        aliases: ["BAP Interactive"],
        label: "BAP Interactive",
        page: "BAP Interactive",
        categories: ["BAP Interactive遊戲"],
    },
    {
        aliases: ["Barking Lizards Technologies"],
        label: "Barking Lizards Technologies",
        page: "Barking Lizards Technologies",
        categories: ["Barking Lizards Technologies遊戲"],
    },
    {
        aliases: ["Battlefront.com"],
        label: "Battlefront.com",
        page: "Battlefront.com",
        categories: ["Battlefront.com遊戲"],
    },
    {
        aliases: ["Bauhaus Entertainment"],
        label: "Bauhaus Entertainment",
        page: "Bauhaus Entertainment",
        categories: ["Bauhaus Entertainment遊戲"],
    },
    {
        aliases: ["BBC Multimedia"],
        label: "BBC Multimedia",
        page: "BBC Multimedia",
        categories: ["BBC Multimedia遊戲"],
    },
    {
        aliases: ["Beach Bum Ltd."],
        label: "Beach Bum Ltd.",
        page: "Beach Bum Ltd.",
        categories: ["Beach Bum Ltd.遊戲"],
    },
    {
        aliases: ["Beachhead Studio"],
        label: "Beachhead Studio",
        page: "Beachhead Studio",
        categories: ["Beachhead Studio遊戲"],
    },
    {
        aliases: ["Beam Software"],
        label: "Beam Software",
        page: "Beam Software",
        categories: ["Beam Software遊戲"],
    },
    {
        aliases: ["Beamdog"],
        label: "Beamdog",
        page: "Beamdog",
        categories: ["Beamdog遊戲"],
    },
    {
        aliases: ["Beatshapers"],
        label: "Beatshapers",
        page: "Beatshapers",
        categories: ["Beatshapers遊戲"],
    },
    {
        aliases: ["Beenox"],
        label: "Beenox",
        page: "Beenox",
        categories: ["Beenox遊戲"],
    },
    {
        aliases: ["Behaviour Interactive"],
        label: "Behaviour Interactive",
        page: "Behaviour Interactive",
        categories: ["Behaviour Interactive遊戲"],
    },
    {
        aliases: ["Behaviour Santiago"],
        label: "Behaviour Santiago",
        page: "Behaviour Santiago",
        categories: ["Behaviour Santiago遊戲"],
    },
    {
        aliases: ["Bend Studio"],
        label: "Bend Studio",
        page: "Bend Studio",
        categories: ["Bend Studio遊戲"],
    },
    {
        aliases: ["Berkeley Systems"],
        label: "Berkeley Systems",
        page: "Berkeley Systems",
        categories: ["Berkeley Systems遊戲"],
    },
    {
        aliases: ["BetaDwarf"],
        label: "BetaDwarf",
        page: "BetaDwarf",
        categories: ["BetaDwarf遊戲"],
    },
    {
        aliases: [
            "贝塞斯达游戏工作室",
            "bethesda-game-studios",
            "Bethesda Game Studios",
        ],
        label: "贝塞斯达游戏工作室",
        page: "贝塞斯达游戏工作室",
        categories: ["貝塞斯達遊戲工作室遊戲"],
    },
    {
        aliases: ["贝塞斯达软件", "bethesda-softworks", "Bethesda Softworks"],
        label: "贝塞斯达软件",
        page: "贝塞斯达软件",
        categories: ["貝塞斯達軟件遊戲"],
        stubTags: ["BethesdaSoftworks-stub"],
    },
    {
        aliases: ["Big Ant Studios"],
        label: "Big Ant Studios",
        page: "Big Ant Studios",
        categories: ["Big Ant Studios遊戲"],
    },
    {
        aliases: ["Big Blue Bubble"],
        label: "Big Blue Bubble",
        page: "Big Blue Bubble",
        categories: ["Big Blue Bubble遊戲"],
    },
    {
        aliases: ["Big Finish Games"],
        label: "Big Finish Games",
        page: "Big Finish Games",
        categories: ["Big Finish Games遊戲"],
    },
    {
        aliases: ["Big Fish Games"],
        label: "Big Fish Games",
        page: "Big Fish Games",
        categories: ["Big Fish Games遊戲"],
    },
    {
        aliases: ["Big Huge Games"],
        label: "Big Huge Games",
        page: "Big Huge Games",
        categories: ["Big Huge Games遊戲"],
    },
    {
        aliases: ["Big Red Software"],
        label: "Big Red Software",
        page: "Big Red Software",
        categories: ["Big Red Software遊戲"],
    },
    {
        aliases: ["Bigbig Studios"],
        label: "Bigbig Studios",
        page: "Bigbig Studios",
        categories: ["Bigbig Studios遊戲"],
    },
    {
        aliases: ["Bigpoint"],
        label: "Bigpoint",
        page: "Bigpoint",
        categories: ["Bigpoint遊戲"],
    },
    {
        aliases: ["Birthday (company)"],
        label: "Birthday (company)",
        page: "Birthday (company)",
        categories: ["Birthday (company)遊戲"],
    },
    {
        aliases: ["Bit Corporation"],
        label: "Bit Corporation",
        page: "Bit Corporation",
        categories: ["Bit Corporation遊戲"],
    },
    {
        aliases: ["Bit Managers"],
        label: "Bit Managers",
        page: "Bit Managers",
        categories: ["Bit Managers遊戲"],
    },
    {
        aliases: ["Bits Studios"],
        label: "Bits Studios",
        page: "Bits Studios",
        categories: ["Bits Studios遊戲"],
    },
    {
        aliases: ["Bizarre Creations"],
        label: "Bizarre Creations",
        page: "Bizarre Creations",
        categories: ["Bizarre Creations遊戲"],
    },
    {
        aliases: [
            "Black Forest游戏",
            "black-forest-games",
            "Black Forest Games",
        ],
        label: "Black Forest游戏",
        page: "Black Forest游戏",
        categories: ["Black Forest遊戲遊戲"],
    },
    {
        aliases: ["Black Hole Entertainment"],
        label: "Black Hole Entertainment",
        page: "Black Hole Entertainment",
        categories: ["Black Hole Entertainment遊戲"],
    },
    {
        aliases: [
            "黑島工作室",
            "black-isle-studios",
            "Black Isle Studios",
            "黑岛工作室",
        ],
        label: "黑島工作室",
        page: "黑島工作室",
        categories: ["黑島工作室遊戲"],
    },
    {
        aliases: ["Black Legend (company)"],
        label: "Black Legend (company)",
        page: "Black Legend (company)",
        categories: ["Black Legend (company)遊戲"],
    },
    {
        aliases: ["Black Ops Entertainment"],
        label: "Black Ops Entertainment",
        page: "Black Ops Entertainment",
        categories: ["Black Ops Entertainment遊戲"],
    },
    {
        aliases: ["Black Rock Studio"],
        label: "Black Rock Studio",
        page: "Black Rock Studio",
        categories: ["Black Rock Studio遊戲"],
    },
    {
        aliases: ["Black Widow Games"],
        label: "Black Widow Games",
        page: "Black Widow Games",
        categories: ["Black Widow Games遊戲"],
    },
    {
        aliases: ["Blackbird Interactive"],
        label: "Blackbird Interactive",
        page: "Blackbird Interactive",
        categories: ["Blackbird Interactive遊戲"],
    },
    {
        aliases: ["Blendo Games"],
        label: "Blendo Games",
        page: "Blendo Games",
        categories: ["Blendo Games遊戲"],
    },
    {
        aliases: ["Blitz Games Studios"],
        label: "Blitz Games Studios",
        page: "Blitz Games Studios",
        categories: ["Blitz Games Studios遊戲"],
    },
    {
        aliases: ["Blizzard Albany"],
        label: "Blizzard Albany",
        page: "Blizzard Albany",
        categories: ["Blizzard Albany遊戲"],
    },
    {
        aliases: ["Blizzard Boston"],
        label: "Blizzard Boston",
        page: "Blizzard Boston",
        categories: ["Blizzard Boston遊戲"],
    },
    {
        aliases: [
            "暴雪娛樂",
            "blizzard-entertainment",
            "Blizzard Entertainment",
            "暴雪娱乐",
        ],
        label: "暴雪娛樂",
        page: "暴雪娛樂",
        categories: ["暴雪娛樂遊戲"],
        stubTags: ["BlizzardEntertainment-stub"],
    },
    {
        aliases: ["暴雪北方", "blizzard-north", "Blizzard North"],
        label: "暴雪北方",
        page: "暴雪北方",
        categories: ["暴雪北方遊戲"],
    },
    {
        aliases: ["Bloober Team"],
        label: "Bloober Team",
        page: "Bloober Team",
        categories: ["Bloober Team遊戲"],
    },
    {
        aliases: ["Blue Fang Games"],
        label: "Blue Fang Games",
        page: "Blue Fang Games",
        categories: ["Blue Fang Games遊戲"],
    },
    {
        aliases: ["Blue Planet Software"],
        label: "Blue Planet Software",
        page: "Blue Planet Software",
        categories: ["Blue Planet Software遊戲"],
    },
    {
        aliases: ["Blue Ribbon (software house)"],
        label: "Blue Ribbon (software house)",
        page: "Blue Ribbon (software house)",
        categories: ["Blue Ribbon (software house)遊戲"],
    },
    {
        aliases: ["Blue Sky Rangers"],
        label: "Blue Sky Rangers",
        page: "Blue Sky Rangers",
        categories: ["Blue Sky Rangers遊戲"],
    },
    {
        aliases: ["Blue Tea Games"],
        label: "Blue Tea Games",
        page: "Blue Tea Games",
        categories: ["Blue Tea Games遊戲"],
    },
    {
        aliases: ["Blue Tongue Entertainment"],
        label: "Blue Tongue Entertainment",
        page: "Blue Tongue Entertainment",
        categories: ["Blue Tongue Entertainment遊戲"],
    },
    {
        aliases: ["Blue Wizard Digital"],
        label: "Blue Wizard Digital",
        page: "Blue Wizard Digital",
        categories: ["Blue Wizard Digital遊戲"],
    },
    {
        aliases: ["蓝点游戏工作室", "bluepoint-games", "Bluepoint Games"],
        label: "蓝点游戏工作室",
        page: "蓝点游戏工作室",
        categories: ["藍點遊戲工作室遊戲"],
    },
    {
        aliases: ["BlueSky Software"],
        label: "BlueSky Software",
        page: "BlueSky Software",
        categories: ["BlueSky Software遊戲"],
    },
    {
        aliases: ["Blumhouse Games"],
        label: "Blumhouse Games",
        page: "Blumhouse Games",
        categories: ["Blumhouse Games遊戲"],
    },
    {
        aliases: ["Boffo Games"],
        label: "Boffo Games",
        page: "Boffo Games",
        categories: ["Boffo Games遊戲"],
    },
    {
        aliases: [
            "波希米亞互動工作室",
            "bohemia-interactive",
            "Bohemia Interactive",
            "波希米亚互动",
        ],
        label: "波希米亞互動工作室",
        page: "波希米亞互動工作室",
        categories: ["波希米亞互動遊戲"],
    },
    {
        aliases: ["Boneloaf"],
        label: "Boneloaf",
        page: "Boneloaf",
        categories: ["Boneloaf遊戲"],
    },
    {
        aliases: ["Bonfire Studios"],
        label: "Bonfire Studios",
        page: "Bonfire Studios",
        categories: ["Bonfire Studios遊戲"],
    },
    {
        aliases: ["Bongfish"],
        label: "Bongfish",
        page: "Bongfish",
        categories: ["Bongfish遊戲"],
    },
    {
        aliases: ["Brace Yourself Games"],
        label: "Brace Yourself Games",
        page: "Brace Yourself Games",
        categories: ["Brace Yourself Games遊戲"],
    },
    {
        aliases: ["Brash Entertainment"],
        label: "Brash Entertainment",
        page: "Brash Entertainment",
        categories: ["Brash Entertainment遊戲"],
    },
    {
        aliases: ["Brøderbund", "broderbund"],
        label: "Brøderbund",
        page: "Brøderbund",
        categories: ["Brøderbund遊戲"],
    },
    {
        aliases: ["Broken Rules"],
        label: "Broken Rules",
        page: "Broken Rules",
        categories: ["Broken Rules遊戲"],
    },
    {
        aliases: ["Bug-Byte"],
        label: "Bug-Byte",
        page: "Bug-Byte",
        categories: ["Bug-Byte遊戲"],
    },
    {
        aliases: ["Buka Entertainment"],
        label: "Buka Entertainment",
        page: "Buka Entertainment",
        categories: ["Buka Entertainment遊戲"],
    },
    {
        aliases: ["BulkyPix"],
        label: "BulkyPix",
        page: "BulkyPix",
        categories: ["BulkyPix遊戲"],
    },
    {
        aliases: ["Bungie"],
        label: "Bungie",
        page: "Bungie",
        categories: ["Bungie遊戲"],
    },
    {
        aliases: ["武士道", "bushiroad"],
        label: "武士道",
        page: "武士道",
        categories: ["武士道遊戲"],
    },
    {
        aliases: ["C&E", "c-and-e"],
        label: "C&E",
        page: "C&E",
        categories: ["C&E遊戲"],
    },
    {
        aliases: ["Camerica"],
        label: "Camerica",
        page: "Camerica",
        categories: ["Camerica遊戲"],
    },
    {
        aliases: ["卡普空", "capcom"],
        label: "卡普空",
        page: "卡普空",
        categories: ["卡普空遊戲"],
        stubTags: ["Capcom-stub"],
    },
    {
        aliases: ["Capstone Software"],
        label: "Capstone Software",
        page: "Capstone Software",
        categories: ["Capstone Software遊戲"],
    },
    {
        aliases: ["Cavedog Entertainment"],
        label: "Cavedog Entertainment",
        page: "Cavedog Entertainment",
        categories: ["Cavedog Entertainment遊戲"],
    },
    {
        aliases: ["CD Projekt"],
        label: "CD Projekt",
        page: "CD Projekt",
        categories: ["CD Projekt遊戲"],
    },
    {
        aliases: ["CDC Games"],
        label: "CDC Games",
        page: "CDC Games",
        categories: ["CDC Games遊戲"],
    },
    {
        aliases: ["CDP.pl"],
        label: "CDP.pl",
        page: "CDP.pl",
        categories: ["CDP.pl遊戲"],
    },
    {
        aliases: ["CDS Software"],
        label: "CDS Software",
        page: "CDS Software",
        categories: ["CDS Software遊戲"],
    },
    {
        aliases: ["CDV Software"],
        label: "CDV Software",
        page: "CDV Software",
        categories: ["CDV Software遊戲"],
    },
    {
        aliases: ["Centuri"],
        label: "Centuri",
        page: "Centuri",
        categories: ["Centuri遊戲"],
    },
    {
        aliases: ["ChampionSoft"],
        label: "ChampionSoft",
        page: "ChampionSoft",
        categories: ["ChampionSoft遊戲"],
    },
    {
        aliases: ["Chucklefish"],
        label: "Chucklefish",
        page: "Chucklefish",
        categories: ["Chucklefish遊戲"],
    },
    {
        aliases: ["Chunsoft Co., Ltd."],
        label: "Chunsoft Co., Ltd.",
        page: "Chunsoft Co., Ltd.",
        categories: ["Chunsoft Co., Ltd.遊戲"],
    },
    {
        aliases: ["CI Games"],
        label: "CI Games",
        page: "CI Games",
        categories: ["CI Games遊戲"],
    },
    {
        aliases: ["CM Games"],
        label: "CM Games",
        page: "CM Games",
        categories: ["CM Games遊戲"],
    },
    {
        aliases: ["Codemasters"],
        label: "Codemasters",
        page: "Codemasters",
        categories: ["Codemasters遊戲"],
    },
    {
        aliases: ["Coffee Stain Studios"],
        label: "Coffee Stain Studios",
        page: "Coffee Stain Studios",
        categories: ["Coffee Stain Studios遊戲"],
    },
    {
        aliases: ["Collavier Corporation"],
        label: "Collavier Corporation",
        page: "Collavier Corporation",
        categories: ["Collavier Corporation遊戲"],
    },
    {
        aliases: ["Conspiracy Entertainment"],
        label: "Conspiracy Entertainment",
        page: "Conspiracy Entertainment",
        categories: ["Conspiracy Entertainment遊戲"],
    },
    {
        aliases: ["Core Design"],
        label: "Core Design",
        page: "Core Design",
        categories: ["Core Design遊戲"],
    },
    {
        aliases: ["Crave Entertainment"],
        label: "Crave Entertainment",
        page: "Crave Entertainment",
        categories: ["Crave Entertainment遊戲"],
    },
    {
        aliases: ["Creat Studios"],
        label: "Creat Studios",
        page: "Creat Studios",
        categories: ["Creat Studios遊戲"],
    },
    {
        aliases: [
            "The Creative Assembly",
            "creative-assembly",
            "Creative Assembly",
        ],
        label: "The Creative Assembly",
        page: "The Creative Assembly",
        categories: ["The Creative Assembly遊戲"],
    },
    {
        aliases: ["CreativeForge Games"],
        label: "CreativeForge Games",
        page: "CreativeForge Games",
        categories: ["CreativeForge Games遊戲"],
    },
    {
        aliases: ["Criterion Games"],
        label: "Criterion Games",
        page: "Criterion Games",
        categories: ["Criterion Games遊戲"],
    },
    {
        aliases: ["Critical Gameplay"],
        label: "Critical Gameplay",
        page: "Critical Gameplay",
        categories: ["Critical Gameplay遊戲"],
    },
    {
        aliases: ["Critical Reflex"],
        label: "Critical Reflex",
        page: "Critical Reflex",
        categories: ["Critical Reflex遊戲"],
    },
    {
        aliases: ["CRL Group"],
        label: "CRL Group",
        page: "CRL Group",
        categories: ["CRL Group遊戲"],
    },
    {
        aliases: ["Cryo Interactive"],
        label: "Cryo Interactive",
        page: "Cryo Interactive",
        categories: ["Cryo Interactive遊戲"],
    },
    {
        aliases: ["Crystal Computing"],
        label: "Crystal Computing",
        page: "Crystal Computing",
        categories: ["Crystal Computing遊戲"],
    },
    {
        aliases: ["晶体动力", "crystal-dynamics", "Crystal Dynamics"],
        label: "晶体动力",
        page: "晶体动力",
        categories: ["晶體動力遊戲"],
    },
    {
        aliases: ["Crytek"],
        label: "Crytek",
        page: "Crytek",
        categories: ["Crytek遊戲"],
    },
    {
        aliases: ["Crytivo"],
        label: "Crytivo",
        page: "Crytivo",
        categories: ["Crytivo遊戲"],
    },
    {
        aliases: ["Culture Brain"],
        label: "Culture Brain",
        page: "Culture Brain",
        categories: ["Culture Brain遊戲"],
    },
    {
        aliases: ["Curve Games"],
        label: "Curve Games",
        page: "Curve Games",
        categories: ["Curve Games遊戲"],
    },
    {
        aliases: ["Cyan", "cyan-worlds", "Cyan Worlds"],
        label: "Cyan",
        page: "Cyan",
        categories: ["Cyan遊戲"],
    },
    {
        aliases: ["CyberAgent"],
        label: "CyberAgent",
        page: "CyberAgent",
        categories: ["CyberAgent遊戲"],
    },
    {
        aliases: ["CyberConnect2"],
        label: "CyberConnect2",
        page: "CyberConnect2",
        categories: ["CyberConnect2遊戲"],
    },
    {
        aliases: ["Cybersoft (video game company)"],
        label: "Cybersoft (video game company)",
        page: "Cybersoft (video game company)",
        categories: ["Cybersoft (video game company)遊戲"],
    },
    {
        aliases: ["CyberStep"],
        label: "CyberStep",
        page: "CyberStep",
        categories: ["CyberStep遊戲"],
    },
    {
        aliases: ["D3 Publisher"],
        label: "D3 Publisher",
        page: "D3 Publisher",
        categories: ["D3 Publisher遊戲"],
    },
    {
        aliases: ["D4 Enterprise"],
        label: "D4 Enterprise",
        page: "D4 Enterprise",
        categories: ["D4 Enterprise遊戲"],
    },
    {
        aliases: ["Daedalic Entertainment"],
        label: "Daedalic Entertainment",
        page: "Daedalic Entertainment",
        categories: ["Daedalic Entertainment遊戲"],
    },
    {
        aliases: ["Dark Energy Digital"],
        label: "Dark Energy Digital",
        page: "Dark Energy Digital",
        categories: ["Dark Energy Digital遊戲"],
    },
    {
        aliases: ["Datcroft Games"],
        label: "Datcroft Games",
        page: "Datcroft Games",
        categories: ["Datcroft Games遊戲"],
    },
    {
        aliases: [
            "黎明游戏公司",
            "daybreak-game-company",
            "Daybreak Game Company",
        ],
        label: "黎明游戏公司",
        page: "黎明游戏公司",
        categories: ["黎明遊戲公司遊戲"],
    },
    {
        aliases: ["DB-SOFT"],
        label: "DB-SOFT",
        page: "DB-SOFT",
        categories: ["DB-SOFT遊戲"],
    },
    {
        aliases: ["Dear Villagers"],
        label: "Dear Villagers",
        page: "Dear Villagers",
        categories: ["Dear Villagers遊戲"],
    },
    {
        aliases: ["Deca Games"],
        label: "Deca Games",
        page: "Deca Games",
        categories: ["Deca Games遊戲"],
    },
    {
        aliases: ["Deck13"],
        label: "Deck13",
        page: "Deck13",
        categories: ["Deck13遊戲"],
    },
    {
        aliases: ["Deep Silver"],
        label: "Deep Silver",
        page: "Deep Silver",
        categories: ["Deep Silver遊戲"],
    },
    {
        aliases: ["Delta Tao Software"],
        label: "Delta Tao Software",
        page: "Delta Tao Software",
        categories: ["Delta Tao Software遊戲"],
    },
    {
        aliases: ["DeNA"],
        label: "DeNA",
        page: "DeNA",
        categories: ["DeNA遊戲"],
    },
    {
        aliases: ["Desk Plant"],
        label: "Desk Plant",
        page: "Desk Plant",
        categories: ["Desk Plant遊戲"],
    },
    {
        aliases: ["Destineer"],
        label: "Destineer",
        page: "Destineer",
        categories: ["Destineer遊戲"],
    },
    {
        aliases: ["Devolver Digital"],
        label: "Devolver Digital",
        page: "Devolver Digital",
        categories: ["Devolver Digital遊戲"],
    },
    {
        aliases: ["Digital Bros"],
        label: "Digital Bros",
        page: "Digital Bros",
        categories: ["Digital Bros遊戲"],
    },
    {
        aliases: ["Digital Extremes"],
        label: "Digital Extremes",
        page: "Digital Extremes",
        categories: ["Digital Extremes遊戲"],
    },
    {
        aliases: ["Digital Happiness"],
        label: "Digital Happiness",
        page: "Digital Happiness",
        categories: ["Digital Happiness遊戲"],
    },
    {
        aliases: [
            "EA Digital Illusions CE",
            "digital-illusions-ce",
            "Digital Illusions CE",
        ],
        label: "EA Digital Illusions CE",
        page: "EA Digital Illusions CE",
        categories: ["EA Digital Illusions CE遊戲"],
        stubTags: ["ElectronicArts-stub"],
    },
    {
        aliases: ["Digital Jesters"],
        label: "Digital Jesters",
        page: "Digital Jesters",
        categories: ["Digital Jesters遊戲"],
    },
    {
        aliases: ["Digital Leisure"],
        label: "Digital Leisure",
        page: "Digital Leisure",
        categories: ["Digital Leisure遊戲"],
    },
    {
        aliases: ["Dimple Entertainment"],
        label: "Dimple Entertainment",
        page: "Dimple Entertainment",
        categories: ["Dimple Entertainment遊戲"],
    },
    {
        aliases: ["Disney Consumer Products"],
        label: "Disney Consumer Products",
        page: "Disney Consumer Products",
        categories: ["Disney Consumer Products遊戲"],
    },
    {
        aliases: ["Disney Interactive"],
        label: "Disney Interactive",
        page: "Disney Interactive",
        categories: ["Disney Interactive遊戲"],
        stubTags: ["Disney-videogame-stub"],
    },
    {
        aliases: [
            "迪士尼互动工作室",
            "disney-interactive-studios",
            "Disney Interactive Studios",
        ],
        label: "迪士尼互动工作室",
        page: "迪士尼互动工作室",
        categories: ["迪士尼互動工作室遊戲"],
        stubTags: ["Disney-videogame-stub"],
    },
    {
        aliases: ["DMM.com"],
        label: "DMM.com",
        page: "DMM.com",
        categories: ["DMM.com遊戲"],
    },
    {
        aliases: [
            "Don't Nod",
            "dontnod-entertainment",
            "Dontnod Entertainment",
        ],
        label: "Don't Nod",
        page: "Don't Nod",
        categories: ["Don't Nod遊戲"],
    },
    {
        aliases: ["Dotemu"],
        label: "Dotemu",
        page: "Dotemu",
        categories: ["Dotemu遊戲"],
    },
    {
        aliases: ["Double Eleven (company)"],
        label: "Double Eleven (company)",
        page: "Double Eleven (company)",
        categories: ["Double Eleven (company)遊戲"],
    },
    {
        aliases: ["Double Fine Productions", "double-fine", "Double Fine"],
        label: "Double Fine Productions",
        page: "Double Fine Productions",
        categories: ["Double Fine Productions遊戲"],
    },
    {
        aliases: ["Dovetail Games"],
        label: "Dovetail Games",
        page: "Dovetail Games",
        categories: ["Dovetail Games遊戲"],
    },
    {
        aliases: ["Dragonfly (company)"],
        label: "Dragonfly (company)",
        page: "Dragonfly (company)",
        categories: ["Dragonfly (company)遊戲"],
    },
    {
        aliases: ["DreamCatcher Interactive"],
        label: "DreamCatcher Interactive",
        page: "DreamCatcher Interactive",
        categories: ["DreamCatcher Interactive遊戲"],
    },
    {
        aliases: ["Dreamhaven"],
        label: "Dreamhaven",
        page: "Dreamhaven",
        categories: ["Dreamhaven遊戲"],
    },
    {
        aliases: ["Drecom"],
        label: "Drecom",
        page: "Drecom",
        categories: ["Drecom遊戲"],
    },
    {
        aliases: ["DROsoft"],
        label: "DROsoft",
        page: "DROsoft",
        categories: ["DROsoft遊戲"],
    },
    {
        aliases: ["DSI Games"],
        label: "DSI Games",
        page: "DSI Games",
        categories: ["DSI Games遊戲"],
    },
    {
        aliases: ["DTP Entertainment"],
        label: "DTP Entertainment",
        page: "DTP Entertainment",
        categories: ["DTP Entertainment遊戲"],
    },
    {
        aliases: ["Duoyi Network"],
        label: "Duoyi Network",
        page: "Duoyi Network",
        categories: ["Duoyi Network遊戲"],
    },
    {
        aliases: ["EA Canada"],
        label: "EA Canada",
        page: "EA Canada",
        categories: ["EA Canada遊戲"],
        stubTags: ["ElectronicArts-stub"],
    },
    {
        aliases: ["EA Digital Illusions CE"],
        label: "EA Digital Illusions CE",
        page: "EA Digital Illusions CE",
        categories: ["EA Digital Illusions CE遊戲"],
        stubTags: ["ElectronicArts-stub"],
    },
    {
        aliases: ["Eastasiasoft"],
        label: "Eastasiasoft",
        page: "Eastasiasoft",
        categories: ["Eastasiasoft遊戲"],
    },
    {
        aliases: ["Edge Games"],
        label: "Edge Games",
        page: "Edge Games",
        categories: ["Edge Games遊戲"],
    },
    {
        aliases: ["Edmark"],
        label: "Edmark",
        page: "Edmark",
        categories: ["Edmark遊戲"],
    },
    {
        aliases: ["EGames (video game developer)"],
        label: "EGames (video game developer)",
        page: "EGames (video game developer)",
        categories: ["EGames (video game developer)遊戲"],
    },
    {
        aliases: [
            "艺夺蒙特利尔",
            "eidos-montr-al",
            "Eidos-Montréal",
            "Eidos蒙特利尔",
        ],
        label: "艺夺蒙特利尔",
        page: "艺夺蒙特利尔",
        categories: ["Eidos蒙特利爾遊戲"],
        stubTags: ["Eidos-stub"],
    },
    {
        aliases: ["Electric Dreams Software"],
        label: "Electric Dreams Software",
        page: "Electric Dreams Software",
        categories: ["Electric Dreams Software遊戲"],
    },
    {
        aliases: ["Electro Brain"],
        label: "Electro Brain",
        page: "Electro Brain",
        categories: ["Electro Brain遊戲"],
    },
    {
        aliases: ["艺电", "electronic-arts", "Electronic Arts"],
        label: "艺电",
        page: "艺电",
        categories: ["藝電遊戲"],
        stubTags: ["ElectronicArts-stub"],
    },
    {
        aliases: ["Elite Systems"],
        label: "Elite Systems",
        page: "Elite Systems",
        categories: ["Elite Systems遊戲"],
    },
    {
        aliases: ["Empire Interactive"],
        label: "Empire Interactive",
        page: "Empire Interactive",
        categories: ["Empire Interactive遊戲"],
    },
    {
        aliases: ["En Masse Entertainment"],
        label: "En Masse Entertainment",
        page: "En Masse Entertainment",
        categories: ["En Masse Entertainment遊戲"],
    },
    {
        aliases: ["Encore, Inc."],
        label: "Encore, Inc.",
        page: "Encore, Inc.",
        categories: ["Encore, Inc.遊戲"],
    },
    {
        aliases: ["艾尼克斯", "enix"],
        label: "艾尼克斯",
        page: "艾尼克斯",
        categories: ["艾尼克斯遊戲"],
    },
    {
        aliases: ["Enlight Software"],
        label: "Enlight Software",
        page: "Enlight Software",
        categories: ["Enlight Software遊戲"],
    },
    {
        aliases: ["Ensemble Studios"],
        label: "Ensemble Studios",
        page: "Ensemble Studios",
        categories: ["Ensemble Studios遊戲"],
    },
    {
        aliases: ["Entertainment Software Publishing"],
        label: "Entertainment Software Publishing",
        page: "Entertainment Software Publishing",
        categories: ["Entertainment Software Publishing遊戲"],
    },
    {
        aliases: ["Eon Digital Entertainment"],
        label: "Eon Digital Entertainment",
        page: "Eon Digital Entertainment",
        categories: ["Eon Digital Entertainment遊戲"],
    },
    {
        aliases: ["Epic Games"],
        label: "Epic Games",
        page: "Epic Games",
        categories: ["Epic Games遊戲"],
    },
    {
        aliases: ["Epic Records Japan"],
        label: "Epic Records Japan",
        page: "Epic Records Japan",
        categories: ["Epic Records Japan遊戲"],
    },
    {
        aliases: ["Europress"],
        label: "Europress",
        page: "Europress",
        categories: ["Europress遊戲"],
    },
    {
        aliases: ["Examu"],
        label: "Examu",
        page: "Examu",
        categories: ["Examu遊戲"],
    },
    {
        aliases: ["Facepunch Studios"],
        label: "Facepunch Studios",
        page: "Facepunch Studios",
        categories: ["Facepunch Studios遊戲"],
    },
    {
        aliases: ["Family Soft"],
        label: "Family Soft",
        page: "Family Soft",
        categories: ["Family Soft遊戲"],
    },
    {
        aliases: ["Faster Than Light (software publisher)"],
        label: "Faster Than Light (software publisher)",
        page: "Faster Than Light (software publisher)",
        categories: ["Faster Than Light (software publisher)遊戲"],
    },
    {
        aliases: ["Fathammer"],
        label: "Fathammer",
        page: "Fathammer",
        categories: ["Fathammer遊戲"],
    },
    {
        aliases: ["Fellow Traveller Games"],
        label: "Fellow Traveller Games",
        page: "Fellow Traveller Games",
        categories: ["Fellow Traveller Games遊戲"],
    },
    {
        aliases: ["Feral Interactive"],
        label: "Feral Interactive",
        page: "Feral Interactive",
        categories: ["Feral Interactive遊戲"],
    },
    {
        aliases: ["Fictions (company)"],
        label: "Fictions (company)",
        page: "Fictions (company)",
        categories: ["Fictions (company)遊戲"],
    },
    {
        aliases: ["Fill-in-Cafe"],
        label: "Fill-in-Cafe",
        page: "Fill-in-Cafe",
        categories: ["Fill-in-Cafe遊戲"],
    },
    {
        aliases: ["Finji"],
        label: "Finji",
        page: "Finji",
        categories: ["Finji遊戲"],
    },
    {
        aliases: ["Firaxis Games"],
        label: "Firaxis Games",
        page: "Firaxis Games",
        categories: ["Firaxis Games遊戲"],
    },
    {
        aliases: ["Firemonkeys Studios"],
        label: "Firemonkeys Studios",
        page: "Firemonkeys Studios",
        categories: ["Firemonkeys Studios遊戲"],
    },
    {
        aliases: ["Fishlabs"],
        label: "Fishlabs",
        page: "Fishlabs",
        categories: ["Fishlabs遊戲"],
    },
    {
        aliases: ["Flazm"],
        label: "Flazm",
        page: "Flazm",
        categories: ["Flazm遊戲"],
    },
    {
        aliases: ["Focus Entertainment"],
        label: "Focus Entertainment",
        page: "Focus Entertainment",
        categories: ["Focus娛樂遊戲"],
    },
    {
        aliases: ["Fox Digital Entertainment"],
        label: "Fox Digital Entertainment",
        page: "Fox Digital Entertainment",
        categories: ["Fox Digital Entertainment遊戲"],
    },
    {
        aliases: ["Fox Interactive"],
        label: "Fox Interactive",
        page: "Fox Interactive",
        categories: ["Fox Interactive遊戲"],
    },
    {
        aliases: ["FoxNext"],
        label: "FoxNext",
        page: "FoxNext",
        categories: ["FoxNext遊戲"],
    },
    {
        aliases: ["Freeverse Inc."],
        label: "Freeverse Inc.",
        page: "Freeverse Inc.",
        categories: ["Freeverse Inc.遊戲"],
    },
    {
        aliases: ["FromSoftware"],
        label: "FromSoftware",
        page: "FromSoftware",
        categories: ["FromSoftware遊戲"],
    },
    {
        aliases: ["Frontier Developments"],
        label: "Frontier Developments",
        page: "Frontier Developments",
        categories: ["Frontier Developments遊戲"],
    },
    {
        aliases: ["FTX Games"],
        label: "FTX Games",
        page: "FTX Games",
        categories: ["FTX Games遊戲"],
    },
    {
        aliases: ["Funcom"],
        label: "Funcom",
        page: "Funcom",
        categories: ["Funcom遊戲"],
    },
    {
        aliases: ["FunPlus"],
        label: "FunPlus",
        page: "FunPlus",
        categories: ["FunPlus遊戲"],
    },
    {
        aliases: ["FuRyu"],
        label: "FuRyu",
        page: "FuRyu",
        categories: ["FuRyu遊戲"],
    },
    {
        aliases: ["Gaelco"],
        label: "Gaelco",
        page: "Gaelco",
        categories: ["Gaelco遊戲"],
    },
    {
        aliases: ["Gaijin Entertainment"],
        label: "Gaijin Entertainment",
        page: "Gaijin Entertainment",
        categories: ["Gaijin Entertainment遊戲"],
    },
    {
        aliases: ["GAME FREAK"],
        label: "GAME FREAK",
        page: "GAME FREAK",
        categories: ["GAME FREAK遊戲"],
    },
    {
        aliases: ["GameHouse"],
        label: "GameHouse",
        page: "GameHouse",
        categories: ["GameHouse遊戲"],
    },
    {
        aliases: ["Gameloft"],
        label: "Gameloft",
        page: "Gameloft",
        categories: ["Gameloft遊戲"],
    },
    {
        aliases: ["Gamevil"],
        label: "Gamevil",
        page: "Gamevil",
        categories: ["Gamevil遊戲"],
    },
    {
        aliases: ["Gearbox Software"],
        label: "Gearbox Software",
        page: "Gearbox Software",
        categories: ["Gearbox Software遊戲"],
    },
    {
        aliases: [".Gears"],
        label: ".Gears",
        page: ".Gears",
        categories: [".Gears遊戲"],
    },
    {
        aliases: ["Giant Sparrow"],
        label: "Giant Sparrow",
        page: "Giant Sparrow",
        categories: ["Giant Sparrow遊戲"],
    },
    {
        aliases: ["Glu Mobile"],
        label: "Glu Mobile",
        page: "Glu Mobile",
        categories: ["Glu Mobile遊戲"],
    },
    {
        aliases: ["Good-Feel"],
        label: "Good-Feel",
        page: "Good-Feel",
        categories: ["Good-Feel遊戲"],
    },
    {
        aliases: ["Grasshopper Manufacture"],
        label: "Grasshopper Manufacture",
        page: "Grasshopper Manufacture",
        categories: ["Grasshopper Manufacture遊戲"],
    },
    {
        aliases: ["Grinding Gear Games"],
        label: "Grinding Gear Games",
        page: "Grinding Gear Games",
        categories: ["Grinding Gear Games遊戲"],
    },
    {
        aliases: ["GSC Game World"],
        label: "GSC Game World",
        page: "GSC Game World",
        categories: ["GSC Game World遊戲"],
    },
    {
        aliases: ["Guerrilla Games"],
        label: "Guerrilla Games",
        page: "Guerrilla Games",
        categories: ["Guerrilla Games遊戲"],
    },
    {
        aliases: ["GungHo Online Entertainment"],
        label: "GungHo Online Entertainment",
        page: "GungHo Online Entertainment",
        categories: ["GungHo Online Entertainment遊戲"],
    },
    {
        aliases: ["HAL研究所", "hal-laboratory", "HAL Laboratory"],
        label: "HAL研究所",
        page: "HAL研究所",
        categories: ["HAL研究所遊戲"],
    },
    {
        aliases: ["Harmonix"],
        label: "Harmonix",
        page: "Harmonix",
        categories: ["Harmonix遊戲"],
    },
    {
        aliases: ["Hasbro Interactive"],
        label: "Hasbro Interactive",
        page: "Hasbro Interactive",
        categories: ["Hasbro Interactive遊戲"],
    },
    {
        aliases: ["High Moon Studios"],
        label: "High Moon Studios",
        page: "High Moon Studios",
        categories: ["High Moon Studios遊戲"],
    },
    {
        aliases: ["id Software"],
        label: "id Software",
        page: "id Software",
        categories: ["id Software遊戲"],
        stubTags: ["idSoftware-stub"],
    },
    {
        aliases: ["Idea Factory"],
        label: "Idea Factory",
        page: "Idea Factory",
        categories: ["Idea Factory遊戲"],
    },
    {
        aliases: ["Infinity Ward"],
        label: "Infinity Ward",
        page: "Infinity Ward",
        categories: ["Infinity Ward遊戲"],
    },
    {
        aliases: ["Infogrames"],
        label: "Infogrames",
        page: "Infogrames",
        categories: ["Infogrames遊戲"],
    },
    {
        aliases: ["Insomniac Games"],
        label: "Insomniac Games",
        page: "Insomniac Games",
        categories: ["Insomniac Games遊戲"],
    },
    {
        aliases: ["Intelligent Systems"],
        label: "Intelligent Systems",
        page: "Intelligent Systems",
        categories: ["Intelligent Systems遊戲"],
    },
    {
        aliases: ["Interplay Entertainment"],
        label: "Interplay Entertainment",
        page: "Interplay Entertainment",
        categories: ["Interplay Entertainment遊戲"],
    },
    {
        aliases: ["IO Interactive"],
        label: "IO Interactive",
        page: "IO Interactive",
        categories: ["IO Interactive遊戲"],
    },
    {
        aliases: ["Irem"],
        label: "Irem",
        page: "Irem",
        categories: ["Irem遊戲"],
    },
    {
        aliases: ["Iron Galaxy"],
        label: "Iron Galaxy",
        page: "Iron Galaxy",
        categories: ["Iron Galaxy遊戲"],
    },
    {
        aliases: ["Irrational Games"],
        label: "Irrational Games",
        page: "Irrational Games",
        categories: ["Irrational Games遊戲"],
    },
    {
        aliases: ["Jagex"],
        label: "Jagex",
        page: "Jagex",
        categories: ["Jagex遊戲"],
    },
    {
        aliases: ["Jaleco"],
        label: "Jaleco",
        page: "Jaleco",
        categories: ["Jaleco遊戲"],
    },
    {
        aliases: ["JoWooD Entertainment"],
        label: "JoWooD Entertainment",
        page: "JoWooD Entertainment",
        categories: ["JoWooD Entertainment遊戲"],
    },
    {
        aliases: ["Kalypso Media"],
        label: "Kalypso Media",
        page: "Kalypso Media",
        categories: ["Kalypso Media遊戲"],
    },
    {
        aliases: ["Klei Entertainment"],
        label: "Klei Entertainment",
        page: "Klei Entertainment",
        categories: ["Klei Entertainment遊戲"],
    },
    {
        aliases: ["光荣 (企业)", "koei", "光荣"],
        label: "光荣 (企业)",
        page: "光荣 (企业)",
        categories: ["光榮遊戲"],
    },
    {
        aliases: ["光荣特库摩", "koei-tecmo", "Koei Tecmo"],
        label: "光荣特库摩",
        page: "光荣特库摩",
        categories: ["光榮特庫摩遊戲"],
    },
    {
        aliases: ["科樂美", "konami", "科乐美"],
        label: "科樂美",
        page: "科樂美",
        categories: ["科樂美遊戲"],
        stubTags: ["Konami-stub"],
    },
    {
        aliases: ["庫洛遊戲", "kuro-games", "Kuro Games", "库洛游戏"],
        label: "庫洛遊戲",
        page: "庫洛遊戲",
        categories: ["庫洛遊戲遊戲"],
    },
    {
        aliases: ["拉瑞安工作室", "larian-studios", "Larian Studios"],
        label: "拉瑞安工作室",
        page: "拉瑞安工作室",
        categories: ["拉瑞安工作室遊戲"],
    },
    {
        aliases: ["LEVEL-5", "level-5-company", "Level-5 (company)"],
        label: "LEVEL-5",
        page: "LEVEL-5",
        categories: ["LEVEL-5遊戲"],
    },
    {
        aliases: ["Lionhead Studios"],
        label: "Lionhead Studios",
        page: "Lionhead Studios",
        categories: ["Lionhead Studios遊戲"],
    },
    {
        aliases: ["卢卡斯艺术", "lucasarts"],
        label: "卢卡斯艺术",
        page: "卢卡斯艺术",
        categories: ["盧卡斯藝術遊戲"],
    },
    {
        aliases: ["MachineGames"],
        label: "MachineGames",
        page: "MachineGames",
        categories: ["MachineGames遊戲"],
    },
    {
        aliases: ["MAGES.", "mages-company", "Mages (company)"],
        label: "MAGES.",
        page: "MAGES.",
        categories: ["MAGES.遊戲"],
    },
    {
        aliases: ["Majesco Entertainment"],
        label: "Majesco Entertainment",
        page: "Majesco Entertainment",
        categories: ["Majesco Entertainment遊戲"],
    },
    {
        aliases: ["Marvelous", "marvelous-company", "Marvelous (company)"],
        label: "Marvelous",
        page: "Marvelous",
        categories: ["Marvelous遊戲"],
    },
    {
        aliases: ["MicroProse"],
        label: "MicroProse",
        page: "MicroProse",
        categories: ["MicroProse遊戲"],
    },
    {
        aliases: ["Microsoft Gaming"],
        label: "Microsoft Gaming",
        page: "Microsoft Gaming",
        categories: ["Microsoft Gaming遊戲"],
    },
    {
        aliases: ["Midway Games"],
        label: "Midway Games",
        page: "Midway Games",
        categories: ["Midway Games遊戲"],
    },
    {
        aliases: ["Milestone (公司)", "Milestone"],
        label: "Milestone",
        page: "Milestone (公司)",
        categories: ["Milestone (公司)游戏"],
    },
    {
        aliases: ["米哈游", "mihoyo"],
        label: "米哈游",
        page: "米哈游",
        categories: ["米哈遊遊戲"],
    },
    {
        aliases: ["Mojang Studios"],
        label: "Mojang Studios",
        page: "Mojang Studios",
        categories: ["Mojang Studios遊戲"],
    },
    {
        aliases: ["Monolith Productions"],
        label: "Monolith Productions",
        page: "Monolith Productions",
        categories: ["Monolith Productions遊戲"],
    },
    {
        aliases: ["Monolith Soft"],
        label: "Monolith Soft",
        page: "Monolith Soft",
        categories: ["Monolith Soft遊戲"],
    },
    {
        aliases: ["Nacon"],
        label: "Nacon",
        page: "Nacon",
        categories: ["Nacon遊戲"],
    },
    {
        aliases: ["南梦宫", "namco"],
        label: "南梦宫",
        page: "南梦宫",
        categories: ["南夢宮遊戲"],
    },
    {
        aliases: ["顽皮狗", "naughty-dog", "Naughty Dog"],
        label: "顽皮狗",
        page: "顽皮狗",
        categories: ["頑皮狗遊戲"],
    },
    {
        aliases: ["NCSoft"],
        label: "NCSoft",
        page: "NCSoft",
        categories: ["NCSoft遊戲"],
    },
    {
        aliases: ["网易游戏", "netease-games", "NetEase Games"],
        label: "网易游戏",
        page: "网易游戏",
        categories: ["網易遊戲遊戲"],
    },
    {
        aliases: ["Neversoft"],
        label: "Neversoft",
        page: "Neversoft",
        categories: ["Neversoft遊戲"],
    },
    {
        aliases: ["Nexon"],
        label: "Nexon",
        page: "Nexon",
        categories: ["Nexon遊戲"],
    },
    {
        aliases: ["任天堂", "nintendo"],
        label: "任天堂",
        page: "任天堂",
        categories: ["任天堂遊戲"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: [
            "日本一软件",
            "nippon-ichi-software",
            "Nippon Ichi Software",
        ],
        label: "日本一软件",
        page: "日本一软件",
        categories: ["日本一軟件遊戲"],
    },
    {
        aliases: [
            "黑曜石娱乐",
            "obsidian-entertainment",
            "Obsidian Entertainment",
        ],
        label: "黑曜石娱乐",
        page: "黑曜石娱乐",
        categories: ["黑曜石娛樂遊戲"],
    },
    {
        aliases: ["Outright Games"],
        label: "Outright Games",
        page: "Outright Games",
        categories: ["Outright Games遊戲"],
    },
    {
        aliases: ["Pangea Software"],
        label: "Pangea Software",
        page: "Pangea Software",
        categories: ["Pangea Software遊戲"],
    },
    {
        aliases: ["Panic Inc."],
        label: "Panic Inc.",
        page: "Panic Inc.",
        categories: ["Panic Inc.遊戲"],
    },
    {
        aliases: ["叠纸游戏", "papergames"],
        label: "叠纸游戏",
        page: "叠纸游戏",
        categories: ["疊紙遊戲遊戲"],
    },
    {
        aliases: ["Paradox Interactive"],
        label: "Paradox Interactive",
        page: "Paradox Interactive",
        categories: ["Paradox Interactive遊戲"],
    },
    {
        aliases: [
            "完美世界",
            "perfect-world-company",
            "Perfect World (company)",
        ],
        label: "完美世界",
        page: "完美世界",
        categories: ["完美世界遊戲"],
    },
    {
        aliases: ["白金工作室", "platinumgames"],
        label: "白金工作室",
        page: "白金工作室",
        categories: ["白金工作室遊戲"],
    },
    {
        aliases: ["Playdead"],
        label: "Playdead",
        page: "Playdead",
        categories: ["Playdead遊戲"],
    },
    {
        aliases: ["PlayFirst"],
        label: "PlayFirst",
        page: "PlayFirst",
        categories: ["PlayFirst遊戲"],
    },
    {
        aliases: ["Playrix"],
        label: "Playrix",
        page: "Playrix",
        categories: ["Playrix遊戲"],
    },
    {
        aliases: ["PlayStation Studios"],
        label: "PlayStation Studios",
        page: "PlayStation Studios",
        categories: ["PlayStation Studios遊戲"],
    },
    {
        aliases: ["寶開遊戲", "popcap-games", "PopCap Games", "宝开游戏"],
        label: "寶開遊戲",
        page: "寶開遊戲",
        categories: ["寶開遊戲遊戲"],
    },
    {
        aliases: ["Quantic Dream"],
        label: "Quantic Dream",
        page: "Quantic Dream",
        categories: ["Quantic Dream遊戲"],
    },
    {
        aliases: ["Rare", "rare-company", "Rare (company)"],
        label: "Rare",
        page: "Rare",
        categories: ["Rare遊戲"],
        stubTags: ["Rare-stub"],
    },
    {
        aliases: ["Raven Software"],
        label: "Raven Software",
        page: "Raven Software",
        categories: ["Raven Software遊戲"],
    },
    {
        aliases: ["Ready at Dawn"],
        label: "Ready at Dawn",
        page: "Ready at Dawn",
        categories: ["Ready at Dawn遊戲"],
    },
    {
        aliases: ["Rebellion Developments"],
        label: "Rebellion Developments",
        page: "Rebellion Developments",
        categories: ["Rebellion Developments遊戲"],
    },
    {
        aliases: [
            "赤燭遊戲",
            "red-candle-games",
            "Red Candle Games",
            "赤烛游戏",
        ],
        label: "赤燭遊戲",
        page: "赤燭遊戲",
        categories: ["赤燭遊戲遊戲"],
    },
    {
        aliases: ["Relic Entertainment"],
        label: "Relic Entertainment",
        page: "Relic Entertainment",
        categories: ["Relic Entertainment遊戲"],
    },
    {
        aliases: [
            "綠美迪娛樂",
            "remedy-entertainment",
            "Remedy Entertainment",
            "绿美迪娱乐",
        ],
        label: "綠美迪娛樂",
        page: "綠美迪娛樂",
        categories: ["綠美迪娛樂遊戲"],
    },
    {
        aliases: ["Respawn Entertainment"],
        label: "Respawn Entertainment",
        page: "Respawn Entertainment",
        categories: ["Respawn Entertainment遊戲"],
    },
    {
        aliases: ["拳头游戏", "riot-games", "Riot Games"],
        label: "拳头游戏",
        page: "拳头游戏",
        categories: ["拳頭遊戲遊戲"],
    },
    {
        aliases: ["Riot Sydney"],
        label: "Riot Sydney",
        page: "Riot Sydney",
        categories: ["Riot Sydney遊戲"],
    },
    {
        aliases: ["Rockstar Games"],
        label: "Rockstar Games",
        page: "Rockstar Games",
        categories: ["Rockstar Games遊戲"],
        stubTags: ["RockstarGames-stub"],
    },
    {
        aliases: ["Rockstar North"],
        label: "Rockstar North",
        page: "Rockstar North",
        categories: ["Rockstar North遊戲"],
    },
    {
        aliases: ["Rocksteady Studios"],
        label: "Rocksteady Studios",
        page: "Rocksteady Studios",
        categories: ["Rocksteady Studios遊戲"],
    },
    {
        aliases: ["Rovio Entertainment"],
        label: "Rovio Entertainment",
        page: "Rovio Entertainment",
        categories: ["Rovio Entertainment遊戲"],
    },
    {
        aliases: ["Runic Games"],
        label: "Runic Games",
        page: "Runic Games",
        categories: ["Runic Games遊戲"],
    },
    {
        aliases: ["Saber Interactive"],
        label: "Saber Interactive",
        page: "Saber Interactive",
        categories: ["Saber Interactive遊戲"],
    },
    {
        aliases: ["世嘉", "sega"],
        label: "世嘉",
        page: "世嘉",
        categories: ["世嘉遊戲"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["SNK"],
        label: "SNK",
        page: "SNK",
        categories: ["SNK遊戲"],
    },
    {
        aliases: [
            "索尼互動娛樂",
            "sony-interactive-entertainment",
            "Sony Interactive Entertainment",
        ],
        label: "索尼互動娛樂",
        page: "索尼互動娛樂",
        categories: ["索尼互動娛樂遊戲"],
        stubTags: ["Sony-videogame-stub"],
    },
    {
        aliases: ["Spike Chunsoft"],
        label: "Spike Chunsoft",
        page: "Spike Chunsoft",
        categories: ["Spike Chunsoft遊戲"],
    },
    {
        aliases: ["史克威爾", "square", "史克威尔"],
        label: "史克威爾",
        page: "史克威爾",
        categories: ["史克威爾遊戲"],
    },
    {
        aliases: ["史克威尔艾尼克斯", "square-enix", "Square Enix"],
        label: "史克威尔艾尼克斯",
        page: "史克威尔艾尼克斯",
        categories: ["史克威爾艾尼克斯遊戲"],
        stubTags: ["SquareEnix-stub"],
    },
    {
        aliases: ["Studio MDHR"],
        label: "Studio MDHR",
        page: "Studio MDHR",
        categories: ["Studio MDHR遊戲"],
    },
    {
        aliases: ["Sucker Punch Productions"],
        label: "Sucker Punch Productions",
        page: "Sucker Punch Productions",
        categories: ["Sucker Punch Productions遊戲"],
    },
    {
        aliases: ["Supergiant Games"],
        label: "Supergiant Games",
        page: "Supergiant Games",
        categories: ["Supergiant Games遊戲"],
    },
    {
        aliases: ["Supermassive Games"],
        label: "Supermassive Games",
        page: "Supermassive Games",
        categories: ["Supermassive Games遊戲"],
    },
    {
        aliases: ["太東", "taito", "太东"],
        label: "太東",
        page: "太東",
        categories: ["太東遊戲"],
        stubTags: ["Taito-videogame-stub"],
    },
    {
        aliases: ["Take-Two Interactive"],
        label: "Take-Two Interactive",
        page: "Take-Two Interactive",
        categories: ["Take-Two Interactive遊戲"],
        stubTags: ["TakeTwo-stub"],
    },
    {
        aliases: ["Team17"],
        label: "Team17",
        page: "Team17",
        categories: ["Team17遊戲"],
    },
    {
        aliases: ["Techland"],
        label: "Techland",
        page: "Techland",
        categories: ["Techland遊戲"],
    },
    {
        aliases: ["騰訊遊戲", "tencent-games", "Tencent Games", "腾讯游戏"],
        label: "騰訊遊戲",
        page: "騰訊遊戲",
        categories: ["騰訊遊戲遊戲"],
    },
    {
        aliases: ["The 3DO Company"],
        label: "The 3DO Company",
        page: "The 3DO Company",
        categories: ["The 3DO Company遊戲"],
    },
    {
        aliases: ["The Adventure Company"],
        label: "The Adventure Company",
        page: "The Adventure Company",
        categories: ["The Adventure Company遊戲"],
    },
    {
        aliases: ["The Arcade (company)"],
        label: "The Arcade (company)",
        page: "The Arcade (company)",
        categories: ["The Arcade (company)遊戲"],
    },
    {
        aliases: ["The Astronauts (company)"],
        label: "The Astronauts (company)",
        page: "The Astronauts (company)",
        categories: ["The Astronauts (company)遊戲"],
    },
    {
        aliases: ["The Behemoth"],
        label: "The Behemoth",
        page: "The Behemoth",
        categories: ["The Behemoth遊戲"],
    },
    {
        aliases: ["The Bitmap Brothers"],
        label: "The Bitmap Brothers",
        page: "The Bitmap Brothers",
        categories: ["The Bitmap Brothers遊戲"],
    },
    {
        aliases: ["THQ"],
        label: "THQ",
        page: "THQ",
        categories: ["THQ遊戲"],
        stubTags: ["THQ-stub"],
    },
    {
        aliases: ["THQ Nordic"],
        label: "THQ Nordic",
        page: "THQ Nordic",
        categories: ["THQ Nordic遊戲"],
    },
    {
        aliases: ["東映", "toei-company", "Toei Company", "东映"],
        label: "東映",
        page: "東映",
        categories: ["東映遊戲"],
    },
    {
        aliases: ["東寶", "toho", "东宝"],
        label: "東寶",
        page: "東寶",
        categories: ["東寶遊戲"],
    },
    {
        aliases: ["德間書店", "tokuma-shoten", "Tokuma Shoten", "德间书店"],
        label: "德間書店",
        page: "德間書店",
        categories: ["德間書店遊戲"],
    },
    {
        aliases: ["Treyarch"],
        label: "Treyarch",
        page: "Treyarch",
        categories: ["Treyarch遊戲"],
    },
    {
        aliases: ["tri-Ace"],
        label: "tri-Ace",
        page: "tri-Ace",
        categories: ["tri-Ace遊戲"],
    },
    {
        aliases: ["TYPE-MOON"],
        label: "TYPE-MOON",
        page: "TYPE-MOON",
        categories: ["TYPE-MOON遊戲"],
    },
    {
        aliases: ["育碧", "ubisoft"],
        label: "育碧",
        page: "育碧",
        categories: ["育碧遊戲"],
        stubTags: ["Ubisoft-stub"],
    },
    {
        aliases: ["Valve公司", "valve-corporation", "Valve Corporation"],
        label: "Valve公司",
        page: "Valve公司",
        categories: ["Valve公司遊戲"],
    },
    {
        aliases: ["Vivendi Games"],
        label: "Vivendi Games",
        page: "Vivendi Games",
        categories: ["Vivendi Games遊戲"],
        stubTags: ["VivendiGames-stub"],
    },
    {
        aliases: ["华纳兄弟游戏", "warner-bros-games", "Warner Bros. Games"],
        label: "华纳兄弟游戏",
        page: "华纳兄弟游戏",
        categories: ["華納兄弟互動娛樂遊戲"],
    },
    {
        aliases: ["Xbox Game Studios"],
        label: "Xbox Game Studios",
        page: "Xbox Game Studios",
        categories: ["Xbox Game Studios遊戲"],
    },
    {
        aliases: ["Yacht Club Games"],
        label: "Yacht Club Games",
        page: "Yacht Club Games",
        categories: ["Yacht Club Games遊戲"],
    },
    {
        aliases: ["ZeniMax Media"],
        label: "ZeniMax Media",
        page: "ZeniMax Media",
        categories: ["ZeniMax Media遊戲"],
        stubTags: ["Zenimax-stub"],
    },
    {
        aliases: ["Zynga"],
        label: "Zynga",
        page: "Zynga",
        categories: ["Zynga遊戲"],
    },
] satisfies TerminologyDefinition[];
