import type { TerminologyDefinition } from "./schema.ts";

// eslint-disable-next-line max-len
// QA: Keep groups and entries in visual display order; do not auto-sort.
// prettier-ignore
export default [
    {
        aliases: [
            "4X",
        ],
        label: "4X",
        page: "4X",
        categories: ["4X电子游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            /[動动]作/,
            "action",
        ],
        label: "动作",
        page: "动作游戏",
        categories: ["动作游戏"],
        stubTags: ["action-videogame-stub"],
    },
    {
        aliases: [
            /[動动]作冒[險险]/,
            "action-adventure",
        ],
        label: "动作冒险",
        page: "动作冒险游戏",
        categories: ["动作冒险游戏"],
        stubTags: ["action-adventure-videogame-stub"],
    },
    {
        aliases: [
            /[動动]作角色扮演/,
            "action role-playing",
            "action RPG",
            "ARPG",
        ],
        label: "動作角色扮演",
        page: "動作角色扮演遊戲",
        categories: ["動作角色扮演遊戲"],
        stubTags: ["action-rpg-videogame-stub"],
    },
    {
        aliases: [
            /冒[險险]/,
            "adventure",
        ],
        label: "冒险",
        page: "冒险游戏",
        categories: ["冒险游戏"],
        stubTags: ["adventure-videogame-stub"],
    },
    {
        aliases: [
            /炮[術术]/,
            "artillery",
        ],
        label: "炮术",
        page: "炮术游戏",
        categories: ["炮术游戏"],
        stubTags: ["artillery-videogame-stub"],
    },
    {
        aliases: [
            "自走棋",
            "auto battler",
        ],
        label: "自走棋",
        page: "自走棋",
        categories: ["自走棋游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            /大逃[殺杀]/,
            "battle royale",
        ],
        label: "大逃杀",
        page: "大逃杀游戏",
        categories: ["大逃杀游戏"],
        stubTags: ["action-videogame-stub"],
    },
    {
        aliases: [
            /清版[動动]作/,
            "beat 'em up",
            "brawler",
        ],
        label: "清版动作",
        page: "清版动作游戏",
        categories: ["清版动作游戏"],
        stubTags: ["Beatemup-videogame-stub"],
    },
    {
        aliases: [
            /商[業业]模[擬拟]/,
            "business sim",
            "business simulation",
        ],
        label: "商业模拟",
        page: "商业模拟游戏",
        categories: ["商业模拟游戏"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            /[彈弹]幕射[擊击]/,
            "bullet hell",
        ],
        label: "彈幕射擊",
        page: "彈幕射擊遊戲",
        categories: ["捲軸射擊遊戲"],
        stubTags: ["shooter-videogame-stub"],
    },
    {
        aliases: [
            /[類类]吸血鬼[倖幸]存者/,
            "bullet heaven",
            "vampire Survivors-like",
            "vampire Survivors–like",
        ],
        label: "類吸血鬼倖存者",
        page: "類吸血鬼倖存者遊戲",
        categories: ["類吸血鬼倖存者遊戲"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "城市建造",
            "city builder",
            "city-building",
        ],
        label: "城市建造",
        page: "城市建造游戏",
        categories: ["城市建造游戏"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            /建造[與与][經经][營营]模[擬拟]/,
            "construction and management simulation",
            "cms",
        ],
        label: "建造與經營模擬",
        page: "建造與經營模擬遊戲",
        categories: ["建造與經營模擬遊戲"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            /[戀恋][愛爱]模[擬拟]/,
            "dating sim",
        ],
        label: "戀愛模擬",
        page: "戀愛模擬遊戲",
        categories: ["戀愛模擬遊戲"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            /集[換换]式卡片/,
            "digital collectible card",
            "dccg",
        ],
        label: "电子集换式卡片",
        page: "电子集换式卡片游戏",
        categories: ["电子集换式卡片游戏"],
        stubTags: ["card-videogame-stub"],
    },
    {
        aliases: [
            /牌[組组][構构][築筑]/,
            "deck building",
        ],
        label: "牌组构筑",
        page: "牌组构筑游戏",
        categories: ["牌组构筑游戏"],
        stubTags: ["card-videogame-stub"],
    },
    {
        aliases: [
            /[數数]字桌上游[戲戏]/,
            /[數数]字桌上/,
            "digital tabletop",
        ],
        label: "桌上",
        page: "数字桌上游戏",
        categories: ["数字桌上游戏"],
        stubTags: ["Board-videogame-stub"],
    },
    {
        aliases: [
            /迷[宮宫]探索/,
            "dungeon crawl",
        ],
        label: "迷宫探索",
        page: "迷宫探索",
        categories: ["迷宫探索游戏"],
        stubTags: ["rpg-videogame-stub"],
    },
    {
        aliases: [
            "教育",
            "educational",
        ],
        label: "教育",
        page: "教育游戏",
        categories: ["教育游戏"],
        stubTags: ["Edu-videogame-stub"],
    },
    {
        aliases: [
            /[無无][盡尽]跑酷/,
            "endless runner",
            "runner",
        ],
        label: "無盡跑酷",
        page: "無盡跑酷遊戲",
        categories: ["無盡跑酷遊戲"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "日本成人",
            "eroge",
            "japanese erotic",
        ],
        label: "日本成人",
        page: "日本成人遊戲",
        categories: ["日本成人遊戲"],
        stubTags: ["Eroge-videogame-stub"],
    },
    {
        aliases: [
            /[農农][場场]模[擬拟]/,
            "farm life sim",
            "farm life simulation",
            "farming",
        ],
        label: "農場模擬",
        page: "農場模擬遊戲",
        categories: ["農場模擬遊戲"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            /格[鬥斗]/,
            "fighting",
        ],
        label: "格鬥",
        page: "格鬥遊戲",
        categories: ["格鬥遊戲"],
        stubTags: ["fighting-videogame-stub"],
    },
    {
        aliases: [
            "健身",
            "fitness",
        ],
        label: "健身",
        page: "健身遊戲",
        categories: ["健身遊戲"],
        stubTags: ["sports-videogame-stub"],
    },
    {
        aliases: [
            /第一人[稱称]射[擊击]/,
            "first-person shooter",
            "fps",
        ],
        label: "第一人称射击",
        page: "第一人称射击游戏",
        categories: ["第一人称射击游戏"],
        stubTags: ["fps-videogame-stub"],
    },
    {
        aliases: [
            /上帝模[擬拟]/,
            "god",
        ],
        label: "上帝模拟",
        page: "上帝模拟游戏",
        categories: ["上帝模拟游戏"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            /政府模[擬拟]/,
            "government sim",
            "government simulation",
        ],
        label: "政府模拟",
        page: "政府模拟游戏",
        categories: ["政府模拟游戏"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            /大[戰战]略/,
            "grand strategy",
        ],
        label: "大战略",
        page: "大战略游戏",
        categories: ["大战略游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            /[圖图]形冒[險险]/,
            "graphic adventure",
        ],
        label: "图形冒险",
        page: "图形冒险游戏",
        categories: ["图形冒险游戏"],
        stubTags: ["adventure-videogame-stub"],
    },
    {
        aliases: [
            /砍[殺杀]/,
            "hack and slash",
        ],
        label: "砍殺",
        page: "砍殺遊戲",
        categories: ["砍殺遊戲"],
        stubTags: ["action-videogame-stub"],
    },
    {
        aliases: [
            /英雄射[擊击]/,
            "hero shooter",
        ],
        label: "英雄射击",
        page: "英雄射击游戏",
        categories: ["英雄射击游戏"],
        stubTags: ["shooter-videogame-stub"],
    },
    {
        aliases: [
            "恐怖",
            "horror",
        ],
        label: "恐怖",
        page: "恐怖游戏",
        categories: ["恐怖游戏"],
        stubTags: ["horror-videogame-stub"],
    },
    {
        aliases: [
            /互[動动]式[電电]影/,
            "full motion video",
            "interactive film",
        ],
        label: "互动式电影",
        page: "互动式电影",
        categories: ["互动式电影"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            /生活模[擬拟]/,
            "life sim",
            "life simulation",
        ],
        label: "生活模拟",
        page: "生活模拟游戏",
        categories: ["生活模拟游戏"],
        stubTags: ["Life-simulation-videogame-stub"],
    },
    {
        aliases: [
            /[類类][銀银]河[戰战]士[惡恶]魔城/,
            "metroidvania",
        ],
        label: "類銀河戰士惡魔城",
        page: "類銀河戰士惡魔城遊戲",
        categories: ["類銀河戰士惡魔城遊戲"],
        stubTags: ["action-adventure-videogame-stub"],
    },
    {
        aliases: [
            /大型多人在[線线]/,
            "massively multiplayer online",
            "mmo",
        ],
        label: "大型多人在线",
        page: "大型多人在线游戏",
        categories: ["大型多人在线游戏"],
        stubTags: ["Online-videogame-stub"],
    },
    {
        aliases: [
            /大型多人在[線线]角色扮演/,
            "massively multiplayer online role-playing",
            "massively multiplayer online RPG",
            "mmorpg",
        ],
        label: "大型多人在线角色扮演",
        page: "大型多人在线角色扮演游戏",
        categories: ["大型多人在线角色扮演游戏"],
        stubTags: ["mmorpg-videogame-stub"],
    },
    {
        aliases: [
            /多人在[線线][戰战][鬥斗][競竞]技[場场]/,
            "multiplayer online battle arena",
            "moba",
        ],
        label: "多人在线战斗竞技场",
        page: "多人在线战斗竞技场",
        categories: ["多人在线战斗竞技场"],
        stubTags: ["Online-videogame-stub"],
    },
    {
        aliases: [
            /怪物[馴驯][養养]/,
            "monster tamer",
            "monster-taming",
        ],
        label: "怪物驯养",
        page: "怪物驯养游戏",
        categories: ["怪物驯养游戏"],
        stubTags: ["rpg-videogame-stub"],
    },
    {
        aliases: [
            "multi-user dungeon",
            "MUD",
        ],
        label: "MUD",
        page: "MUD",
        categories: ["MUD游戏"],
        stubTags: ["rpg-videogame-stub"],
    },
    {
        aliases: [
            /音[樂乐]/,
            "music",
        ],
        label: "音樂",
        page: "音樂遊戲",
        categories: ["音樂遊戲"],
        stubTags: ["music-videogame-stub"],
    },
    {
        aliases: [
            /[敘叙]事冒[險险]/,
            "narrative adventure",
        ],
        label: "叙事冒险",
        page: "叙事冒险游戏",
        categories: ["叙事冒险游戏"],
        stubTags: ["adventure-videogame-stub"],
    },
    {
        aliases: [
            "乙女",
            "otome",
        ],
        label: "乙女",
        page: "乙女游戏",
        categories: ["乙女游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            /聚[會会]/,
            "party",
        ],
        label: "聚会",
        page: "聚会游戏",
        categories: ["聚会游戏"],
        stubTags: ["Party-videogame-stub"],
    },
    {
        aliases: [
            /[點点][擊击]式冒[險险]/,
            "point-and-click adventure",
            "pca",
        ],
        label: "点击式冒险",
        page: "点击式冒险游戏",
        categories: ["点击式冒险游戏"],
        stubTags: ["adventure-videogame-stub"],
    },
    {
        aliases: [
            /平[臺台]/,
            "platform",
            "platformer",
        ],
        label: "平台",
        page: "平台游戏",
        categories: ["平台游戏"],
        stubTags: ["platform-videogame-stub"],
    },
    {
        aliases: [
            "益智",
            "puzzle",
        ],
        label: "益智",
        page: "益智类电子游戏",
        categories: ["益智类电子游戏"],
        stubTags: ["puzzle-videogame-stub"],
    },
    {
        aliases: [
            /益智平[臺台]/,
            "puzzle-platform",
        ],
        label: "益智—平台",
        page: "益智平台游戏",
        categories: ["益智类电子游戏", "平台游戏"],
        stubTags: ["platform-videogame-stub", "puzzle-videogame-stub"],
    },
    {
        aliases: [
            /[競竞]速/,
            "racing",
        ],
        label: "竞速",
        page: "竞速游戏",
        categories: ["竞速游戏"],
        stubTags: ["racing-videogame-stub"],
    },
    {
        aliases: [
            /[節节]奏/,
            "rhythm",
        ],
        label: "节奏",
        page: "节奏游戏",
        categories: ["节奏游戏"],
        stubTags: ["music-videogame-stub"],
    },
    {
        aliases: [
            "Roguelike",
            "roguelite",
        ],
        label: "roguelike",
        page: "Roguelike",
        categories: ["Roguelike游戏"],
        stubTags: ["roguelike-videogame-stub"],
    },
    {
        aliases: [
            /[電电]子角色扮演/,
            "角色扮演",
            "role-playing",
            "RPG",
        ],
        label: "角色扮演",
        page: "電子角色扮演遊戲",
        categories: ["電子角色扮演遊戲"],
        stubTags: ["rpg-videogame-stub"],
    },
    {
        aliases: [
            /即[時时][戰战]略/,
            "real-time strategy",
            "rts",
        ],
        label: "即时战略",
        page: "即时战略游戏",
        categories: ["即时战略游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            /即[時时][戰战][術术]/,
            "real-time tactics",
            "rtt",
        ],
        label: "即时战术",
        page: "即时战术游戏",
        categories: ["即时战术游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            /奔跑射[擊击]/,
            "run and gun",
        ],
        label: "奔跑射擊",
        page: "奔跑射擊遊戲",
        categories: ["奔跑射擊遊戲"],
        stubTags: ["shooter-videogame-stub"],
    },
    {
        aliases: [
            "沙盒",
            "sandbox",
        ],
        label: "沙盒",
        page: "沙盒游戏",
        categories: ["沙盒游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            /清版射[擊击]/,
            "shoot 'em up",
        ],
        label: "清版射击",
        page: "清版射击游戏",
        categories: ["清版射击游戏"],
        stubTags: ["shmup-videogame-stub"],
    },
    {
        aliases: [
            /[捲卷][軸轴]射[擊击]/,
            "scrolling shooter",
        ],
        label: "捲軸射擊",
        page: "捲軸射擊遊戲",
        categories: ["捲軸射擊遊戲"],
        stubTags: ["shooter-videogame-stub"],
    },
    {
        aliases: [
            /射[擊击]/,
            "shooter",
        ],
        label: "射击",
        page: "射击游戏",
        categories: ["射击游戏"],
        stubTags: ["shooter-videogame-stub"],
    },
    {
        aliases: [
            /模[擬拟]/,
            "simulation",
        ],
        label: "模拟",
        page: "模拟游戏",
        categories: ["模拟游戏"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            "赛车",
            "sim racing",
            "racing sim",
            "racing simulation",
        ],
        label: "Sim racing",
        page: "赛车游戏",
        categories: ["競速遊戲"],
        stubTags: ["racing-videogame-stub"],
    },
    {
        aliases: [
            /社交模[擬拟]/,
            "social sim",
            "social simulation",
        ],
        label: "社交模拟",
        page: "社交模拟游戏",
        categories: ["社交模拟游戏"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            "魂系",
            "souls-like",
            "soulslike",
        ],
        label: "魂系",
        page: "魂系",
        categories: ["魂系游戏"],
        stubTags: ["action-videogame-stub"],
    },
    {
        aliases: [
            /[體体]育/,
            "sports",
        ],
        label: "体育",
        page: "體育電子遊戲",
        categories: ["體育電子遊戲"],
        stubTags: ["sports-videogame-stub"],
    },
    {
        aliases: [
            /[隱隐]蔽[類类]/,
            "stealth",
        ],
        label: "隐蔽类",
        page: "隐蔽类游戏",
        categories: ["隐蔽类游戏"],
        stubTags: ["adventure-videogame-stub"],
    },
    {
        aliases: [
            "策略",
            "strategy",
        ],
        label: "策略",
        page: "策略游戏",
        categories: ["策略游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            "生存",
            "survival",
        ],
        label: "生存",
        page: "生存游戏",
        categories: ["生存游戏"],
        stubTags: ["adventure-videogame-stub"],
    },
    {
        aliases: [
            "恐怖生存",
            "survival horror",
        ],
        label: "恐怖生存",
        page: "恐怖生存游戏",
        categories: ["恐怖生存游戏"],
        stubTags: ["horror-videogame-stub"],
    },
    {
        aliases: [
            /[戰战]略角色扮演/,
            "strategy RPG",
            "tactical role-playing",
            "tactical RPG",
            "SRPG",
        ],
        label: "戰略角色扮演",
        page: "戰略角色扮演遊戲",
        categories: ["戰略角色扮演遊戲"],
        stubTags: ["tactical-rpg-videogame-stub"],
    },
    {
        aliases: [
            /[戰战][術术]射[擊击]/,
            "tactical shooter",
        ],
        label: "战术射击",
        page: "战术射击游戏",
        categories: ["战术射击游戏"],
        stubTags: ["shooter-videogame-stub"],
    },
    {
        aliases: [
            "回合制策略",
            "turn-based strategy",
            "tbs",
        ],
        label: "回合制策略",
        page: "回合制策略游戏",
        categories: ["回合制策略游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            /回合制[戰战][術术]/,
            "turn-based tactics",
            "tbt",
        ],
        label: "回合制战术",
        page: "回合制战术游戏",
        categories: ["回合制战术游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            /消除[類类]/,
            "match-three",
            "tile matching",
            "tile-matching",
        ],
        label: "消除类",
        page: "消除类游戏",
        categories: ["消除类游戏"],
        stubTags: ["puzzle-videogame-stub"],
    },
    {
        aliases: [
            "塔防",
            "tower defense",
        ],
        label: "塔防",
        page: "塔防",
        categories: ["塔防游戏"],
        stubTags: ["strategy-videogame-stub"],
    },
    {
        aliases: [
            /第三人[稱称]射[擊击]/,
            "third-person shooter",
            "tps",
        ],
        label: "第三人称射击",
        page: "第三人称射击游戏",
        categories: ["第三人称射击游戏"],
        stubTags: ["tps-videogame-stub"],
    },
    {
        aliases: [
            /交通工具模[擬拟]/,
            "vehicle sim",
            "vehicle simulation",
        ],
        label: "交通工具模拟",
        page: "交通工具模拟游戏",
        categories: ["交通工具模拟游戏"],
        stubTags: ["Vehicle-simulation-videogame-stub"],
    },
    {
        aliases: [
            /交通工具[戰战][鬥斗]/,
            "vehicular combat",
        ],
        label: "交通工具戰鬥",
        page: "交通工具戰鬥遊戲",
        categories: ["交通工具戰鬥遊戲"],
        stubTags: ["Vehicle-simulation-videogame-stub"],
    },
    {
        aliases: [
            /[電电]子[寵宠]物/,
            "pet-raising simulation",
            "virtual pet",
        ],
        label: "电子宠物",
        page: "电子宠物",
        categories: ["电子宠物游戏"],
        stubTags: ["Life-simulation-videogame-stub"],
    },
    {
        aliases: [
            /[視视][覺觉]小[說说]/,
            "visual novel",
        ],
        label: "视觉小说",
        page: "视觉小说",
        categories: ["视觉小说"],
        stubTags: ["Visual-novel-stub"],
    },
    {
        aliases: [
            /步行模[擬拟]器/,
            "walking sim",
            "walking simulator",
        ],
        label: "步行模擬器",
        page: "步行模擬器",
        categories: ["步行模擬器"],
        stubTags: ["simulation-videogame-stub"],
    },
    {
        aliases: [
            /[電电][腦脑][戰战][爭争]/,
            "computer wargame",
            "wargame",
        ],
        label: "电脑战争",
        page: "电脑战争游戏",
        categories: ["电脑战争游戏"],
        stubTags: ["strategy-videogame-stub"],
    }
] satisfies TerminologyDefinition[];
