import type { TerminologyDefinition } from "./schema.ts";
export default [
    {
        aliases: ["3DO"],
        label: "3DO",
        page: "3DO",
        categories: ["3DO游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "任天堂3DS",
            "3ds",
            "Nintendo 3DS",
            "3DS Virtual Console",
            "iQue 3DS",
        ],
        label: "任天堂3DS",
        page: "任天堂3DS",
        categories: ["任天堂3DS游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["64DD"],
        label: "64DD",
        page: "64DD",
        categories: ["64DD游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Arcadia 2001", "a2001"],
        label: "Arcadia 2001",
        page: "Arcadia 2001",
        categories: ["Arcadia 2001游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Xerox Alto", "alto"],
        label: "Xerox Alto",
        page: "Xerox Alto",
        categories: ["Xerox Alto游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Amiga", "ami"],
        label: "Amiga",
        page: "Amiga",
        categories: ["Amiga游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Amiga CD32", "ami32"],
        label: "Amiga CD32",
        page: "Amiga CD32",
        categories: ["Amiga CD32游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["AmigaOS", "amios", "AmigaOS 4", "AROS", "MorphOS"],
        label: "AmigaOS",
        page: "AmigaOS",
        categories: ["AmigaOS游戏"],
        stubTags: ["Mobile-videogame-stub"],
    },
    {
        aliases: ["Apple I", "appi"],
        label: "Apple I",
        page: "Apple I",
        categories: ["Apple I游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Apple II", "appii"],
        label: "Apple II",
        page: "Apple II",
        categories: ["Apple II游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Mattel Aquarius", "aqua"],
        label: "Mattel Aquarius",
        page: "Mattel Aquarius",
        categories: ["Mattel Aquarius游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Acorn Archimedes", "arc"],
        label: "Acorn Archimedes",
        page: "Acorn Archimedes",
        categories: ["Acorn Archimedes游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["街机游戏", "arcade", "Arcade video game", "Arcade game"],
        label: "街机游戏",
        page: "街机游戏",
        categories: ["街机游戏"],
        stubTags: ["Arcade-stub"],
    },
    {
        aliases: ["Atari 8位元家族", "atr", "Atari 8-bit computers"],
        label: "Atari 8位元家族",
        page: "Atari 8位元家族",
        categories: ["Atari 8位元家族游戏"],
        stubTags: ["Atari-console-stub"],
    },
    {
        aliases: ["雅達利2600", "atr26", "Atari 2600", "Atari 2800"],
        label: "雅達利2600",
        page: "雅達利2600",
        categories: ["雅達利2600遊戲"],
        stubTags: ["Atari-console-stub"],
    },
    {
        aliases: ["雅達利5200", "atr52", "Atari 5200"],
        label: "雅達利5200",
        page: "雅達利5200",
        categories: ["雅達利5200遊戲"],
        stubTags: ["Atari-console-stub"],
    },
    {
        aliases: ["雅达利7800", "atr78", "Atari 7800"],
        label: "雅达利7800",
        page: "雅达利7800",
        categories: ["雅达利7800游戏"],
        stubTags: ["Atari-console-stub"],
    },
    {
        aliases: ["Atari ST", "atrst", "Atari Falcon"],
        label: "Atari ST",
        page: "Atari ST",
        categories: ["Atari ST游戏"],
        stubTags: ["AtariST-videogame-stub"],
    },
    {
        aliases: ["雅達利VCS", "atrvcs", "Atari VCS"],
        label: "雅達利VCS",
        page: "雅達利VCS",
        categories: ["雅達利VCS遊戲"],
        stubTags: ["Atari-console-stub"],
    },
    {
        aliases: ["Bada"],
        label: "Bada",
        page: "Bada",
        categories: ["Bada游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["条码扫描器游戏", "bar", "barcode scanner games"],
        label: "条码扫描器游戏",
        page: "条码扫描器游戏",
        categories: ["条码扫描器游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "BlackBerry 10",
            "bb10",
            "BlackBerry Tablet OS",
            "BlackBerry OS",
        ],
        label: "BlackBerry 10",
        page: "BlackBerry 10",
        categories: ["BlackBerry游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["BBC Micro", "bbc", "Acorn Electron", "BBC Master"],
        label: "BBC Micro",
        page: "BBC Micro",
        categories: ["BBC Micro游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["BBS门游戏", "bbs", "BBS door"],
        label: "BBS门游戏",
        page: "BBS门游戏",
        categories: ["BBS门游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["BeOS", "Haiku"],
        label: "BeOS",
        page: "BeOS",
        categories: ["BeOS游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "BSD",
            "Berkeley Software Distribution",
            "OpenBSD",
            "FreeBSD",
        ],
        label: "BSD",
        page: "BSD",
        categories: ["BSD游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Commodore 16", "c16", "Commodore Plus/4"],
        label: "Commodore 16",
        page: "Commodore 16",
        categories: ["Commodore 16游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Commodore 64", "c64"],
        label: "Commodore 64",
        page: "Commodore 64",
        categories: ["Commodore 64游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Commodore 128", "c128"],
        label: "Commodore 128",
        page: "Commodore 128",
        categories: ["Commodore 128游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["CD-i", "cdi", "Philips CD-i"],
        label: "CD-i",
        page: "CD-i",
        categories: ["CD-i游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["康懋達CDTV", "cdtv", "Commodore CDTV"],
        label: "康懋達CDTV",
        page: "康懋達CDTV",
        categories: ["康懋達CDTV遊戲"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["ColecoVision", "clv", "Coleco Adam"],
        label: "ColecoVision",
        page: "ColecoVision",
        categories: ["ColecoVision游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Amstrad CPC", "cpc"],
        label: "Amstrad CPC",
        page: "Amstrad CPC",
        categories: ["Amstrad CPC游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["CP/M"],
        label: "CP/M",
        page: "CP/M",
        categories: ["CP/M游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Cassette Vision", "cv"],
        label: "Cassette Vision",
        page: "Cassette Vision",
        categories: ["Cassette Vision游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Dreamcast", "dc"],
        label: "Dreamcast",
        page: "Dreamcast",
        categories: ["Dreamcast游戏"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["DEC Professional", "dec"],
        label: "DEC Professional",
        page: "DEC Professional",
        categories: ["DEC Professional游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["DOS", "MS-DOS"],
        label: "DOS",
        page: "DOS",
        categories: ["DOS游戏"],
        stubTags: ["MSDOS-videogame-stub"],
    },
    {
        aliases: ["Dragon 32/64", "dra"],
        label: "Dragon 32/64",
        page: "Dragon 32/64",
        categories: ["Dragon 32/64游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Android", "droid"],
        label: "Android",
        page: "Android",
        categories: ["Android游戏"],
        stubTags: ["Mobile-videogame-stub"],
    },
    {
        aliases: ["任天堂DS", "ds", "Nintendo DS", "DSiWare", "iQue DS"],
        label: "任天堂DS",
        page: "任天堂DS",
        categories: ["任天堂DS游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["TurboDuo", "duo", "PC Engine Duo"],
        label: "TurboDuo",
        page: "TurboDuo",
        categories: ["TurboDuo游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["EPOC16"],
        label: "EPOC16",
        page: "EPOC16",
        categories: ["EPOC16游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "磁碟機",
            "fds",
            "Famicom Disk System",
            "Family Computer Disk System",
        ],
        label: "磁碟機",
        page: "磁碟機",
        categories: ["Famicom Disk System游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["FM-7", "fm7"],
        label: "FM-7",
        page: "FM-7",
        categories: ["FM-7游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["FM Towns", "fmt"],
        label: "FM Towns",
        page: "FM Towns",
        categories: ["FM Towns游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Fire OS", "fos"],
        label: "Fire OS",
        page: "Fire OS",
        categories: ["Fire OS游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Game & Watch", "g-w", "G&W"],
        label: "Game & Watch",
        page: "Game & Watch",
        categories: ["Game & Watch游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Game Boy", "gb"],
        label: "Game Boy",
        page: "Game Boy",
        categories: ["Game Boy游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["Game Boy Advance", "gba", "iQue GBA"],
        label: "Game Boy Advance",
        page: "Game Boy Advance",
        categories: ["Game Boy Advance游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["Game Boy Color", "gbc"],
        label: "Game Boy Color",
        page: "Game Boy Color",
        categories: ["Game Boy Color游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["任天堂GameCube", "gcn", "GameCube", "Nintendo GameCube"],
        label: "任天堂GameCube",
        page: "任天堂GameCube",
        categories: ["任天堂GameCube游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["Game.com", "gcom"],
        label: "Game.com",
        page: "Game.com",
        categories: ["Game.com游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Google Daydream", "gd"],
        label: "Google Daydream",
        page: "Google Daydream",
        categories: ["Google Daydream游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Mega Drive", "gen", "Sega Genesis", "Sega Mega Drive"],
        label: "Mega Drive",
        page: "Mega Drive",
        categories: ["Mega Drive游戏"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["Game Gear", "gg"],
        label: "Game Gear",
        page: "Game Gear",
        categories: ["Game Gear游戏"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["GameStick", "gs"],
        label: "GameStick",
        page: "GameStick",
        categories: ["GameStick游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Amstrad GX4000", "gx4000"],
        label: "Amstrad GX4000",
        page: "Amstrad GX4000",
        categories: ["Amstrad GX4000游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Gizmondo", "gzm"],
        label: "Gizmondo",
        page: "Gizmondo",
        categories: ["Gizmondo游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["HP 3000", "hp3k"],
        label: "HP 3000",
        page: "HP 3000",
        categories: ["HP 3000游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "IBM PC兼容机",
            "ibm",
            "IBM Personal Computer",
            "IBM PC compatible",
        ],
        label: "IBM PC兼容机",
        page: "IBM PC兼容机",
        categories: ["PC游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["Intellivision", "int"],
        label: "Intellivision",
        page: "Intellivision",
        categories: ["Intellivision游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "iOS",
            "iPhone",
            "iPod",
            "iPadOS",
            "iPad",
            "visionOS",
            "Apple Vision Pro",
        ],
        label: "iOS",
        page: "iOS",
        categories: ["iOS游戏"],
        stubTags: ["MSDOS-videogame-stub"],
    },
    {
        aliases: ["雅达利Jaguar", "jag", "Atari Jaguar"],
        label: "雅达利Jaguar",
        page: "雅达利Jaguar",
        categories: ["雅达利Jaguar游戏"],
        stubTags: ["Atari-console-stub"],
    },
    {
        aliases: ["Atari Jaguar CD", "jagcd"],
        label: "Atari Jaguar CD",
        page: "Atari Jaguar CD",
        categories: ["Atari Jaguar CD游戏"],
        stubTags: ["Atari-console-stub"],
    },
    {
        aliases: ["Linux", "lin"],
        label: "Linux",
        page: "Linux",
        categories: ["Linux游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Amazon Luna", "luna"],
        label: "Amazon Luna",
        page: "Amazon Luna",
        categories: ["Amazon Luna游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Atari Lynx", "lynx"],
        label: "Atari Lynx",
        page: "Atari Lynx",
        categories: ["Atari Lynx游戏"],
        stubTags: ["Atari-console-stub"],
    },
    {
        aliases: ["Classic Mac OS", "Classic Mac", "Macintosh"],
        label: "Classic Mac OS",
        page: "Classic Mac OS",
        categories: ["Mac OS游戏"],
        stubTags: ["Mac-videogame-stub"],
    },
    {
        aliases: ["Maemo"],
        label: "Maemo",
        page: "Maemo",
        categories: ["Maemo游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["大型计算机", "main", "Mainframe computer"],
        label: "大型计算机",
        page: "大型计算机",
        categories: ["大型计算机游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["手机", "mobi", "Mobile phone", "Mobile"],
        label: "手机",
        page: "手机",
        categories: ["手机游戏"],
        stubTags: ["Mobile-videogame-stub"],
    },
    {
        aliases: ["MeeGo"],
        label: "MeeGo",
        page: "MeeGo",
        categories: ["MeeGo游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["MSX"],
        label: "MSX",
        page: "MSX",
        categories: ["MSX游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["MSX2"],
        label: "MSX2",
        page: "MSX2",
        categories: ["MSX2游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["任天堂64", "n64", "Nintendo 64", "iQue Player"],
        label: "任天堂64",
        page: "任天堂64",
        categories: ["任天堂64游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["Neo Geo", "neo", "Neo Geo AES"],
        label: "Neo Geo",
        page: "Neo Geo",
        categories: ["Neo Geo游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Hyper Neo Geo 64", "neo64"],
        label: "Hyper Neo Geo 64",
        page: "Hyper Neo Geo 64",
        categories: ["Hyper Neo Geo 64游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Neo Geo CD", "neocd"],
        label: "Neo Geo CD",
        page: "Neo Geo CD",
        categories: ["Neo Geo CD游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["红白机", "nes", "Nintendo Entertainment System", "Famicom"],
        label: "红白机",
        page: "红白机",
        categories: ["红白机游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["NeXT Computer", "next"],
        label: "NeXT Computer",
        page: "NeXT Computer",
        categories: ["NeXT Computer游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["N-Gage", "nge"],
        label: "N-Gage",
        page: "N-Gage",
        categories: ["N-Gage游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Neo Geo Pocket", "ngp"],
        label: "Neo Geo Pocket",
        page: "Neo Geo Pocket",
        categories: ["Neo Geo Pocket游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Neo Geo Pocket Color", "ngpc"],
        label: "Neo Geo Pocket Color",
        page: "Neo Geo Pocket Color",
        categories: ["Neo Geo Pocket Color游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["Nintendo Network", "nn"],
        label: "Nintendo Network",
        page: "Nintendo Network",
        categories: ["Nintendo Network游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["任天堂Switch", "ns", "Nintendo Switch", "Switch"],
        label: "任天堂Switch",
        page: "任天堂Switch",
        categories: ["任天堂Switch游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["任天堂Switch 2", "ns2", "Nintendo Switch 2", "Switch 2"],
        label: "任天堂Switch 2",
        page: "任天堂Switch 2",
        categories: ["任天堂Switch 2游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["美格福斯奧德賽", "ody", "Magnavox Odyssey"],
        label: "美格福斯奧德賽",
        page: "美格福斯奧德賽",
        categories: ["美格福斯奧德賽遊戲"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["米罗华奥德赛²", "ody2", "Magnavox Odyssey 2"],
        label: "米罗华奥德赛²",
        page: "米罗华奥德赛²",
        categories: ["米罗华奥德赛²游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["OS/2", "os2"],
        label: "OS/2",
        page: "OS/2",
        categories: ["OS/2游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["macOS", "osx", "mac", "OS X"],
        label: "macOS",
        page: "macOS",
        categories: ["macOS游戏"],
        stubTags: ["Mac-videogame-stub"],
    },
    {
        aliases: ["Ouya"],
        label: "Ouya",
        page: "Ouya",
        categories: ["Ouya游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Philips P2000", "p2000"],
        label: "Philips P2000",
        page: "Philips P2000",
        categories: ["Philips P2000游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Palm OS", "palm"],
        label: "Palm OS",
        page: "Palm OS",
        categories: ["Palm OS游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["电子邮件游戏", "pbem", "Play-by-email"],
        label: "电子邮件游戏",
        page: "电子邮件游戏",
        categories: ["电子邮件游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["PC-6000系列", "pc60", "PC-6000 series"],
        label: "PC-6000系列",
        page: "PC-6000系列",
        categories: ["PC-6000系列游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["PC-8000系列", "pc80", "PC-8000 series"],
        label: "PC-8000系列",
        page: "PC-8000系列",
        categories: ["PC-8000系列游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["PC-8800系列", "pc88", "PC-8800 series"],
        label: "PC-8800系列",
        page: "PC-8800系列",
        categories: ["PC-8800系列游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["PC-9800系列", "pc98", "PC-9800 series"],
        label: "PC-9800系列",
        page: "PC-9800系列",
        categories: ["PC-9800系列游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["PC Engine CD-ROM²", "pcd", "TurboGrafx-CD"],
        label: "PC Engine CD-ROM²",
        page: "PC Engine CD-ROM²",
        categories: ["PC Engine CD-ROM²游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["PC Engine", "pce", "TurboGrafx-16"],
        label: "PC Engine",
        page: "PC Engine",
        categories: ["PC Engine游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["PC-FX", "pcfx"],
        label: "PC-FX",
        page: "PC-FX",
        categories: ["PC-FX游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["IBM PCjr", "pcjr"],
        label: "IBM PCjr",
        page: "IBM PCjr",
        categories: ["IBM PCjr游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["Amstrad PCW", "pcw"],
        label: "Amstrad PCW",
        page: "Amstrad PCW",
        categories: ["Amstrad PCW游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["Imlac PDS-1", "pds1"],
        label: "Imlac PDS-1",
        page: "Imlac PDS-1",
        categories: ["Imlac PDS-1游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["PDP-1", "pdp1"],
        label: "PDP-1",
        page: "PDP-1",
        categories: ["PDP-1游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Commodore PET", "pet"],
        label: "Commodore PET",
        page: "Commodore PET",
        categories: ["Commodore PET游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["PICO 4", "pico4"],
        label: "PICO 4",
        page: "PICO 4",
        categories: ["PICO 4游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Apple Pippin", "pippin"],
        label: "Apple Pippin",
        page: "Apple Pippin",
        categories: ["Apple Pippin游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["PLATO"],
        label: "PLATO",
        page: "PLATO",
        categories: ["PLATO游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Pocket PC", "ppc"],
        label: "Pocket PC",
        page: "Pocket PC",
        categories: ["Pocket PC游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["PC"],
        label: "PC",
    },
    {
        aliases: ["PlayStation", "ps1", "PlayStation 1", "PS one"],
        label: "PlayStation",
        page: "PlayStation",
        categories: ["PlayStation游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["PlayStation 2", "ps2"],
        label: "PlayStation 2",
        page: "PlayStation 2",
        categories: ["PlayStation 2游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["PlayStation 3", "ps3"],
        label: "PlayStation 3",
        page: "PlayStation 3",
        categories: ["PlayStation 3游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["PlayStation 4", "ps4"],
        label: "PlayStation 4",
        page: "PlayStation 4",
        categories: ["PlayStation 4游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["PlayStation 5", "ps5"],
        label: "PlayStation 5",
        page: "PlayStation 5",
        categories: ["PlayStation 5游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["PlayStation Network", "psn"],
        label: "PlayStation Network",
        page: "PlayStation Network",
        categories: ["PlayStation Network游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["PlayStation Portable", "psp"],
        label: "PlayStation Portable",
        page: "PlayStation Portable",
        categories: ["PlayStation Portable游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["PlayStation Vita", "psv", "PS Vita", "PSVita"],
        label: "PlayStation Vita",
        page: "PlayStation Vita",
        categories: ["PlayStation Vita游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["PlayStation VR", "psvr", "PlayStation VR2", "PS VR"],
        label: "PlayStation VR",
        page: "PlayStation VR",
        categories: ["PlayStation VR游戏"],
        stubTags: ["PlayStation-stub"],
    },
    {
        aliases: ["Meta Quest", "quest", "Oculus Quest", "Oculus Rift"],
        label: "Meta Quest",
        page: "Meta Quest",
        categories: ["Meta Quest游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["RISC OS", "ros"],
        label: "RISC OS",
        page: "RISC OS",
        categories: ["RISC OS游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["R-Zone", "rz"],
        label: "R-Zone",
        page: "R-Zone",
        categories: ["R-Zone游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Sega 32X", "s32x"],
        label: "Sega 32X",
        page: "Sega 32X",
        categories: ["Sega 32X游戏"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["SAM Coupé", "sam"],
        label: "SAM Coupé",
        page: "SAM Coupé",
        categories: ["SAM Coupé游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["世嘉土星", "sat", "Sega Saturn", "Saturn"],
        label: "世嘉土星",
        page: "世嘉土星",
        categories: ["世嘉土星游戏"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["Mega-CD", "scd", "Sega CD", "Mega CD"],
        label: "Mega-CD",
        page: "Mega-CD",
        categories: ["Mega-CD游戏"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["Super Cassette Vision", "scv"],
        label: "Super Cassette Vision",
        page: "Super Cassette Vision",
        categories: ["Super Cassette Vision游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["SG-1000", "sg1k", "Sega SG-1000"],
        label: "SG-1000",
        page: "SG-1000",
        categories: ["SG-1000游戏"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["Nvidia Shield", "shield"],
        label: "Nvidia Shield",
        page: "Nvidia Shield",
        categories: ["Nvidia Shield游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: [
            "世嘉Master System",
            "sms",
            "Sega Master System",
            "Master System",
        ],
        label: "世嘉Master System",
        page: "世嘉Master System",
        categories: ["世嘉Master System游戏"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: [
            "超級任天堂",
            "snes",
            "Super Nintendo",
            "Super Famicom",
            "Super Comboy",
        ],
        label: "超級任天堂",
        page: "超級任天堂",
        categories: ["超級任天堂遊戲"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["社交网络游戏", "sng", "social network game"],
        label: "社交网络游戏",
        page: "社交网络游戏",
        categories: ["社交网络游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Google Stadia", "stadia"],
        label: "Google Stadia",
        page: "Google Stadia",
        categories: ["Google Stadia游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Xerox Star", "star"],
        label: "Xerox Star",
        page: "Xerox Star",
        categories: ["Xerox Star游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Steam"],
        label: "Steam",
        page: "Steam",
        categories: ["Steam游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Satellaview", "stv"],
        label: "Satellaview",
        page: "Satellaview",
        categories: ["Satellaview游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Symbian OS", "sym", "EPOC32"],
        label: "Symbian OS",
        page: "Symbian OS",
        categories: ["Symbian游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Tandy 1000", "t1000"],
        label: "Tandy 1000",
        page: "Tandy 1000",
        categories: ["Tandy 1000游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Thomson computers", "th1"],
        label: "Thomson computers",
        page: "Thomson computers",
        categories: ["Thomson computers游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["Tatung Einstein", "tein"],
        label: "Tatung Einstein",
        page: "Tatung Einstein",
        categories: ["Tatung Einstein游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["TI-99/4A", "ti99"],
        label: "TI-99/4A",
        page: "TI-99/4A",
        categories: ["TI-99/4A游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Tizen", "tiz"],
        label: "Tizen",
        page: "Tizen",
        categories: ["Tizen游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["TRS-80", "trs80"],
        label: "TRS-80",
        page: "TRS-80",
        categories: ["TRS-80游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["TRS-80 Color Computer", "trscc"],
        label: "TRS-80 Color Computer",
        page: "TRS-80 Color Computer",
        categories: ["TRS-80 Color Computer游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["tvOS"],
        label: "tvOS",
        page: "tvOS",
        categories: ["tvOS游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Tektronix 4050", "tx4050"],
        label: "Tektronix 4050",
        page: "Tektronix 4050",
        categories: ["Tektronix 4050游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Tapwave Zodiac", "tz"],
        label: "Tapwave Zodiac",
        page: "Tapwave Zodiac",
        categories: ["Tapwave Zodiac游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Unix"],
        label: "Unix",
        page: "Unix",
        categories: ["Unix游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Virtual Boy", "vboy"],
        label: "Virtual Boy",
        page: "Virtual Boy",
        categories: ["Virtual Boy游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["VIC-20", "vic20"],
        label: "VIC-20",
        page: "VIC-20",
        categories: ["VIC-20游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["HTC Vive", "vive"],
        label: "HTC Vive",
        page: "HTC Vive",
        categories: ["HTC Vive游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Vectrex", "vtx"],
        label: "Vectrex",
        page: "Vectrex",
        categories: ["Vectrex游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["watchOS"],
        label: "watchOS",
        page: "watchOS",
        categories: ["watchOS游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["网页游戏", "web", "Browser game", "Web game"],
        label: "网页游戏",
        page: "网页游戏",
        categories: ["网页游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["webOS"],
        label: "webOS",
        page: "webOS",
        categories: ["webOS游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Wii", "WiiWare", "Wii Virtual Console"],
        label: "Wii",
        page: "Wii",
        categories: ["Wii游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["Wii U", "wiiu", "WiiU Virtual Console"],
        label: "Wii U",
        page: "Wii U",
        categories: ["Wii U游戏"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: ["Windows", "win", "Microsoft Windows"],
        label: "Windows",
        page: "Windows",
        categories: ["Windows游戏"],
        stubTags: ["Windows-videogame-stub"],
    },
    {
        aliases: ["Windows Mobile", "wmo"],
        label: "Windows Mobile",
        page: "Windows Mobile",
        categories: ["Windows Mobile游戏"],
        stubTags: ["Windows-videogame-stub"],
    },
    {
        aliases: ["Windows Phone", "wp"],
        label: "Windows Phone",
        page: "Windows Phone",
        categories: ["Windows Phone游戏"],
        stubTags: ["Windows-videogame-stub"],
    },
    {
        aliases: ["WonderSwan", "ws"],
        label: "WonderSwan",
        page: "WonderSwan",
        categories: ["WonderSwan游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["WonderSwan Color", "wsc"],
        label: "WonderSwan Color",
        page: "WonderSwan Color",
        categories: ["WonderSwan Color游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["OLPC XO-1", "x01"],
        label: "OLPC XO-1",
        page: "OLPC XO-1",
        categories: ["OLPC XO-1游戏"],
        stubTags: ["computer-videogame-stub"],
    },
    {
        aliases: ["夏普X1", "x1", "Sharp X1"],
        label: "夏普X1",
        page: "夏普X1",
        categories: ["夏普X1游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["X68000", "x68k"],
        label: "X68000",
        page: "X68000",
        categories: ["X68000游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Xbox", "xb", "Xbox Live Arcade"],
        label: "Xbox",
        page: "Xbox",
        categories: ["Xbox游戏"],
        stubTags: ["Xbox-stub"],
    },
    {
        aliases: ["Xbox 360", "xb360", "Xbox 360 Live Arcade", "X360"],
        label: "Xbox 360",
        page: "Xbox 360",
        categories: ["Xbox 360游戏"],
        stubTags: ["Xbox-stub"],
    },
    {
        aliases: ["Xbox One", "xbo", "XOne"],
        label: "Xbox One",
        page: "Xbox One",
        categories: ["Xbox One游戏"],
        stubTags: ["Xbox-stub"],
    },
    {
        aliases: [
            "Xbox Series X/S",
            "xbx-s",
            "XBX/S",
            "Xbox Series",
            "Xbox Series X and S",
            "Xbox Series X",
            "Xbox Series S",
            "XS",
            "XSX/S",
        ],
        label: "Xbox Series X/S",
        page: "Xbox Series X/S",
        categories: ["Xbox Series X/S游戏"],
        stubTags: ["Xbox-stub"],
    },
    {
        aliases: ["Zeebo", "zb"],
        label: "Zeebo",
        page: "Zeebo",
        categories: ["Zeebo游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["ZETA", "ZETA (operating system)"],
        label: "ZETA",
        page: "ZETA",
        categories: ["ZETA游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["Zune HD", "zune"],
        label: "Zune HD",
        page: "Zune HD",
        categories: ["Zune HD游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["ZX Spectrum", "zx"],
        label: "ZX Spectrum",
        page: "ZX Spectrum",
        categories: ["ZX Spectrum游戏"],
        stubTags: ["videogame-stub"],
    },
    {
        aliases: ["ZX81"],
        label: "ZX81",
        page: "ZX81",
        categories: ["ZX81游戏"],
        stubTags: ["videogame-stub"],
    },
] satisfies TerminologyDefinition[];
