/**
 * Configures ESLint rules and globals for the gadget workspace.
 */

import jsdoc from "eslint-plugin-jsdoc";

const browserGlobals = {
    AbortController: "readonly",
    Blob: "readonly",
    CustomEvent: "readonly",
    DocumentFragment: "readonly",
    FormData: "readonly",
    Headers: "readonly",
    HTMLDialogElement: "readonly",
    HTMLElement: "readonly",
    IntersectionObserver: "readonly",
    MutationObserver: "readonly",
    Node: "readonly",
    Promise: "readonly",
    Request: "readonly",
    Response: "readonly",
    URL: "readonly",
    URLSearchParams: "readonly",
    console: "readonly",
    document: "readonly",
    fetch: "readonly",
    history: "readonly",
    localStorage: "readonly",
    location: "readonly",
    navigator: "readonly",
    queueMicrotask: "readonly",
    sessionStorage: "readonly",
    setInterval: "readonly",
    setTimeout: "readonly",
    clearInterval: "readonly",
    clearTimeout: "readonly",
    window: "readonly",
};

const mediaWikiGlobals = {
    $: "readonly",
    OO: "readonly",
    mw: "readonly",
};

export default [
    {
        ignores: [
            "**/node_modules/**",
            "**/dist/**",
            "**/build/**",
            "**/coverage/**",
            "**/.cache/**",
            "**/.parcel-cache/**",
            "**/.turbo/**",
            "**/.vite/**",
        ],
    },
    {
        files: ["**/*.{js,mjs,cjs}"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                ...browserGlobals,
                ...mediaWikiGlobals,
            },
        },
        plugins: {
            jsdoc,
        },
        linterOptions: {
            reportUnusedDisableDirectives: "error",
            reportUnusedInlineConfigs: "error",
        },
        rules: {
            "accessor-pairs": "error",
            "array-callback-return": [
                "error",
                {
                    allowImplicit: false,
                    checkForEach: true,
                },
            ],
            "block-scoped-var": "error",
            camelcase: ["error", { properties: "never", ignoreGlobals: true }],
            "capitalized-comments": [
                "error",
                "always",
                {
                    ignoreConsecutiveComments: true,
                    ignoreInlineComments: true,
                    ignorePattern:
                        "global|eslint|istanbul|webpack|vite|TODO|FIXME",
                },
            ],
            "class-methods-use-this": "error",
            complexity: ["error", { max: 8 }],
            "consistent-return": "error",
            curly: ["error", "all"],
            "default-case": "error",
            "default-case-last": "error",
            "default-param-last": "error",
            eqeqeq: ["error", "always", { null: "ignore" }],
            "func-name-matching": "error",
            "func-names": ["error", "as-needed"],
            "func-style": [
                "error",
                "declaration",
                { allowArrowFunctions: true },
            ],
            "grouped-accessor-pairs": ["error", "getBeforeSet"],
            "guard-for-in": "error",
            "id-length": [
                "error",
                {
                    exceptions: ["$", "_", "i", "j", "x", "y"],
                    min: 2,
                },
            ],
            "init-declarations": ["error", "always"],
            "jsdoc/check-access": "error",
            "jsdoc/check-alignment": "error",
            "jsdoc/check-examples": "error",
            "jsdoc/check-indentation": "error",
            "jsdoc/check-line-alignment": "error",
            "jsdoc/check-param-names": "error",
            "jsdoc/check-property-names": "error",
            "jsdoc/check-syntax": "error",
            "jsdoc/check-tag-names": "error",
            "jsdoc/check-types": "error",
            "jsdoc/check-values": "error",
            "jsdoc/empty-tags": "error",
            "jsdoc/implements-on-classes": "error",
            "jsdoc/informative-docs": "error",
            "jsdoc/match-description": [
                "error",
                {
                    matchDescription: "^[A-Z].*[.!?]$",
                },
            ],
            "jsdoc/multiline-blocks": ["error", { noSingleLineBlocks: true }],
            "jsdoc/no-bad-blocks": "error",
            "jsdoc/no-blank-block-descriptions": "error",
            "jsdoc/no-blank-blocks": "error",
            "jsdoc/no-defaults": "error",
            "jsdoc/no-missing-syntax": [
                "error",
                {
                    contexts: [
                        "ClassDeclaration",
                        "ExportDefaultDeclaration",
                        "ExportNamedDeclaration",
                        "FunctionDeclaration",
                        "MethodDefinition",
                    ],
                },
            ],
            "jsdoc/no-multi-asterisks": "error",
            "jsdoc/no-restricted-syntax": [
                "error",
                {
                    contexts: [
                        {
                            comment: "JsdocBlock:has(JsdocTag[tag='todo'])",
                            context: "any",
                            message:
                                "Resolve TODOs before committing documented code.",
                        },
                    ],
                },
            ],
            "jsdoc/no-types": "off",
            "jsdoc/no-undefined-types": [
                "error",
                {
                    definedTypes: [
                        "JQuery",
                        "mw.Api",
                        "mw.Title",
                        "OO.ui.Widget",
                    ],
                },
            ],
            "jsdoc/require-asterisk-prefix": "error",
            "jsdoc/require-description": "error",
            "jsdoc/require-description-complete-sentence": "error",
            "jsdoc/require-example": "off",
            "jsdoc/require-hyphen-before-param-description": [
                "error",
                "always",
            ],
            "jsdoc/require-jsdoc": [
                "error",
                {
                    publicOnly: false,
                    require: {
                        ArrowFunctionExpression: true,
                        ClassDeclaration: true,
                        ClassExpression: true,
                        FunctionDeclaration: true,
                        FunctionExpression: true,
                        MethodDefinition: true,
                    },
                },
            ],
            "jsdoc/require-param": "error",
            "jsdoc/require-param-description": "error",
            "jsdoc/require-param-name": "error",
            "jsdoc/require-param-type": "error",
            "jsdoc/require-property": "error",
            "jsdoc/require-property-description": "error",
            "jsdoc/require-property-name": "error",
            "jsdoc/require-property-type": "error",
            "jsdoc/require-returns": "error",
            "jsdoc/require-returns-check": "error",
            "jsdoc/require-returns-description": "error",
            "jsdoc/require-returns-type": "error",
            "jsdoc/require-template": "error",
            "jsdoc/require-throws": "error",
            "jsdoc/require-yields": "error",
            "jsdoc/require-yields-check": "error",
            "jsdoc/sort-tags": "error",
            "jsdoc/tag-lines": ["error", "any", { startLines: 1 }],
            "jsdoc/text-escaping": "error",
            "jsdoc/valid-types": "error",
            "logical-assignment-operators": [
                "error",
                "always",
                {
                    enforceForIfStatements: true,
                },
            ],
            "max-classes-per-file": ["error", 1],
            "max-depth": ["error", 3],
            "max-lines": [
                "error",
                {
                    max: 300,
                    skipBlankLines: true,
                    skipComments: true,
                },
            ],
            "max-lines-per-function": [
                "error",
                {
                    max: 60,
                    skipBlankLines: true,
                    skipComments: true,
                },
            ],
            "max-len": [
                "error",
                {
                    code: 79,
                    comments: 72,
                    ignoreRegExpLiterals: true,
                    ignoreStrings: true,
                    ignoreTemplateLiterals: true,
                    ignoreUrls: true,
                    tabWidth: 4,
                },
            ],
            "max-nested-callbacks": ["error", 3],
            "max-params": ["error", 4],
            "new-cap": "error",
            "no-alert": "error",
            "no-array-constructor": "error",
            "no-await-in-loop": "error",
            "no-bitwise": "error",
            "no-caller": "error",
            "no-case-declarations": "error",
            "no-console": ["error", { allow: ["warn", "error"] }],
            "no-constructor-return": "error",
            "no-continue": "error",
            "no-else-return": ["error", { allowElseIf: false }],
            "no-empty-function": "error",
            "no-empty-pattern": "error",
            "no-eq-null": "off",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-boolean-cast": [
                "error",
                { enforceForInnerExpressions: true },
            ],
            "no-implicit-coercion": ["error", { allow: [] }],
            "no-implicit-globals": "error",
            "no-implied-eval": "error",
            "no-inline-comments": "error",
            "no-invalid-this": "error",
            "no-iterator": "error",
            "no-labels": "error",
            "no-lone-blocks": "error",
            "no-lonely-if": "error",
            "no-magic-numbers": [
                "error",
                {
                    ignore: [-1, 0, 1, 2],
                    ignoreArrayIndexes: true,
                    ignoreDefaultValues: true,
                },
            ],
            "no-multi-assign": "error",
            "no-negated-condition": "error",
            "no-nested-ternary": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-wrappers": "error",
            "no-object-constructor": "error",
            "no-param-reassign": "error",
            "no-plusplus": "error",
            "no-promise-executor-return": "error",
            "no-proto": "error",
            "no-restricted-exports": [
                "error",
                {
                    restrictedNamedExports: ["default", "then"],
                },
            ],
            "no-restricted-globals": ["error", "event", "fdescribe"],
            "no-restricted-imports": ["error", { patterns: ["../*"] }],
            "no-return-assign": ["error", "always"],
            "no-script-url": "error",
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-shadow": "error",
            "no-template-curly-in-string": "error",
            "no-throw-literal": "error",
            "no-undef": "error",
            "no-undef-init": "error",
            "no-underscore-dangle": "error",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": "error",
            "no-unreachable-loop": "error",
            "no-unused-expressions": "error",
            "no-unused-private-class-members": "error",
            "no-unused-vars": [
                "error",
                {
                    args: "after-used",
                    argsIgnorePattern: "^_",
                    caughtErrors: "all",
                    caughtErrorsIgnorePattern: "^_",
                    varsIgnorePattern: "^_",
                },
            ],
            "no-use-before-define": [
                "error",
                {
                    classes: true,
                    functions: false,
                    variables: true,
                },
            ],
            "no-useless-assignment": "error",
            "no-useless-call": "error",
            "no-useless-computed-key": "error",
            "no-useless-concat": "error",
            "no-useless-constructor": "error",
            "no-useless-rename": "error",
            "no-useless-return": "error",
            "no-var": "error",
            "object-shorthand": ["error", "always"],
            "one-var": ["error", "never"],
            "operator-assignment": ["error", "always"],
            "prefer-arrow-callback": ["error", { allowNamedFunctions: false }],
            "prefer-const": ["error", { destructuring: "all" }],
            "prefer-destructuring": [
                "error",
                {
                    array: false,
                    object: true,
                },
                {
                    enforceForRenamedProperties: false,
                },
            ],
            "prefer-exponentiation-operator": "error",
            "prefer-named-capture-group": "error",
            "prefer-object-has-own": "error",
            "prefer-object-spread": "error",
            "prefer-promise-reject-errors": "error",
            "prefer-regex-literals": [
                "error",
                { disallowRedundantWrapping: true },
            ],
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            radix: ["error", "always"],
            "require-atomic-updates": "error",
            "require-await": "error",
            "require-unicode-regexp": "error",
            "sort-imports": [
                "error",
                {
                    allowSeparatedGroups: true,
                    ignoreCase: true,
                    ignoreDeclarationSort: false,
                    ignoreMemberSort: false,
                },
            ],
            "sort-keys": [
                "error",
                "asc",
                { caseSensitive: false, natural: true },
            ],
            "sort-vars": "error",
            strict: ["error", "never"],
            "symbol-description": "error",
            "unicode-bom": ["error", "never"],
            "vars-on-top": "error",
            yoda: ["error", "never"],
        },
    },
    {
        files: ["**/*.cjs"],
        languageOptions: {
            sourceType: "commonjs",
        },
    },
    {
        files: ["eslint.config.js", "**/scripts/**/*.{js,mjs,cjs}"],
        languageOptions: {
            globals: {
                Buffer: "readonly",
                console: "readonly",
                process: "readonly",
            },
        },
        rules: {
            "no-console": "off",
            "no-magic-numbers": "off",
            "no-restricted-imports": "off",
            "sort-keys": "off",
        },
    },
];
