import { defineTerminologies } from "./terminology.ts";

export default defineTerminologies([
    {
        aliases: ["07th Expansion"],
        name: "07th Expansion",
        page: "07th Expansion",
        categories: ["07th Expansion遊戲"],
    },
    {
        aliases: ["1-Up Studio"],
        name: "1-Up Studio",
        page: "1-Up Studio",
        categories: ["1-Up Studio遊戲"],
    },
    {
        aliases: ["11 Bit Studios"],
        name: "11 Bit Studios",
        page: "11 Bit Studios",
        categories: ["11 Bit Studios遊戲"],
    },
    {
        aliases: ["17-bit"],
        name: "17-Bit",
        page: "17-Bit",
        categories: ["17-Bit遊戲"],
    },
    {
        aliases: ["1C Company"],
        name: "1C Company",
        page: "1C Company",
        categories: ["1C Company遊戲"],
    },
    {
        aliases: ["2015 (company)"],
        name: "2015 (company)",
        page: "2015 (company)",
        categories: ["2015 (company)遊戲"],
    },
    {
        aliases: ["21st Street Games"],
        name: "21st Street Games",
        page: "21st Street Games",
        categories: ["21st Street Games遊戲"],
    },
    {
        aliases: ["22cans"],
        name: "22cans",
        page: "22cans",
        categories: ["22cans遊戲"],
    },
    {
        aliases: ["2K Australia"],
        name: "2K Australia",
        page: "2K Australia",
        categories: ["2K Australia遊戲"],
    },
    {
        aliases: ["2k-china", "2K China", "2K中国"],
        name: "2K中国",
        page: "2K中国",
        categories: ["2K中國遊戲"],
    },
    {
        aliases: ["2k-company", "2K (company)", "2K Games"],
        name: "2K Games",
        page: "2K Games",
        categories: ["2K Games遊戲"],
    },
    {
        aliases: ["2K Czech"],
        name: "2K Czech",
        page: "2K Czech",
        categories: ["2K Czech遊戲"],
    },
    {
        aliases: ["2K Los Angeles"],
        name: "2K Los Angeles",
        page: "2K Los Angeles",
        categories: ["2K Los Angeles遊戲"],
    },
    {
        aliases: ["2K Marin"],
        name: "2K Marin",
        page: "2K Marin",
        categories: ["2K Marin遊戲"],
    },
    {
        aliases: ["31st Union"],
        name: "31st Union",
        page: "31st Union",
        categories: ["31st Union遊戲"],
    },
    {
        aliases: ["37games", "三七互娱"],
        name: "三七互娱",
        page: "三七互娱",
        categories: ["三七互娛遊戲"],
    },
    {
        aliases: ["38 Studios"],
        name: "38 Studios",
        page: "38 Studios",
        categories: ["38 Studios遊戲"],
    },
    {
        aliases: ["3D Realms"],
        name: "3D Realms",
        page: "3D Realms",
        categories: ["3D Realms遊戲"],
    },
    {
        aliases: ["4A Games"],
        name: "4A Games",
        page: "4A Games",
        categories: ["4A Games遊戲"],
    },
    {
        aliases: ["4J Studios"],
        name: "4J Studios",
        page: "4J Studios",
        categories: ["4J Studios遊戲"],
    },
    {
        aliases: ["4mm Games"],
        name: "4mm Games",
        page: "4mm Games",
        categories: ["4mm Games遊戲"],
    },
    {
        aliases: ["505-games", "505 Games", "505游戏"],
        name: "505游戏",
        page: "505游戏",
        categories: ["505遊戲遊戲"],
    },
    {
        aliases: ["5th Cell"],
        name: "5th Cell",
        page: "5th Cell",
        categories: ["5th Cell遊戲"],
    },
    {
        aliases: ["704games"],
        name: "704Games",
        page: "704Games",
        categories: ["704Games遊戲"],
    },
    {
        aliases: ["7th Level"],
        name: "7th Level",
        page: "7th Level",
        categories: ["7th Level遊戲"],
    },
    {
        aliases: ["8-4"],
        name: "8-4",
        page: "8-4",
        categories: ["8-4遊戲"],
    },
    {
        aliases: ["989 Studios"],
        name: "989 Studios",
        page: "989 Studios",
        categories: ["989 Studios遊戲"],
    },
    {
        aliases: ["ABA Games"],
        name: "ABA Games",
        page: "ABA Games",
        categories: ["ABA Games遊戲"],
    },
    {
        aliases: ["ABS-CBN Digital Media"],
        name: "ABS-CBN Digital Media",
        page: "ABS-CBN Digital Media",
        categories: ["ABS-CBN Digital Media遊戲"],
    },
    {
        aliases: ["Absolute Entertainment"],
        name: "Absolute Entertainment",
        page: "Absolute Entertainment",
        categories: ["Absolute Entertainment遊戲"],
    },
    {
        aliases: ["Absurd Ventures"],
        name: "Absurd Ventures",
        page: "Absurd Ventures",
        categories: ["Absurd Ventures遊戲"],
    },
    {
        aliases: ["Access Games"],
        name: "Access Games",
        page: "Access Games",
        categories: ["Access Games遊戲"],
    },
    {
        aliases: ["Access Software"],
        name: "Access Software",
        page: "Access Software",
        categories: ["Access Software遊戲"],
    },
    {
        aliases: ["Acclaim Entertainment"],
        name: "Acclaim Entertainment",
        page: "Acclaim Entertainment",
        categories: ["Acclaim Entertainment遊戲"],
    },
    {
        aliases: ["accolade-inc", "Accolade, Inc.", "Accolade"],
        name: "Accolade",
        page: "Accolade",
        categories: ["Accolade遊戲"],
    },
    {
        aliases: ["ACE Team"],
        name: "ACE Team",
        page: "ACE Team",
        categories: ["ACE Team遊戲"],
    },
    {
        aliases: ["acornsoft"],
        name: "Acornsoft",
        page: "Acornsoft",
        categories: ["Acornsoft遊戲"],
    },
    {
        aliases: ["acquire-company", "Acquire (company)", "Acquire"],
        name: "Acquire",
        page: "Acquire",
        categories: ["Acquire遊戲"],
    },
    {
        aliases: ["Action Button Entertainment"],
        name: "Action Button Entertainment",
        page: "Action Button Entertainment",
        categories: ["Action Button Entertainment遊戲"],
    },
    {
        aliases: ["Action Forms"],
        name: "Action Forms",
        page: "Action Forms",
        categories: ["Action Forms遊戲"],
    },
    {
        aliases: ["Active Enterprises"],
        name: "Active Enterprises",
        page: "Active Enterprises",
        categories: ["Active Enterprises遊戲"],
    },
    {
        aliases: ["activision", "动视"],
        name: "动视",
        page: "动视",
        categories: ["動視遊戲"],
        stubTags: ["Activision-stub"],
    },
    {
        aliases: ["activision-blizzard", "Activision Blizzard", "动视暴雪"],
        name: "动视暴雪",
        page: "动视暴雪",
        categories: ["動視暴雪遊戲"],
    },
    {
        aliases: ["Actual Entertainment"],
        name: "Actual Entertainment",
        page: "Actual Entertainment",
        categories: ["Actual Entertainment遊戲"],
    },
    {
        aliases: ["AdHoc Studio"],
        name: "AdHoc Studio",
        page: "AdHoc Studio",
        categories: ["AdHoc Studio遊戲"],
    },
    {
        aliases: ["adk-corporation", "ADK Corporation", "ADK (游戏公司)"],
        name: "ADK (游戏公司)",
        page: "ADK (游戏公司)",
        categories: ["ADK (遊戲公司)遊戲"],
    },
    {
        aliases: ["Adult Swim Games"],
        name: "Adult Swim Games",
        page: "Adult Swim Games",
        categories: ["Adult Swim Games遊戲"],
    },
    {
        aliases: ["Adventure International"],
        name: "Adventure International",
        page: "Adventure International",
        categories: ["Adventure International遊戲"],
    },
    {
        aliases: ["Adventure Soft"],
        name: "Adventure Soft",
        page: "Adventure Soft",
        categories: ["Adventure Soft遊戲"],
    },
    {
        aliases: ["Aftershock PC"],
        name: "Aftershock PC",
        page: "Aftershock PC",
        categories: ["Aftershock PC遊戲"],
    },
    {
        aliases: ["Agate (game company)"],
        name: "Agate (game company)",
        page: "Agate (game company)",
        categories: ["Agate (game company)遊戲"],
    },
    {
        aliases: ["Agatsuma Entertainment"],
        name: "Agatsuma Entertainment",
        page: "Agatsuma Entertainment",
        categories: ["Agatsuma Entertainment遊戲"],
    },
    {
        aliases: ["AGD Interactive"],
        name: "AGD Interactive",
        page: "AGD Interactive",
        categories: ["AGD Interactive遊戲"],
    },
    {
        aliases: ["ageod"],
        name: "AGEod",
        page: "AGEod",
        categories: ["AGEod遊戲"],
    },
    {
        aliases: ["agetec"],
        name: "Agetec",
        page: "Agetec",
        categories: ["Agetec遊戲"],
    },
    {
        aliases: ["Aggro Crab"],
        name: "Aggro Crab",
        page: "Aggro Crab",
        categories: ["Aggro Crab遊戲"],
    },
    {
        aliases: ["aicom"],
        name: "Aicom",
        page: "Aicom",
        categories: ["Aicom遊戲"],
    },
    {
        aliases: ["AirG Inc."],
        name: "AirG Inc.",
        page: "AirG Inc.",
        categories: ["AirG Inc.遊戲"],
    },
    {
        aliases: ["Airship Syndicate"],
        name: "Airship Syndicate",
        page: "Airship Syndicate",
        categories: ["Airship Syndicate遊戲"],
    },
    {
        aliases: ["Airtight Games"],
        name: "Airtight Games",
        page: "Airtight Games",
        categories: ["Airtight Games遊戲"],
    },
    {
        aliases: ["akabeisoft2"],
        name: "Akabeisoft2",
        page: "Akabeisoft2",
        categories: ["Akabeisoft2遊戲"],
    },
    {
        aliases: ["akella"],
        name: "Akella",
        page: "Akella",
        categories: ["Akella遊戲"],
    },
    {
        aliases: ["Aksys Games"],
        name: "Aksys Games",
        page: "Aksys Games",
        categories: ["Aksys Games遊戲"],
    },
    {
        aliases: ["Akupara Games"],
        name: "Akupara Games",
        page: "Akupara Games",
        categories: ["Akupara Games遊戲"],
    },
    {
        aliases: ["alawar"],
        name: "Alawar",
        page: "Alawar",
        categories: ["Alawar遊戲"],
    },
    {
        aliases: ["Alcachofa Soft"],
        name: "Alcachofa Soft",
        page: "Alcachofa Soft",
        categories: ["Alcachofa Soft遊戲"],
    },
    {
        aliases: ["alchemist-company", "Alchemist (company)", "Alchemist"],
        name: "Alchemist",
        page: "Alchemist",
        categories: ["Alchemist遊戲"],
    },
    {
        aliases: ["Alfa System"],
        name: "Alfa System",
        page: "Alfa System",
        categories: ["Alfa System遊戲"],
    },
    {
        aliases: ["Aliasworlds Entertainment"],
        name: "Aliasworlds Entertainment",
        page: "Aliasworlds Entertainment",
        categories: ["Aliasworlds Entertainment遊戲"],
    },
    {
        aliases: ["alice-and-smith", "Alice & Smith"],
        name: "Alice & Smith",
        page: "Alice & Smith",
        categories: ["Alice & Smith遊戲"],
    },
    {
        aliases: ["All in! Games"],
        name: "All in! Games",
        page: "All in! Games",
        categories: ["All in! Games遊戲"],
    },
    {
        aliases: ["Allods Team"],
        name: "Allods Team",
        page: "Allods Team",
        categories: ["Allods Team遊戲"],
    },
    {
        aliases: ["alphadream"],
        name: "AlphaDream",
        page: "AlphaDream",
        categories: ["AlphaDream遊戲"],
    },
    {
        aliases: ["alphasim"],
        name: "AlphaSim",
        page: "AlphaSim",
        categories: ["AlphaSim遊戲"],
    },
    {
        aliases: ["alvion"],
        name: "Alvion",
        page: "Alvion",
        categories: ["Alvion遊戲"],
    },
    {
        aliases: ["Amanita Design"],
        name: "Amanita Design",
        page: "Amanita Design",
        categories: ["Amanita Design遊戲"],
    },
    {
        aliases: [
            "amazon-game-studios",
            "Amazon Game Studios",
            "亚马逊游戏工作室",
            "亞馬遜遊戲工作室",
        ],
        name: "亞馬遜遊戲工作室",
        page: "亞馬遜遊戲工作室",
        categories: ["亞馬遜遊戲工作室遊戲"],
    },
    {
        aliases: ["ambrella"],
        name: "Ambrella",
        page: "Ambrella",
        categories: ["Ambrella遊戲"],
    },
    {
        aliases: ["Ambrosia Software"],
        name: "Ambrosia Software",
        page: "Ambrosia Software",
        categories: ["Ambrosia Software遊戲"],
    },
    {
        aliases: ["American Game Cartridges"],
        name: "American Game Cartridges",
        page: "American Game Cartridges",
        categories: ["American Game Cartridges遊戲"],
    },
    {
        aliases: ["amnesiagames"],
        name: "AmnesiaGames",
        page: "AmnesiaGames",
        categories: ["AmnesiaGames遊戲"],
    },
    {
        aliases: ["Amplitude Studios"],
        name: "Amplitude Studios",
        page: "Amplitude Studios",
        categories: ["Amplitude Studios遊戲"],
    },
    {
        aliases: ["amsoft"],
        name: "Amsoft",
        page: "Amsoft",
        categories: ["Amsoft遊戲"],
    },
    {
        aliases: ["Ancient (company)"],
        name: "Ancient (company)",
        page: "Ancient (company)",
        categories: ["Ancient (company)遊戲"],
    },
    {
        aliases: ["Animoca Brands"],
        name: "Animoca Brands",
        page: "Animoca Brands",
        categories: ["Animoca Brands遊戲"],
    },
    {
        aliases: ["Anino Games"],
        name: "Anino Games",
        page: "Anino Games",
        categories: ["Anino Games遊戲"],
    },
    {
        aliases: [
            "annapurna-interactive",
            "Annapurna Interactive",
            "安纳布尔纳互动",
        ],
        name: "安纳布尔纳互动",
        page: "安纳布尔纳互动",
        categories: ["安納布爾納互動遊戲"],
    },
    {
        aliases: ["Antimatter Games"],
        name: "Antimatter Games",
        page: "Antimatter Games",
        categories: ["Antimatter Games遊戲"],
    },
    {
        aliases: ["Apex Computer Productions"],
        name: "Apex Computer Productions",
        page: "Apex Computer Productions",
        categories: ["Apex Computer Productions遊戲"],
    },
    {
        aliases: ["Apogee Entertainment"],
        name: "Apogee Entertainment",
        page: "Apogee Entertainment",
        categories: ["Apogee Entertainment遊戲"],
    },
    {
        aliases: ["AQ Interactive"],
        name: "AQ Interactive",
        page: "AQ Interactive",
        categories: ["AQ Interactive遊戲"],
    },
    {
        aliases: ["aquaplus"],
        name: "Aquaplus",
        page: "Aquaplus",
        categories: ["Aquaplus遊戲"],
    },
    {
        aliases: ["aquria"],
        name: "Aquria",
        page: "Aquria",
        categories: ["Aquria遊戲"],
    },
    {
        aliases: [
            "arc-system-works",
            "Arc System Works",
            "亚克系统",
            "亞克系統",
        ],
        name: "亞克系統",
        page: "亞克系統",
        categories: ["亞克系統遊戲"],
    },
    {
        aliases: ["Arcadia Systems"],
        name: "Arcadia Systems",
        page: "Arcadia Systems",
        categories: ["Arcadia Systems遊戲"],
    },
    {
        aliases: ["Arcen Games"],
        name: "Arcen Games",
        page: "Arcen Games",
        categories: ["Arcen Games遊戲"],
    },
    {
        aliases: ["Archetype Entertainment"],
        name: "Archetype Entertainment",
        page: "Archetype Entertainment",
        categories: ["Archetype Entertainment遊戲"],
    },
    {
        aliases: ["archimage"],
        name: "Archimage",
        page: "Archimage",
        categories: ["Archimage遊戲"],
    },
    {
        aliases: ["arenanet"],
        name: "ArenaNet",
        page: "ArenaNet",
        categories: ["ArenaNet遊戲"],
    },
    {
        aliases: ["Argonaut Games"],
        name: "Argonaut Games",
        page: "Argonaut Games",
        categories: ["Argonaut Games遊戲"],
    },
    {
        aliases: ["arika"],
        name: "Arika",
        page: "Arika",
        categories: ["Arika遊戲"],
    },
    {
        aliases: ["ariolasoft"],
        name: "Ariolasoft",
        page: "Ariolasoft",
        categories: ["Ariolasoft遊戲"],
    },
    {
        aliases: ["Arkane Studios"],
        name: "Arkane Studios",
        page: "Arkane Studios",
        categories: ["Arkane Studios遊戲"],
    },
    {
        aliases: ["Arkedo Studio"],
        name: "Arkedo Studio",
        page: "Arkedo Studio",
        categories: ["Arkedo Studio遊戲"],
    },
    {
        aliases: ["Armature Studio"],
        name: "Armature Studio",
        page: "Armature Studio",
        categories: ["Armature Studio遊戲"],
    },
    {
        aliases: ["Armor Games"],
        name: "Armor Games",
        page: "Armor Games",
        categories: ["Armor Games遊戲"],
    },
    {
        aliases: ["Arrowhead Game Studios"],
        name: "Arrowhead Game Studios",
        page: "Arrowhead Game Studios",
        categories: ["Arrowhead Game Studios遊戲"],
    },
    {
        aliases: ["Arsys Software"],
        name: "Arsys Software",
        page: "Arsys Software",
        categories: ["Arsys Software遊戲"],
    },
    {
        aliases: ["Art Data Interactive"],
        name: "Art Data Interactive",
        page: "Art Data Interactive",
        categories: ["Art Data Interactive遊戲"],
    },
    {
        aliases: ["artdink"],
        name: "Artdink",
        page: "Artdink",
        categories: ["Artdink遊戲"],
    },
    {
        aliases: ["Artech Digital Entertainment"],
        name: "Artech Digital Entertainment",
        page: "Artech Digital Entertainment",
        categories: ["Artech Digital Entertainment遊戲"],
    },
    {
        aliases: ["artepiazza"],
        name: "ArtePiazza",
        page: "ArtePiazza",
        categories: ["ArtePiazza遊戲"],
    },
    {
        aliases: ["Artificial Studios"],
        name: "Artificial Studios",
        page: "Artificial Studios",
        categories: ["Artificial Studios遊戲"],
    },
    {
        aliases: ["Artix Entertainment"],
        name: "Artix Entertainment",
        page: "Artix Entertainment",
        categories: ["Artix Entertainment遊戲"],
    },
    {
        aliases: ["artoon"],
        name: "Artoon",
        page: "Artoon",
        categories: ["Artoon遊戲"],
    },
    {
        aliases: ["Arush Entertainment"],
        name: "Arush Entertainment",
        page: "Arush Entertainment",
        categories: ["Arush Entertainment遊戲"],
    },
    {
        aliases: ["arzest"],
        name: "Arzest",
        page: "Arzest",
        categories: ["Arzest遊戲"],
    },
    {
        aliases: ["ascaron"],
        name: "Ascaron",
        page: "Ascaron",
        categories: ["Ascaron遊戲"],
    },
    {
        aliases: ["ASCII Corporation"],
        name: "ASCII Corporation",
        page: "ASCII Corporation",
        categories: ["ASCII Corporation遊戲"],
    },
    {
        aliases: ["asobo-studio", "Asobo Studio", "Asobo工作室"],
        name: "Asobo工作室",
        page: "Asobo工作室",
        categories: ["Asobo工作室遊戲"],
    },
    {
        aliases: ["asobu"],
        name: "Asobu",
        page: "Asobu",
        categories: ["Asobu遊戲"],
    },
    {
        aliases: ["Asphere Innovations"],
        name: "Asphere Innovations",
        page: "Asphere Innovations",
        categories: ["Asphere Innovations遊戲"],
    },
    {
        aliases: ["aspyr"],
        name: "Aspyr",
        page: "Aspyr",
        categories: ["Aspyr遊戲"],
    },
    {
        aliases: ["Astra Logical"],
        name: "Astra Logical",
        page: "Astra Logical",
        categories: ["Astra Logical遊戲"],
    },
    {
        aliases: ["astragon"],
        name: "Astragon",
        page: "Astragon",
        categories: ["Astragon遊戲"],
    },
    {
        aliases: ["atari-games", "Atari Games", "雅达利游戏"],
        name: "雅达利游戏",
        page: "雅达利游戏",
        categories: ["雅達利遊戲遊戲"],
        stubTags: ["Atari-stub"],
    },
    {
        aliases: ["atari-inc", "Atari, Inc.", "雅達利公司"],
        name: "雅達利公司",
        page: "雅達利公司",
        categories: ["雅達利公司遊戲"],
        stubTags: ["Atari-stub"],
    },
    {
        aliases: ["Atari, Inc. (formerly GT Interactive)"],
        name: "Atari, Inc. (formerly GT Interactive)",
        page: "Atari, Inc. (formerly GT Interactive)",
        categories: ["Atari, Inc. (formerly GT Interactive)遊戲"],
        stubTags: ["Atari-stub"],
    },
    {
        aliases: ["atari-sa", "Atari SA", "雅达利SA", "雅達利SA"],
        name: "雅達利SA",
        page: "雅達利SA",
        categories: ["雅達利SA遊戲"],
        stubTags: ["Atari-stub"],
    },
    {
        aliases: ["Ateam Inc."],
        name: "Ateam Inc.",
        page: "Ateam Inc.",
        categories: ["Ateam Inc.遊戲"],
    },
    {
        aliases: ["Atelier 801"],
        name: "Atelier 801",
        page: "Atelier 801",
        categories: ["Atelier 801遊戲"],
    },
    {
        aliases: ["Athena (game developer)"],
        name: "Athena (game developer)",
        page: "Athena (game developer)",
        categories: ["Athena (game developer)遊戲"],
    },
    {
        aliases: ["atlus"],
        name: "Atlus",
        page: "Atlus",
        categories: ["Atlus遊戲"],
    },
    {
        aliases: ["atod"],
        name: "Atod",
        page: "Atod",
        categories: ["Atod遊戲"],
    },
    {
        aliases: ["Atomic Games"],
        name: "Atomic Games",
        page: "Atomic Games",
        categories: ["Atomic Games遊戲"],
    },
    {
        aliases: ["Attic Entertainment Software"],
        name: "Attic Entertainment Software",
        page: "Attic Entertainment Software",
        categories: ["Attic Entertainment Software遊戲"],
    },
    {
        aliases: ["audiogaming"],
        name: "AudioGaming",
        page: "AudioGaming",
        categories: ["AudioGaming遊戲"],
    },
    {
        aliases: ["audiogenic"],
        name: "Audiogenic",
        page: "Audiogenic",
        categories: ["Audiogenic遊戲"],
    },
    {
        aliases: ["audiokinetic"],
        name: "Audiokinetic",
        page: "Audiokinetic",
        categories: ["Audiokinetic遊戲"],
    },
    {
        aliases: ["Auroch Digital"],
        name: "Auroch Digital",
        page: "Auroch Digital",
        categories: ["Auroch Digital遊戲"],
    },
    {
        aliases: ["Autumn Games"],
        name: "Autumn Games",
        page: "Autumn Games",
        categories: ["Autumn Games遊戲"],
    },
    {
        aliases: ["Avalanche Software"],
        name: "Avalanche Software",
        page: "Avalanche Software",
        categories: ["Avalanche Software遊戲"],
    },
    {
        aliases: [
            "avalanche-studios-group",
            "Avalanche Studios Group",
            "雪崩工作室集团",
            "雪崩工作室",
        ],
        name: "雪崩工作室",
        page: "雪崩工作室",
        categories: ["雪崩工作室集團遊戲"],
    },
    {
        aliases: ["Avalon Hill"],
        name: "Avalon Hill",
        page: "Avalon Hill",
        categories: ["Avalon Hill遊戲"],
    },
    {
        aliases: ["avantgarden"],
        name: "Avantgarden",
        page: "Avantgarden",
        categories: ["Avantgarden遊戲"],
    },
    {
        aliases: ["Avatar Reality"],
        name: "Avatar Reality",
        page: "Avatar Reality",
        categories: ["Avatar Reality遊戲"],
    },
    {
        aliases: ["Aventurine SA"],
        name: "Aventurine SA",
        page: "Aventurine SA",
        categories: ["Aventurine SA遊戲"],
    },
    {
        aliases: ["awem"],
        name: "Awem",
        page: "Awem",
        categories: ["Awem遊戲"],
    },
    {
        aliases: ["B2B Games"],
        name: "B2B Games",
        page: "B2B Games",
        categories: ["B2B Games遊戲"],
    },
    {
        aliases: ["Backbone Entertainment"],
        name: "Backbone Entertainment",
        page: "Backbone Entertainment",
        categories: ["Backbone Entertainment遊戲"],
    },
    {
        aliases: ["BAM! Entertainment"],
        name: "BAM! Entertainment",
        page: "BAM! Entertainment",
        categories: ["BAM! Entertainment遊戲"],
    },
    {
        aliases: ["bandai", "万代", "萬代"],
        name: "萬代",
        page: "萬代",
        categories: ["萬代遊戲"],
    },
    {
        aliases: [
            "bandai-namco-entertainment",
            "Bandai Namco Entertainment",
            "万代南梦宫娱乐",
        ],
        name: "万代南梦宫娱乐",
        page: "万代南梦宫娱乐",
        categories: ["萬代南夢宮遊戲"],
        stubTags: ["BandaiNamco-stub"],
    },
    {
        aliases: ["Bandai Namco Forge Digitals"],
        name: "Bandai Namco Forge Digitals",
        page: "Bandai Namco Forge Digitals",
        categories: ["萬代南夢宮遊戲"],
        stubTags: ["BandaiNamco-stub"],
    },
    {
        aliases: [
            "bandai-namco-studios",
            "Bandai Namco Studios",
            "万代南梦宫工作室",
        ],
        name: "万代南梦宫工作室",
        page: "万代南梦宫工作室",
        categories: ["萬代南夢宮遊戲"],
        stubTags: ["BandaiNamco-stub"],
    },
    {
        aliases: ["banpresto"],
        name: "Banpresto",
        page: "Banpresto",
        categories: ["Banpresto遊戲"],
    },
    {
        aliases: ["BAP Interactive"],
        name: "BAP Interactive",
        page: "BAP Interactive",
        categories: ["BAP Interactive遊戲"],
    },
    {
        aliases: ["Barking Lizards Technologies"],
        name: "Barking Lizards Technologies",
        page: "Barking Lizards Technologies",
        categories: ["Barking Lizards Technologies遊戲"],
    },
    {
        aliases: ["Battlefront.com"],
        name: "Battlefront.com",
        page: "Battlefront.com",
        categories: ["Battlefront.com遊戲"],
    },
    {
        aliases: ["Bauhaus Entertainment"],
        name: "Bauhaus Entertainment",
        page: "Bauhaus Entertainment",
        categories: ["Bauhaus Entertainment遊戲"],
    },
    {
        aliases: ["BBC Multimedia"],
        name: "BBC Multimedia",
        page: "BBC Multimedia",
        categories: ["BBC Multimedia遊戲"],
    },
    {
        aliases: ["Beach Bum Ltd."],
        name: "Beach Bum Ltd.",
        page: "Beach Bum Ltd.",
        categories: ["Beach Bum Ltd.遊戲"],
    },
    {
        aliases: ["Beachhead Studio"],
        name: "Beachhead Studio",
        page: "Beachhead Studio",
        categories: ["Beachhead Studio遊戲"],
    },
    {
        aliases: ["Beam Software"],
        name: "Beam Software",
        page: "Beam Software",
        categories: ["Beam Software遊戲"],
    },
    {
        aliases: ["beamdog"],
        name: "Beamdog",
        page: "Beamdog",
        categories: ["Beamdog遊戲"],
    },
    {
        aliases: ["beatshapers"],
        name: "Beatshapers",
        page: "Beatshapers",
        categories: ["Beatshapers遊戲"],
    },
    {
        aliases: ["beenox"],
        name: "Beenox",
        page: "Beenox",
        categories: ["Beenox遊戲"],
    },
    {
        aliases: ["Behaviour Interactive"],
        name: "Behaviour Interactive",
        page: "Behaviour Interactive",
        categories: ["Behaviour Interactive遊戲"],
    },
    {
        aliases: ["Behaviour Santiago"],
        name: "Behaviour Santiago",
        page: "Behaviour Santiago",
        categories: ["Behaviour Santiago遊戲"],
    },
    {
        aliases: ["Bend Studio"],
        name: "Bend Studio",
        page: "Bend Studio",
        categories: ["Bend Studio遊戲"],
    },
    {
        aliases: ["Berkeley Systems"],
        name: "Berkeley Systems",
        page: "Berkeley Systems",
        categories: ["Berkeley Systems遊戲"],
    },
    {
        aliases: ["betadwarf"],
        name: "BetaDwarf",
        page: "BetaDwarf",
        categories: ["BetaDwarf遊戲"],
    },
    {
        aliases: [
            "bethesda-game-studios",
            "Bethesda Game Studios",
            "贝塞斯达游戏工作室",
        ],
        name: "贝塞斯达游戏工作室",
        page: "贝塞斯达游戏工作室",
        categories: ["貝塞斯達遊戲工作室遊戲"],
    },
    {
        aliases: ["bethesda-softworks", "Bethesda Softworks", "贝塞斯达软件"],
        name: "贝塞斯达软件",
        page: "贝塞斯达软件",
        categories: ["貝塞斯達軟件遊戲"],
        stubTags: ["BethesdaSoftworks-stub"],
    },
    {
        aliases: ["Big Ant Studios"],
        name: "Big Ant Studios",
        page: "Big Ant Studios",
        categories: ["Big Ant Studios遊戲"],
    },
    {
        aliases: ["Big Blue Bubble"],
        name: "Big Blue Bubble",
        page: "Big Blue Bubble",
        categories: ["Big Blue Bubble遊戲"],
    },
    {
        aliases: ["Big Finish Games"],
        name: "Big Finish Games",
        page: "Big Finish Games",
        categories: ["Big Finish Games遊戲"],
    },
    {
        aliases: ["Big Fish Games"],
        name: "Big Fish Games",
        page: "Big Fish Games",
        categories: ["Big Fish Games遊戲"],
    },
    {
        aliases: ["Big Huge Games"],
        name: "Big Huge Games",
        page: "Big Huge Games",
        categories: ["Big Huge Games遊戲"],
    },
    {
        aliases: ["Big Red Software"],
        name: "Big Red Software",
        page: "Big Red Software",
        categories: ["Big Red Software遊戲"],
    },
    {
        aliases: ["Bigbig Studios"],
        name: "Bigbig Studios",
        page: "Bigbig Studios",
        categories: ["Bigbig Studios遊戲"],
    },
    {
        aliases: ["bigpoint"],
        name: "Bigpoint",
        page: "Bigpoint",
        categories: ["Bigpoint遊戲"],
    },
    {
        aliases: ["Birthday (company)"],
        name: "Birthday (company)",
        page: "Birthday (company)",
        categories: ["Birthday (company)遊戲"],
    },
    {
        aliases: ["Bit Corporation"],
        name: "Bit Corporation",
        page: "Bit Corporation",
        categories: ["Bit Corporation遊戲"],
    },
    {
        aliases: ["Bit Managers"],
        name: "Bit Managers",
        page: "Bit Managers",
        categories: ["Bit Managers遊戲"],
    },
    {
        aliases: ["Bits Studios"],
        name: "Bits Studios",
        page: "Bits Studios",
        categories: ["Bits Studios遊戲"],
    },
    {
        aliases: ["Bizarre Creations"],
        name: "Bizarre Creations",
        page: "Bizarre Creations",
        categories: ["Bizarre Creations遊戲"],
    },
    {
        aliases: [
            "black-forest-games",
            "Black Forest Games",
            "Black Forest游戏",
        ],
        name: "Black Forest游戏",
        page: "Black Forest游戏",
        categories: ["Black Forest遊戲遊戲"],
    },
    {
        aliases: ["Black Hole Entertainment"],
        name: "Black Hole Entertainment",
        page: "Black Hole Entertainment",
        categories: ["Black Hole Entertainment遊戲"],
    },
    {
        aliases: [
            "black-isle-studios",
            "Black Isle Studios",
            "黑岛工作室",
            "黑島工作室",
        ],
        name: "黑島工作室",
        page: "黑島工作室",
        categories: ["黑島工作室遊戲"],
    },
    {
        aliases: ["Black Legend (company)"],
        name: "Black Legend (company)",
        page: "Black Legend (company)",
        categories: ["Black Legend (company)遊戲"],
    },
    {
        aliases: ["Black Ops Entertainment"],
        name: "Black Ops Entertainment",
        page: "Black Ops Entertainment",
        categories: ["Black Ops Entertainment遊戲"],
    },
    {
        aliases: ["Black Rock Studio"],
        name: "Black Rock Studio",
        page: "Black Rock Studio",
        categories: ["Black Rock Studio遊戲"],
    },
    {
        aliases: ["Black Widow Games"],
        name: "Black Widow Games",
        page: "Black Widow Games",
        categories: ["Black Widow Games遊戲"],
    },
    {
        aliases: ["Blackbird Interactive"],
        name: "Blackbird Interactive",
        page: "Blackbird Interactive",
        categories: ["Blackbird Interactive遊戲"],
    },
    {
        aliases: ["Blendo Games"],
        name: "Blendo Games",
        page: "Blendo Games",
        categories: ["Blendo Games遊戲"],
    },
    {
        aliases: ["Blitz Games Studios"],
        name: "Blitz Games Studios",
        page: "Blitz Games Studios",
        categories: ["Blitz Games Studios遊戲"],
    },
    {
        aliases: ["Blizzard Albany"],
        name: "Blizzard Albany",
        page: "Blizzard Albany",
        categories: ["Blizzard Albany遊戲"],
    },
    {
        aliases: ["Blizzard Boston"],
        name: "Blizzard Boston",
        page: "Blizzard Boston",
        categories: ["Blizzard Boston遊戲"],
    },
    {
        aliases: [
            "blizzard-entertainment",
            "Blizzard Entertainment",
            "暴雪娱乐",
            "暴雪娛樂",
        ],
        name: "暴雪娛樂",
        page: "暴雪娛樂",
        categories: ["暴雪娛樂遊戲"],
        stubTags: ["BlizzardEntertainment-stub"],
    },
    {
        aliases: ["blizzard-north", "Blizzard North", "暴雪北方"],
        name: "暴雪北方",
        page: "暴雪北方",
        categories: ["暴雪北方遊戲"],
    },
    {
        aliases: ["Bloober Team"],
        name: "Bloober Team",
        page: "Bloober Team",
        categories: ["Bloober Team遊戲"],
    },
    {
        aliases: ["Blue Fang Games"],
        name: "Blue Fang Games",
        page: "Blue Fang Games",
        categories: ["Blue Fang Games遊戲"],
    },
    {
        aliases: ["Blue Planet Software"],
        name: "Blue Planet Software",
        page: "Blue Planet Software",
        categories: ["Blue Planet Software遊戲"],
    },
    {
        aliases: ["Blue Ribbon (software house)"],
        name: "Blue Ribbon (software house)",
        page: "Blue Ribbon (software house)",
        categories: ["Blue Ribbon (software house)遊戲"],
    },
    {
        aliases: ["Blue Sky Rangers"],
        name: "Blue Sky Rangers",
        page: "Blue Sky Rangers",
        categories: ["Blue Sky Rangers遊戲"],
    },
    {
        aliases: ["Blue Tea Games"],
        name: "Blue Tea Games",
        page: "Blue Tea Games",
        categories: ["Blue Tea Games遊戲"],
    },
    {
        aliases: ["Blue Tongue Entertainment"],
        name: "Blue Tongue Entertainment",
        page: "Blue Tongue Entertainment",
        categories: ["Blue Tongue Entertainment遊戲"],
    },
    {
        aliases: ["Blue Wizard Digital"],
        name: "Blue Wizard Digital",
        page: "Blue Wizard Digital",
        categories: ["Blue Wizard Digital遊戲"],
    },
    {
        aliases: ["bluepoint-games", "Bluepoint Games", "蓝点游戏工作室"],
        name: "蓝点游戏工作室",
        page: "蓝点游戏工作室",
        categories: ["藍點遊戲工作室遊戲"],
    },
    {
        aliases: ["BlueSky Software"],
        name: "BlueSky Software",
        page: "BlueSky Software",
        categories: ["BlueSky Software遊戲"],
    },
    {
        aliases: ["Blumhouse Games"],
        name: "Blumhouse Games",
        page: "Blumhouse Games",
        categories: ["Blumhouse Games遊戲"],
    },
    {
        aliases: ["Boffo Games"],
        name: "Boffo Games",
        page: "Boffo Games",
        categories: ["Boffo Games遊戲"],
    },
    {
        aliases: [
            "bohemia-interactive",
            "Bohemia Interactive",
            "波希米亚互动",
            "波希米亞互動工作室",
        ],
        name: "波希米亞互動工作室",
        page: "波希米亞互動工作室",
        categories: ["波希米亞互動遊戲"],
    },
    {
        aliases: ["boneloaf"],
        name: "Boneloaf",
        page: "Boneloaf",
        categories: ["Boneloaf遊戲"],
    },
    {
        aliases: ["Bonfire Studios"],
        name: "Bonfire Studios",
        page: "Bonfire Studios",
        categories: ["Bonfire Studios遊戲"],
    },
    {
        aliases: ["bongfish"],
        name: "Bongfish",
        page: "Bongfish",
        categories: ["Bongfish遊戲"],
    },
    {
        aliases: ["Brace Yourself Games"],
        name: "Brace Yourself Games",
        page: "Brace Yourself Games",
        categories: ["Brace Yourself Games遊戲"],
    },
    {
        aliases: ["Brash Entertainment"],
        name: "Brash Entertainment",
        page: "Brash Entertainment",
        categories: ["Brash Entertainment遊戲"],
    },
    {
        aliases: ["broderbund", "Brøderbund"],
        name: "Brøderbund",
        page: "Brøderbund",
        categories: ["Brøderbund遊戲"],
    },
    {
        aliases: ["Broken Rules"],
        name: "Broken Rules",
        page: "Broken Rules",
        categories: ["Broken Rules遊戲"],
    },
    {
        aliases: ["bug-byte"],
        name: "Bug-Byte",
        page: "Bug-Byte",
        categories: ["Bug-Byte遊戲"],
    },
    {
        aliases: ["Buka Entertainment"],
        name: "Buka Entertainment",
        page: "Buka Entertainment",
        categories: ["Buka Entertainment遊戲"],
    },
    {
        aliases: ["bulkypix"],
        name: "BulkyPix",
        page: "BulkyPix",
        categories: ["BulkyPix遊戲"],
    },
    {
        aliases: ["bungie"],
        name: "Bungie",
        page: "Bungie",
        categories: ["Bungie遊戲"],
    },
    {
        aliases: ["bushiroad", "武士道"],
        name: "武士道",
        page: "武士道",
        categories: ["武士道遊戲"],
    },
    {
        aliases: ["c-and-e", "C&E"],
        name: "C&E",
        page: "C&E",
        categories: ["C&E遊戲"],
    },
    {
        aliases: ["camerica"],
        name: "Camerica",
        page: "Camerica",
        categories: ["Camerica遊戲"],
    },
    {
        aliases: ["capcom", "卡普空"],
        name: "卡普空",
        page: "卡普空",
        categories: ["卡普空遊戲"],
        stubTags: ["Capcom-stub"],
    },
    {
        aliases: ["Capstone Software"],
        name: "Capstone Software",
        page: "Capstone Software",
        categories: ["Capstone Software遊戲"],
    },
    {
        aliases: ["Cavedog Entertainment"],
        name: "Cavedog Entertainment",
        page: "Cavedog Entertainment",
        categories: ["Cavedog Entertainment遊戲"],
    },
    {
        aliases: ["CD Projekt"],
        name: "CD Projekt",
        page: "CD Projekt",
        categories: ["CD Projekt遊戲"],
    },
    {
        aliases: ["CDC Games"],
        name: "CDC Games",
        page: "CDC Games",
        categories: ["CDC Games遊戲"],
    },
    {
        aliases: ["CDP.pl"],
        name: "CDP.pl",
        page: "CDP.pl",
        categories: ["CDP.pl遊戲"],
    },
    {
        aliases: ["CDS Software"],
        name: "CDS Software",
        page: "CDS Software",
        categories: ["CDS Software遊戲"],
    },
    {
        aliases: ["CDV Software"],
        name: "CDV Software",
        page: "CDV Software",
        categories: ["CDV Software遊戲"],
    },
    {
        aliases: ["centuri"],
        name: "Centuri",
        page: "Centuri",
        categories: ["Centuri遊戲"],
    },
    {
        aliases: ["championsoft"],
        name: "ChampionSoft",
        page: "ChampionSoft",
        categories: ["ChampionSoft遊戲"],
    },
    {
        aliases: ["chucklefish"],
        name: "Chucklefish",
        page: "Chucklefish",
        categories: ["Chucklefish遊戲"],
    },
    {
        aliases: ["Chunsoft Co., Ltd."],
        name: "Chunsoft Co., Ltd.",
        page: "Chunsoft Co., Ltd.",
        categories: ["Chunsoft Co., Ltd.遊戲"],
    },
    {
        aliases: ["CI Games"],
        name: "CI Games",
        page: "CI Games",
        categories: ["CI Games遊戲"],
    },
    {
        aliases: ["CM Games"],
        name: "CM Games",
        page: "CM Games",
        categories: ["CM Games遊戲"],
    },
    {
        aliases: ["codemasters"],
        name: "Codemasters",
        page: "Codemasters",
        categories: ["Codemasters遊戲"],
    },
    {
        aliases: ["Coffee Stain Studios"],
        name: "Coffee Stain Studios",
        page: "Coffee Stain Studios",
        categories: ["Coffee Stain Studios遊戲"],
    },
    {
        aliases: ["Collavier Corporation"],
        name: "Collavier Corporation",
        page: "Collavier Corporation",
        categories: ["Collavier Corporation遊戲"],
    },
    {
        aliases: ["Conspiracy Entertainment"],
        name: "Conspiracy Entertainment",
        page: "Conspiracy Entertainment",
        categories: ["Conspiracy Entertainment遊戲"],
    },
    {
        aliases: ["Core Design"],
        name: "Core Design",
        page: "Core Design",
        categories: ["Core Design遊戲"],
    },
    {
        aliases: ["Crave Entertainment"],
        name: "Crave Entertainment",
        page: "Crave Entertainment",
        categories: ["Crave Entertainment遊戲"],
    },
    {
        aliases: ["Creat Studios"],
        name: "Creat Studios",
        page: "Creat Studios",
        categories: ["Creat Studios遊戲"],
    },
    {
        aliases: [
            "creative-assembly",
            "Creative Assembly",
            "The Creative Assembly",
        ],
        name: "The Creative Assembly",
        page: "The Creative Assembly",
        categories: ["The Creative Assembly遊戲"],
    },
    {
        aliases: ["CreativeForge Games"],
        name: "CreativeForge Games",
        page: "CreativeForge Games",
        categories: ["CreativeForge Games遊戲"],
    },
    {
        aliases: ["Criterion Games"],
        name: "Criterion Games",
        page: "Criterion Games",
        categories: ["Criterion Games遊戲"],
    },
    {
        aliases: ["Critical Gameplay"],
        name: "Critical Gameplay",
        page: "Critical Gameplay",
        categories: ["Critical Gameplay遊戲"],
    },
    {
        aliases: ["Critical Reflex"],
        name: "Critical Reflex",
        page: "Critical Reflex",
        categories: ["Critical Reflex遊戲"],
    },
    {
        aliases: ["CRL Group"],
        name: "CRL Group",
        page: "CRL Group",
        categories: ["CRL Group遊戲"],
    },
    {
        aliases: ["Cryo Interactive"],
        name: "Cryo Interactive",
        page: "Cryo Interactive",
        categories: ["Cryo Interactive遊戲"],
    },
    {
        aliases: ["Crystal Computing"],
        name: "Crystal Computing",
        page: "Crystal Computing",
        categories: ["Crystal Computing遊戲"],
    },
    {
        aliases: ["crystal-dynamics", "Crystal Dynamics", "晶体动力"],
        name: "晶体动力",
        page: "晶体动力",
        categories: ["晶體動力遊戲"],
    },
    {
        aliases: ["crytek"],
        name: "Crytek",
        page: "Crytek",
        categories: ["Crytek遊戲"],
    },
    {
        aliases: ["crytivo"],
        name: "Crytivo",
        page: "Crytivo",
        categories: ["Crytivo遊戲"],
    },
    {
        aliases: ["Culture Brain"],
        name: "Culture Brain",
        page: "Culture Brain",
        categories: ["Culture Brain遊戲"],
    },
    {
        aliases: ["Curve Games"],
        name: "Curve Games",
        page: "Curve Games",
        categories: ["Curve Games遊戲"],
    },
    {
        aliases: ["cyan-worlds", "Cyan Worlds", "Cyan"],
        name: "Cyan",
        page: "Cyan",
        categories: ["Cyan遊戲"],
    },
    {
        aliases: ["cyberagent"],
        name: "CyberAgent",
        page: "CyberAgent",
        categories: ["CyberAgent遊戲"],
    },
    {
        aliases: ["cyberconnect2"],
        name: "CyberConnect2",
        page: "CyberConnect2",
        categories: ["CyberConnect2遊戲"],
    },
    {
        aliases: ["Cybersoft (video game company)"],
        name: "Cybersoft (video game company)",
        page: "Cybersoft (video game company)",
        categories: ["Cybersoft (video game company)遊戲"],
    },
    {
        aliases: ["cyberstep"],
        name: "CyberStep",
        page: "CyberStep",
        categories: ["CyberStep遊戲"],
    },
    {
        aliases: ["D3 Publisher"],
        name: "D3 Publisher",
        page: "D3 Publisher",
        categories: ["D3 Publisher遊戲"],
    },
    {
        aliases: ["D4 Enterprise"],
        name: "D4 Enterprise",
        page: "D4 Enterprise",
        categories: ["D4 Enterprise遊戲"],
    },
    {
        aliases: ["Daedalic Entertainment"],
        name: "Daedalic Entertainment",
        page: "Daedalic Entertainment",
        categories: ["Daedalic Entertainment遊戲"],
    },
    {
        aliases: ["Dark Energy Digital"],
        name: "Dark Energy Digital",
        page: "Dark Energy Digital",
        categories: ["Dark Energy Digital遊戲"],
    },
    {
        aliases: ["Datcroft Games"],
        name: "Datcroft Games",
        page: "Datcroft Games",
        categories: ["Datcroft Games遊戲"],
    },
    {
        aliases: [
            "daybreak-game-company",
            "Daybreak Game Company",
            "黎明游戏公司",
        ],
        name: "黎明游戏公司",
        page: "黎明游戏公司",
        categories: ["黎明遊戲公司遊戲"],
    },
    {
        aliases: ["db-soft"],
        name: "DB-SOFT",
        page: "DB-SOFT",
        categories: ["DB-SOFT遊戲"],
    },
    {
        aliases: ["Dear Villagers"],
        name: "Dear Villagers",
        page: "Dear Villagers",
        categories: ["Dear Villagers遊戲"],
    },
    {
        aliases: ["Deca Games"],
        name: "Deca Games",
        page: "Deca Games",
        categories: ["Deca Games遊戲"],
    },
    {
        aliases: ["deck13"],
        name: "Deck13",
        page: "Deck13",
        categories: ["Deck13遊戲"],
    },
    {
        aliases: ["Deep Silver"],
        name: "Deep Silver",
        page: "Deep Silver",
        categories: ["Deep Silver遊戲"],
    },
    {
        aliases: ["Delta Tao Software"],
        name: "Delta Tao Software",
        page: "Delta Tao Software",
        categories: ["Delta Tao Software遊戲"],
    },
    {
        aliases: ["dena"],
        name: "DeNA",
        page: "DeNA",
        categories: ["DeNA遊戲"],
    },
    {
        aliases: ["Desk Plant"],
        name: "Desk Plant",
        page: "Desk Plant",
        categories: ["Desk Plant遊戲"],
    },
    {
        aliases: ["destineer"],
        name: "Destineer",
        page: "Destineer",
        categories: ["Destineer遊戲"],
    },
    {
        aliases: ["Devolver Digital"],
        name: "Devolver Digital",
        page: "Devolver Digital",
        categories: ["Devolver Digital遊戲"],
    },
    {
        aliases: ["Digital Bros"],
        name: "Digital Bros",
        page: "Digital Bros",
        categories: ["Digital Bros遊戲"],
    },
    {
        aliases: ["Digital Extremes"],
        name: "Digital Extremes",
        page: "Digital Extremes",
        categories: ["Digital Extremes遊戲"],
    },
    {
        aliases: ["Digital Happiness"],
        name: "Digital Happiness",
        page: "Digital Happiness",
        categories: ["Digital Happiness遊戲"],
    },
    {
        aliases: [
            "digital-illusions-ce",
            "Digital Illusions CE",
            "EA Digital Illusions CE",
        ],
        name: "EA Digital Illusions CE",
        page: "EA Digital Illusions CE",
        categories: ["EA Digital Illusions CE遊戲"],
        stubTags: ["ElectronicArts-stub"],
    },
    {
        aliases: ["Digital Jesters"],
        name: "Digital Jesters",
        page: "Digital Jesters",
        categories: ["Digital Jesters遊戲"],
    },
    {
        aliases: ["Digital Leisure"],
        name: "Digital Leisure",
        page: "Digital Leisure",
        categories: ["Digital Leisure遊戲"],
    },
    {
        aliases: ["Dimple Entertainment"],
        name: "Dimple Entertainment",
        page: "Dimple Entertainment",
        categories: ["Dimple Entertainment遊戲"],
    },
    {
        aliases: ["Disney Consumer Products"],
        name: "Disney Consumer Products",
        page: "Disney Consumer Products",
        categories: ["Disney Consumer Products遊戲"],
    },
    {
        aliases: ["Disney Interactive"],
        name: "Disney Interactive",
        page: "Disney Interactive",
        categories: ["Disney Interactive遊戲"],
        stubTags: ["Disney-videogame-stub"],
    },
    {
        aliases: [
            "disney-interactive-studios",
            "Disney Interactive Studios",
            "迪士尼互动工作室",
        ],
        name: "迪士尼互动工作室",
        page: "迪士尼互动工作室",
        categories: ["迪士尼互動工作室遊戲"],
        stubTags: ["Disney-videogame-stub"],
    },
    {
        aliases: ["DMM.com"],
        name: "DMM.com",
        page: "DMM.com",
        categories: ["DMM.com遊戲"],
    },
    {
        aliases: [
            "dontnod-entertainment",
            "Dontnod Entertainment",
            "Don't Nod",
        ],
        name: "Don't Nod",
        page: "Don't Nod",
        categories: ["Don't Nod遊戲"],
    },
    {
        aliases: ["dotemu"],
        name: "Dotemu",
        page: "Dotemu",
        categories: ["Dotemu遊戲"],
    },
    {
        aliases: ["Double Eleven (company)"],
        name: "Double Eleven (company)",
        page: "Double Eleven (company)",
        categories: ["Double Eleven (company)遊戲"],
    },
    {
        aliases: ["double-fine", "Double Fine", "Double Fine Productions"],
        name: "Double Fine Productions",
        page: "Double Fine Productions",
        categories: ["Double Fine Productions遊戲"],
    },
    {
        aliases: ["Dovetail Games"],
        name: "Dovetail Games",
        page: "Dovetail Games",
        categories: ["Dovetail Games遊戲"],
    },
    {
        aliases: ["Dragonfly (company)"],
        name: "Dragonfly (company)",
        page: "Dragonfly (company)",
        categories: ["Dragonfly (company)遊戲"],
    },
    {
        aliases: ["DreamCatcher Interactive"],
        name: "DreamCatcher Interactive",
        page: "DreamCatcher Interactive",
        categories: ["DreamCatcher Interactive遊戲"],
    },
    {
        aliases: ["dreamhaven"],
        name: "Dreamhaven",
        page: "Dreamhaven",
        categories: ["Dreamhaven遊戲"],
    },
    {
        aliases: ["drecom"],
        name: "Drecom",
        page: "Drecom",
        categories: ["Drecom遊戲"],
    },
    {
        aliases: ["drosoft"],
        name: "DROsoft",
        page: "DROsoft",
        categories: ["DROsoft遊戲"],
    },
    {
        aliases: ["DSI Games"],
        name: "DSI Games",
        page: "DSI Games",
        categories: ["DSI Games遊戲"],
    },
    {
        aliases: ["DTP Entertainment"],
        name: "DTP Entertainment",
        page: "DTP Entertainment",
        categories: ["DTP Entertainment遊戲"],
    },
    {
        aliases: ["Duoyi Network"],
        name: "Duoyi Network",
        page: "Duoyi Network",
        categories: ["Duoyi Network遊戲"],
    },
    {
        aliases: ["EA Canada"],
        name: "EA Canada",
        page: "EA Canada",
        categories: ["EA Canada遊戲"],
        stubTags: ["ElectronicArts-stub"],
    },
    {
        aliases: ["EA Digital Illusions CE"],
        name: "EA Digital Illusions CE",
        page: "EA Digital Illusions CE",
        categories: ["EA Digital Illusions CE遊戲"],
        stubTags: ["ElectronicArts-stub"],
    },
    {
        aliases: ["eastasiasoft"],
        name: "Eastasiasoft",
        page: "Eastasiasoft",
        categories: ["Eastasiasoft遊戲"],
    },
    {
        aliases: ["Edge Games"],
        name: "Edge Games",
        page: "Edge Games",
        categories: ["Edge Games遊戲"],
    },
    {
        aliases: ["edmark"],
        name: "Edmark",
        page: "Edmark",
        categories: ["Edmark遊戲"],
    },
    {
        aliases: ["EGames (video game developer)"],
        name: "EGames (video game developer)",
        page: "EGames (video game developer)",
        categories: ["EGames (video game developer)遊戲"],
    },
    {
        aliases: [
            "eidos-montr-al",
            "Eidos-Montréal",
            "Eidos蒙特利尔",
            "艺夺蒙特利尔",
        ],
        name: "艺夺蒙特利尔",
        page: "艺夺蒙特利尔",
        categories: ["Eidos蒙特利爾遊戲"],
        stubTags: ["Eidos-stub"],
    },
    {
        aliases: ["Electric Dreams Software"],
        name: "Electric Dreams Software",
        page: "Electric Dreams Software",
        categories: ["Electric Dreams Software遊戲"],
    },
    {
        aliases: ["Electro Brain"],
        name: "Electro Brain",
        page: "Electro Brain",
        categories: ["Electro Brain遊戲"],
    },
    {
        aliases: ["electronic-arts", "Electronic Arts", "艺电"],
        name: "艺电",
        page: "艺电",
        categories: ["藝電遊戲"],
        stubTags: ["ElectronicArts-stub"],
    },
    {
        aliases: ["Elite Systems"],
        name: "Elite Systems",
        page: "Elite Systems",
        categories: ["Elite Systems遊戲"],
    },
    {
        aliases: ["Empire Interactive"],
        name: "Empire Interactive",
        page: "Empire Interactive",
        categories: ["Empire Interactive遊戲"],
    },
    {
        aliases: ["En Masse Entertainment"],
        name: "En Masse Entertainment",
        page: "En Masse Entertainment",
        categories: ["En Masse Entertainment遊戲"],
    },
    {
        aliases: ["Encore, Inc."],
        name: "Encore, Inc.",
        page: "Encore, Inc.",
        categories: ["Encore, Inc.遊戲"],
    },
    {
        aliases: ["enix", "艾尼克斯"],
        name: "艾尼克斯",
        page: "艾尼克斯",
        categories: ["艾尼克斯遊戲"],
    },
    {
        aliases: ["Enlight Software"],
        name: "Enlight Software",
        page: "Enlight Software",
        categories: ["Enlight Software遊戲"],
    },
    {
        aliases: ["Ensemble Studios"],
        name: "Ensemble Studios",
        page: "Ensemble Studios",
        categories: ["Ensemble Studios遊戲"],
    },
    {
        aliases: ["Entertainment Software Publishing"],
        name: "Entertainment Software Publishing",
        page: "Entertainment Software Publishing",
        categories: ["Entertainment Software Publishing遊戲"],
    },
    {
        aliases: ["Eon Digital Entertainment"],
        name: "Eon Digital Entertainment",
        page: "Eon Digital Entertainment",
        categories: ["Eon Digital Entertainment遊戲"],
    },
    {
        aliases: ["Epic Games"],
        name: "Epic Games",
        page: "Epic Games",
        categories: ["Epic Games遊戲"],
    },
    {
        aliases: ["Epic Records Japan"],
        name: "Epic Records Japan",
        page: "Epic Records Japan",
        categories: ["Epic Records Japan遊戲"],
    },
    {
        aliases: ["europress"],
        name: "Europress",
        page: "Europress",
        categories: ["Europress遊戲"],
    },
    {
        aliases: ["examu"],
        name: "Examu",
        page: "Examu",
        categories: ["Examu遊戲"],
    },
    {
        aliases: ["Facepunch Studios"],
        name: "Facepunch Studios",
        page: "Facepunch Studios",
        categories: ["Facepunch Studios遊戲"],
    },
    {
        aliases: ["Family Soft"],
        name: "Family Soft",
        page: "Family Soft",
        categories: ["Family Soft遊戲"],
    },
    {
        aliases: ["Faster Than Light (software publisher)"],
        name: "Faster Than Light (software publisher)",
        page: "Faster Than Light (software publisher)",
        categories: ["Faster Than Light (software publisher)遊戲"],
    },
    {
        aliases: ["fathammer"],
        name: "Fathammer",
        page: "Fathammer",
        categories: ["Fathammer遊戲"],
    },
    {
        aliases: ["Fellow Traveller Games"],
        name: "Fellow Traveller Games",
        page: "Fellow Traveller Games",
        categories: ["Fellow Traveller Games遊戲"],
    },
    {
        aliases: ["Feral Interactive"],
        name: "Feral Interactive",
        page: "Feral Interactive",
        categories: ["Feral Interactive遊戲"],
    },
    {
        aliases: ["Fictions (company)"],
        name: "Fictions (company)",
        page: "Fictions (company)",
        categories: ["Fictions (company)遊戲"],
    },
    {
        aliases: ["fill-in-cafe"],
        name: "Fill-in-Cafe",
        page: "Fill-in-Cafe",
        categories: ["Fill-in-Cafe遊戲"],
    },
    {
        aliases: ["finji"],
        name: "Finji",
        page: "Finji",
        categories: ["Finji遊戲"],
    },
    {
        aliases: ["Firaxis Games"],
        name: "Firaxis Games",
        page: "Firaxis Games",
        categories: ["Firaxis Games遊戲"],
    },
    {
        aliases: ["Firemonkeys Studios"],
        name: "Firemonkeys Studios",
        page: "Firemonkeys Studios",
        categories: ["Firemonkeys Studios遊戲"],
    },
    {
        aliases: ["fishlabs"],
        name: "Fishlabs",
        page: "Fishlabs",
        categories: ["Fishlabs遊戲"],
    },
    {
        aliases: ["flazm"],
        name: "Flazm",
        page: "Flazm",
        categories: ["Flazm遊戲"],
    },
    {
        aliases: ["Focus Entertainment"],
        name: "Focus Entertainment",
        page: "Focus Entertainment",
        categories: ["Focus娛樂遊戲"],
    },
    {
        aliases: ["Fox Digital Entertainment"],
        name: "Fox Digital Entertainment",
        page: "Fox Digital Entertainment",
        categories: ["Fox Digital Entertainment遊戲"],
    },
    {
        aliases: ["Fox Interactive"],
        name: "Fox Interactive",
        page: "Fox Interactive",
        categories: ["Fox Interactive遊戲"],
    },
    {
        aliases: ["foxnext"],
        name: "FoxNext",
        page: "FoxNext",
        categories: ["FoxNext遊戲"],
    },
    {
        aliases: ["Freeverse Inc."],
        name: "Freeverse Inc.",
        page: "Freeverse Inc.",
        categories: ["Freeverse Inc.遊戲"],
    },
    {
        aliases: ["fromsoftware"],
        name: "FromSoftware",
        page: "FromSoftware",
        categories: ["FromSoftware遊戲"],
    },
    {
        aliases: ["Frontier Developments"],
        name: "Frontier Developments",
        page: "Frontier Developments",
        categories: ["Frontier Developments遊戲"],
    },
    {
        aliases: ["FTX Games"],
        name: "FTX Games",
        page: "FTX Games",
        categories: ["FTX Games遊戲"],
    },
    {
        aliases: ["funcom"],
        name: "Funcom",
        page: "Funcom",
        categories: ["Funcom遊戲"],
    },
    {
        aliases: ["funplus"],
        name: "FunPlus",
        page: "FunPlus",
        categories: ["FunPlus遊戲"],
    },
    {
        aliases: ["furyu"],
        name: "FuRyu",
        page: "FuRyu",
        categories: ["FuRyu遊戲"],
    },
    {
        aliases: ["gaelco"],
        name: "Gaelco",
        page: "Gaelco",
        categories: ["Gaelco遊戲"],
    },
    {
        aliases: ["Gaijin Entertainment"],
        name: "Gaijin Entertainment",
        page: "Gaijin Entertainment",
        categories: ["Gaijin Entertainment遊戲"],
    },
    {
        aliases: ["Game Freak"],
        name: "GAME FREAK",
        page: "GAME FREAK",
        categories: ["GAME FREAK遊戲"],
    },
    {
        aliases: ["gamehouse"],
        name: "GameHouse",
        page: "GameHouse",
        categories: ["GameHouse遊戲"],
    },
    {
        aliases: ["gameloft"],
        name: "Gameloft",
        page: "Gameloft",
        categories: ["Gameloft遊戲"],
    },
    {
        aliases: ["gamevil"],
        name: "Gamevil",
        page: "Gamevil",
        categories: ["Gamevil遊戲"],
    },
    {
        aliases: ["Gearbox Software"],
        name: "Gearbox Software",
        page: "Gearbox Software",
        categories: ["Gearbox Software遊戲"],
    },
    {
        aliases: [".Gears"],
        name: ".Gears",
        page: ".Gears",
        categories: [".Gears遊戲"],
    },
    {
        aliases: ["Giant Sparrow"],
        name: "Giant Sparrow",
        page: "Giant Sparrow",
        categories: ["Giant Sparrow遊戲"],
    },
    {
        aliases: ["Glu Mobile"],
        name: "Glu Mobile",
        page: "Glu Mobile",
        categories: ["Glu Mobile遊戲"],
    },
    {
        aliases: ["good-feel"],
        name: "Good-Feel",
        page: "Good-Feel",
        categories: ["Good-Feel遊戲"],
    },
    {
        aliases: ["Grasshopper Manufacture"],
        name: "Grasshopper Manufacture",
        page: "Grasshopper Manufacture",
        categories: ["Grasshopper Manufacture遊戲"],
    },
    {
        aliases: ["Grinding Gear Games"],
        name: "Grinding Gear Games",
        page: "Grinding Gear Games",
        categories: ["Grinding Gear Games遊戲"],
    },
    {
        aliases: ["GSC Game World"],
        name: "GSC Game World",
        page: "GSC Game World",
        categories: ["GSC Game World遊戲"],
    },
    {
        aliases: ["Guerrilla Games"],
        name: "Guerrilla Games",
        page: "Guerrilla Games",
        categories: ["Guerrilla Games遊戲"],
    },
    {
        aliases: ["GungHo Online Entertainment"],
        name: "GungHo Online Entertainment",
        page: "GungHo Online Entertainment",
        categories: ["GungHo Online Entertainment遊戲"],
    },
    {
        aliases: ["hal-laboratory", "HAL Laboratory", "HAL研究所"],
        name: "HAL研究所",
        page: "HAL研究所",
        categories: ["HAL研究所遊戲"],
    },
    {
        aliases: ["harmonix"],
        name: "Harmonix",
        page: "Harmonix",
        categories: ["Harmonix遊戲"],
    },
    {
        aliases: ["Hasbro Interactive"],
        name: "Hasbro Interactive",
        page: "Hasbro Interactive",
        categories: ["Hasbro Interactive遊戲"],
    },
    {
        aliases: ["High Moon Studios"],
        name: "High Moon Studios",
        page: "High Moon Studios",
        categories: ["High Moon Studios遊戲"],
    },
    {
        aliases: ["id Software"],
        name: "id Software",
        page: "id Software",
        categories: ["id Software遊戲"],
        stubTags: ["idSoftware-stub"],
    },
    {
        aliases: ["Idea Factory"],
        name: "Idea Factory",
        page: "Idea Factory",
        categories: ["Idea Factory遊戲"],
    },
    {
        aliases: ["Infinity Ward"],
        name: "Infinity Ward",
        page: "Infinity Ward",
        categories: ["Infinity Ward遊戲"],
    },
    {
        aliases: ["infogrames"],
        name: "Infogrames",
        page: "Infogrames",
        categories: ["Infogrames遊戲"],
    },
    {
        aliases: ["Insomniac Games"],
        name: "Insomniac Games",
        page: "Insomniac Games",
        categories: ["Insomniac Games遊戲"],
    },
    {
        aliases: ["Intelligent Systems"],
        name: "Intelligent Systems",
        page: "Intelligent Systems",
        categories: ["Intelligent Systems遊戲"],
    },
    {
        aliases: ["Interplay Entertainment"],
        name: "Interplay Entertainment",
        page: "Interplay Entertainment",
        categories: ["Interplay Entertainment遊戲"],
    },
    {
        aliases: ["IO Interactive"],
        name: "IO Interactive",
        page: "IO Interactive",
        categories: ["IO Interactive遊戲"],
    },
    {
        aliases: ["irem"],
        name: "Irem",
        page: "Irem",
        categories: ["Irem遊戲"],
    },
    {
        aliases: ["Iron Galaxy"],
        name: "Iron Galaxy",
        page: "Iron Galaxy",
        categories: ["Iron Galaxy遊戲"],
    },
    {
        aliases: ["Irrational Games"],
        name: "Irrational Games",
        page: "Irrational Games",
        categories: ["Irrational Games遊戲"],
    },
    {
        aliases: ["jagex"],
        name: "Jagex",
        page: "Jagex",
        categories: ["Jagex遊戲"],
    },
    {
        aliases: ["jaleco"],
        name: "Jaleco",
        page: "Jaleco",
        categories: ["Jaleco遊戲"],
    },
    {
        aliases: ["JoWooD Entertainment"],
        name: "JoWooD Entertainment",
        page: "JoWooD Entertainment",
        categories: ["JoWooD Entertainment遊戲"],
    },
    {
        aliases: ["Kalypso Media"],
        name: "Kalypso Media",
        page: "Kalypso Media",
        categories: ["Kalypso Media遊戲"],
    },
    {
        aliases: ["Klei Entertainment"],
        name: "Klei Entertainment",
        page: "Klei Entertainment",
        categories: ["Klei Entertainment遊戲"],
    },
    {
        aliases: ["koei", "光荣", "光荣 (企业)"],
        name: "光荣 (企业)",
        page: "光荣 (企业)",
        categories: ["光榮遊戲"],
    },
    {
        aliases: ["koei-tecmo", "Koei Tecmo", "光荣特库摩"],
        name: "光荣特库摩",
        page: "光荣特库摩",
        categories: ["光榮特庫摩遊戲"],
    },
    {
        aliases: ["konami", "科乐美", "科樂美"],
        name: "科樂美",
        page: "科樂美",
        categories: ["科樂美遊戲"],
        stubTags: ["Konami-stub"],
    },
    {
        aliases: ["kuro-games", "Kuro Games", "库洛游戏", "庫洛遊戲"],
        name: "庫洛遊戲",
        page: "庫洛遊戲",
        categories: ["庫洛遊戲遊戲"],
    },
    {
        aliases: ["larian-studios", "Larian Studios", "拉瑞安工作室"],
        name: "拉瑞安工作室",
        page: "拉瑞安工作室",
        categories: ["拉瑞安工作室遊戲"],
    },
    {
        aliases: ["level-5-company", "Level-5 (company)", "LEVEL-5"],
        name: "LEVEL-5",
        page: "LEVEL-5",
        categories: ["LEVEL-5遊戲"],
    },
    {
        aliases: ["Lionhead Studios"],
        name: "Lionhead Studios",
        page: "Lionhead Studios",
        categories: ["Lionhead Studios遊戲"],
    },
    {
        aliases: ["lucasarts", "卢卡斯艺术"],
        name: "卢卡斯艺术",
        page: "卢卡斯艺术",
        categories: ["盧卡斯藝術遊戲"],
    },
    {
        aliases: ["machinegames"],
        name: "MachineGames",
        page: "MachineGames",
        categories: ["MachineGames遊戲"],
    },
    {
        aliases: ["mages-company", "Mages (company)", "MAGES."],
        name: "MAGES.",
        page: "MAGES.",
        categories: ["MAGES.遊戲"],
    },
    {
        aliases: ["Majesco Entertainment"],
        name: "Majesco Entertainment",
        page: "Majesco Entertainment",
        categories: ["Majesco Entertainment遊戲"],
    },
    {
        aliases: ["marvelous-company", "Marvelous (company)", "Marvelous"],
        name: "Marvelous",
        page: "Marvelous",
        categories: ["Marvelous遊戲"],
    },
    {
        aliases: ["microprose"],
        name: "MicroProse",
        page: "MicroProse",
        categories: ["MicroProse遊戲"],
    },
    {
        aliases: ["Microsoft Gaming"],
        name: "Microsoft Gaming",
        page: "Microsoft Gaming",
        categories: ["Microsoft Gaming遊戲"],
    },
    {
        aliases: ["Midway Games"],
        name: "Midway Games",
        page: "Midway Games",
        categories: ["Midway Games遊戲"],
    },
    {
        aliases: ["Milestone"],
        name: "Milestone",
        page: "Milestone (公司)",
        categories: ["Milestone (公司)游戏"],
    },
    {
        aliases: ["mihoyo", "米哈游"],
        name: "米哈游",
        page: "米哈游",
        categories: ["米哈遊遊戲"],
    },
    {
        aliases: ["Mojang Studios"],
        name: "Mojang Studios",
        page: "Mojang Studios",
        categories: ["Mojang Studios遊戲"],
    },
    {
        aliases: ["Monolith Productions"],
        name: "Monolith Productions",
        page: "Monolith Productions",
        categories: ["Monolith Productions遊戲"],
    },
    {
        aliases: ["Monolith Soft"],
        name: "Monolith Soft",
        page: "Monolith Soft",
        categories: ["Monolith Soft遊戲"],
    },
    {
        aliases: ["nacon"],
        name: "Nacon",
        page: "Nacon",
        categories: ["Nacon遊戲"],
    },
    {
        aliases: ["namco", "南梦宫"],
        name: "南梦宫",
        page: "南梦宫",
        categories: ["南夢宮遊戲"],
    },
    {
        aliases: ["naughty-dog", "Naughty Dog", "顽皮狗"],
        name: "顽皮狗",
        page: "顽皮狗",
        categories: ["頑皮狗遊戲"],
    },
    {
        aliases: ["ncsoft"],
        name: "NCSoft",
        page: "NCSoft",
        categories: ["NCSoft遊戲"],
    },
    {
        aliases: ["netease-games", "NetEase Games", "网易游戏"],
        name: "网易游戏",
        page: "网易游戏",
        categories: ["網易遊戲遊戲"],
    },
    {
        aliases: ["neversoft"],
        name: "Neversoft",
        page: "Neversoft",
        categories: ["Neversoft遊戲"],
    },
    {
        aliases: ["nexon"],
        name: "Nexon",
        page: "Nexon",
        categories: ["Nexon遊戲"],
    },
    {
        aliases: ["nintendo", "任天堂"],
        name: "任天堂",
        page: "任天堂",
        categories: ["任天堂遊戲"],
        stubTags: ["Nintendo-stub"],
    },
    {
        aliases: [
            "nippon-ichi-software",
            "Nippon Ichi Software",
            "日本一软件",
        ],
        name: "日本一软件",
        page: "日本一软件",
        categories: ["日本一軟件遊戲"],
    },
    {
        aliases: [
            "obsidian-entertainment",
            "Obsidian Entertainment",
            "黑曜石娱乐",
        ],
        name: "黑曜石娱乐",
        page: "黑曜石娱乐",
        categories: ["黑曜石娛樂遊戲"],
    },
    {
        aliases: ["Outright Games"],
        name: "Outright Games",
        page: "Outright Games",
        categories: ["Outright Games遊戲"],
    },
    {
        aliases: ["Pangea Software"],
        name: "Pangea Software",
        page: "Pangea Software",
        categories: ["Pangea Software遊戲"],
    },
    {
        aliases: ["Panic Inc."],
        name: "Panic Inc.",
        page: "Panic Inc.",
        categories: ["Panic Inc.遊戲"],
    },
    {
        aliases: ["papergames", "叠纸游戏"],
        name: "叠纸游戏",
        page: "叠纸游戏",
        categories: ["疊紙遊戲遊戲"],
    },
    {
        aliases: ["Paradox Interactive"],
        name: "Paradox Interactive",
        page: "Paradox Interactive",
        categories: ["Paradox Interactive遊戲"],
    },
    {
        aliases: [
            "perfect-world-company",
            "Perfect World (company)",
            "完美世界",
        ],
        name: "完美世界",
        page: "完美世界",
        categories: ["完美世界遊戲"],
    },
    {
        aliases: ["platinumgames", "白金工作室"],
        name: "白金工作室",
        page: "白金工作室",
        categories: ["白金工作室遊戲"],
    },
    {
        aliases: ["playdead"],
        name: "Playdead",
        page: "Playdead",
        categories: ["Playdead遊戲"],
    },
    {
        aliases: ["playfirst"],
        name: "PlayFirst",
        page: "PlayFirst",
        categories: ["PlayFirst遊戲"],
    },
    {
        aliases: ["playrix"],
        name: "Playrix",
        page: "Playrix",
        categories: ["Playrix遊戲"],
    },
    {
        aliases: ["PlayStation Studios"],
        name: "PlayStation Studios",
        page: "PlayStation Studios",
        categories: ["PlayStation Studios遊戲"],
    },
    {
        aliases: ["popcap-games", "PopCap Games", "宝开游戏", "寶開遊戲"],
        name: "寶開遊戲",
        page: "寶開遊戲",
        categories: ["寶開遊戲遊戲"],
    },
    {
        aliases: ["Quantic Dream"],
        name: "Quantic Dream",
        page: "Quantic Dream",
        categories: ["Quantic Dream遊戲"],
    },
    {
        aliases: ["rare-company", "Rare (company)", "Rare"],
        name: "Rare",
        page: "Rare",
        categories: ["Rare遊戲"],
        stubTags: ["Rare-stub"],
    },
    {
        aliases: ["Raven Software"],
        name: "Raven Software",
        page: "Raven Software",
        categories: ["Raven Software遊戲"],
    },
    {
        aliases: ["Ready at Dawn"],
        name: "Ready at Dawn",
        page: "Ready at Dawn",
        categories: ["Ready at Dawn遊戲"],
    },
    {
        aliases: ["Rebellion Developments"],
        name: "Rebellion Developments",
        page: "Rebellion Developments",
        categories: ["Rebellion Developments遊戲"],
    },
    {
        aliases: [
            "red-candle-games",
            "Red Candle Games",
            "赤烛游戏",
            "赤燭遊戲",
        ],
        name: "赤燭遊戲",
        page: "赤燭遊戲",
        categories: ["赤燭遊戲遊戲"],
    },
    {
        aliases: ["Relic Entertainment"],
        name: "Relic Entertainment",
        page: "Relic Entertainment",
        categories: ["Relic Entertainment遊戲"],
    },
    {
        aliases: [
            "remedy-entertainment",
            "Remedy Entertainment",
            "绿美迪娱乐",
            "綠美迪娛樂",
        ],
        name: "綠美迪娛樂",
        page: "綠美迪娛樂",
        categories: ["綠美迪娛樂遊戲"],
    },
    {
        aliases: ["Respawn Entertainment"],
        name: "Respawn Entertainment",
        page: "Respawn Entertainment",
        categories: ["Respawn Entertainment遊戲"],
    },
    {
        aliases: ["riot-games", "Riot Games", "拳头游戏"],
        name: "拳头游戏",
        page: "拳头游戏",
        categories: ["拳頭遊戲遊戲"],
    },
    {
        aliases: ["Riot Sydney"],
        name: "Riot Sydney",
        page: "Riot Sydney",
        categories: ["Riot Sydney遊戲"],
    },
    {
        aliases: ["Rockstar Games"],
        name: "Rockstar Games",
        page: "Rockstar Games",
        categories: ["Rockstar Games遊戲"],
        stubTags: ["RockstarGames-stub"],
    },
    {
        aliases: ["Rockstar North"],
        name: "Rockstar North",
        page: "Rockstar North",
        categories: ["Rockstar North遊戲"],
    },
    {
        aliases: ["Rocksteady Studios"],
        name: "Rocksteady Studios",
        page: "Rocksteady Studios",
        categories: ["Rocksteady Studios遊戲"],
    },
    {
        aliases: ["Rovio Entertainment"],
        name: "Rovio Entertainment",
        page: "Rovio Entertainment",
        categories: ["Rovio Entertainment遊戲"],
    },
    {
        aliases: ["Runic Games"],
        name: "Runic Games",
        page: "Runic Games",
        categories: ["Runic Games遊戲"],
    },
    {
        aliases: ["Saber Interactive"],
        name: "Saber Interactive",
        page: "Saber Interactive",
        categories: ["Saber Interactive遊戲"],
    },
    {
        aliases: ["sega", "世嘉"],
        name: "世嘉",
        page: "世嘉",
        categories: ["世嘉遊戲"],
        stubTags: ["Sega-stub"],
    },
    {
        aliases: ["snk"],
        name: "SNK",
        page: "SNK",
        categories: ["SNK遊戲"],
    },
    {
        aliases: [
            "sony-interactive-entertainment",
            "Sony Interactive Entertainment",
            "索尼互動娛樂",
        ],
        name: "索尼互動娛樂",
        page: "索尼互動娛樂",
        categories: ["索尼互動娛樂遊戲"],
        stubTags: ["Sony-videogame-stub"],
    },
    {
        aliases: ["Spike Chunsoft"],
        name: "Spike Chunsoft",
        page: "Spike Chunsoft",
        categories: ["Spike Chunsoft遊戲"],
    },
    {
        aliases: ["square", "史克威尔", "史克威爾"],
        name: "史克威爾",
        page: "史克威爾",
        categories: ["史克威爾遊戲"],
    },
    {
        aliases: ["square-enix", "Square Enix", "史克威尔艾尼克斯"],
        name: "史克威尔艾尼克斯",
        page: "史克威尔艾尼克斯",
        categories: ["史克威爾艾尼克斯遊戲"],
        stubTags: ["SquareEnix-stub"],
    },
    {
        aliases: ["Studio MDHR"],
        name: "Studio MDHR",
        page: "Studio MDHR",
        categories: ["Studio MDHR遊戲"],
    },
    {
        aliases: ["Sucker Punch Productions"],
        name: "Sucker Punch Productions",
        page: "Sucker Punch Productions",
        categories: ["Sucker Punch Productions遊戲"],
    },
    {
        aliases: ["Supergiant Games"],
        name: "Supergiant Games",
        page: "Supergiant Games",
        categories: ["Supergiant Games遊戲"],
    },
    {
        aliases: ["Supermassive Games"],
        name: "Supermassive Games",
        page: "Supermassive Games",
        categories: ["Supermassive Games遊戲"],
    },
    {
        aliases: ["taito", "太东", "太東"],
        name: "太東",
        page: "太東",
        categories: ["太東遊戲"],
        stubTags: ["Taito-videogame-stub"],
    },
    {
        aliases: ["Take-Two Interactive"],
        name: "Take-Two Interactive",
        page: "Take-Two Interactive",
        categories: ["Take-Two Interactive遊戲"],
        stubTags: ["TakeTwo-stub"],
    },
    {
        aliases: ["team17"],
        name: "Team17",
        page: "Team17",
        categories: ["Team17遊戲"],
    },
    {
        aliases: ["techland"],
        name: "Techland",
        page: "Techland",
        categories: ["Techland遊戲"],
    },
    {
        aliases: ["tencent-games", "Tencent Games", "腾讯游戏", "騰訊遊戲"],
        name: "騰訊遊戲",
        page: "騰訊遊戲",
        categories: ["騰訊遊戲遊戲"],
    },
    {
        aliases: ["The 3DO Company"],
        name: "The 3DO Company",
        page: "The 3DO Company",
        categories: ["The 3DO Company遊戲"],
    },
    {
        aliases: ["The Adventure Company"],
        name: "The Adventure Company",
        page: "The Adventure Company",
        categories: ["The Adventure Company遊戲"],
    },
    {
        aliases: ["The Arcade (company)"],
        name: "The Arcade (company)",
        page: "The Arcade (company)",
        categories: ["The Arcade (company)遊戲"],
    },
    {
        aliases: ["The Astronauts (company)"],
        name: "The Astronauts (company)",
        page: "The Astronauts (company)",
        categories: ["The Astronauts (company)遊戲"],
    },
    {
        aliases: ["The Behemoth"],
        name: "The Behemoth",
        page: "The Behemoth",
        categories: ["The Behemoth遊戲"],
    },
    {
        aliases: ["The Bitmap Brothers"],
        name: "The Bitmap Brothers",
        page: "The Bitmap Brothers",
        categories: ["The Bitmap Brothers遊戲"],
    },
    {
        aliases: ["thq"],
        name: "THQ",
        page: "THQ",
        categories: ["THQ遊戲"],
        stubTags: ["THQ-stub"],
    },
    {
        aliases: ["THQ Nordic"],
        name: "THQ Nordic",
        page: "THQ Nordic",
        categories: ["THQ Nordic遊戲"],
    },
    {
        aliases: ["toei-company", "Toei Company", "东映", "東映"],
        name: "東映",
        page: "東映",
        categories: ["東映遊戲"],
    },
    {
        aliases: ["toho", "东宝", "東寶"],
        name: "東寶",
        page: "東寶",
        categories: ["東寶遊戲"],
    },
    {
        aliases: ["tokuma-shoten", "Tokuma Shoten", "德间书店", "德間書店"],
        name: "德間書店",
        page: "德間書店",
        categories: ["德間書店遊戲"],
    },
    {
        aliases: ["treyarch"],
        name: "Treyarch",
        page: "Treyarch",
        categories: ["Treyarch遊戲"],
    },
    {
        aliases: ["tri-ace"],
        name: "tri-Ace",
        page: "tri-Ace",
        categories: ["tri-Ace遊戲"],
    },
    {
        aliases: ["type-moon"],
        name: "TYPE-MOON",
        page: "TYPE-MOON",
        categories: ["TYPE-MOON遊戲"],
    },
    {
        aliases: ["ubisoft", "育碧"],
        name: "育碧",
        page: "育碧",
        categories: ["育碧遊戲"],
        stubTags: ["Ubisoft-stub"],
    },
    {
        aliases: ["valve-corporation", "Valve Corporation", "Valve公司"],
        name: "Valve公司",
        page: "Valve公司",
        categories: ["Valve公司遊戲"],
    },
    {
        aliases: ["Vivendi Games"],
        name: "Vivendi Games",
        page: "Vivendi Games",
        categories: ["Vivendi Games遊戲"],
        stubTags: ["VivendiGames-stub"],
    },
    {
        aliases: ["warner-bros-games", "Warner Bros. Games", "华纳兄弟游戏"],
        name: "华纳兄弟游戏",
        page: "华纳兄弟游戏",
        categories: ["華納兄弟互動娛樂遊戲"],
    },
    {
        aliases: ["Xbox Game Studios"],
        name: "Xbox Game Studios",
        page: "Xbox Game Studios",
        categories: ["Xbox Game Studios遊戲"],
    },
    {
        aliases: ["Yacht Club Games"],
        name: "Yacht Club Games",
        page: "Yacht Club Games",
        categories: ["Yacht Club Games遊戲"],
    },
    {
        aliases: ["ZeniMax Media"],
        name: "ZeniMax Media",
        page: "ZeniMax Media",
        categories: ["ZeniMax Media遊戲"],
        stubTags: ["Zenimax-stub"],
    },
    {
        aliases: ["zynga"],
        name: "Zynga",
        page: "Zynga",
        categories: ["Zynga遊戲"],
    },
]);
