/**
 * Generated English Wikipedia TemplateData for cite sign.
 *
 * Run the workspace update:template-data script to refresh it.
 */

import type { CitationTemplateData } from "./types.ts";

const templateData: CitationTemplateData = {
    aliases: {
        url: [],
        title: [],
        last: ["last1", "author", "author1"],
        first: ["first1"],
        "author-link": ["author-link1", "author1-link"],
        last2: ["author2"],
        first2: [],
        "author-link2": ["author2-link"],
        date: [],
        work: [],
        publisher: [],
        newspaper: [],
        "access-date": [],
        others: [],
        year: [],
        "orig-date": [],
        "editor-last": [],
        "editor-first": [],
        "editor-link": [],
        issue: [],
        department: [],
        place: ["location"],
        "publication-place": [],
        "publication-date": [],
        edition: [],
        volume: [],
        page: [],
        pages: [],
        "no-pp": [],
        at: [],
        language: [],
        "trans-title": [],
        type: [],
        format: [],
        arxiv: [],
        asin: [],
        "asin-tld": [],
        bibcode: [],
        doi: [],
        "doi-broken-date": [],
        isbn: [],
        issn: [],
        jfm: [],
        jstor: [],
        lccn: [],
        mr: [],
        oclc: [],
        ol: [],
        osti: [],
        pmc: [],
        pmid: [],
        rfc: [],
        ssrn: [],
        zbl: [],
        id: [],
        "archive-url": [],
        "archive-date": [],
        "url-status": [],
        quote: [],
        ref: [],
        postscript: [],
        last3: ["author3"],
        first3: [],
        "author-link3": ["author3-link"],
        last4: ["author4"],
        first4: [],
        "author-link4": ["author4-link"],
        last5: ["author5"],
        first5: [],
        "author-link5": ["author5-link"],
        last6: ["author6"],
        first6: [],
        "author-link6": ["author6-link"],
        last7: ["author7"],
        first7: [],
        "author-link7": ["author7-link"],
        last8: ["author8"],
        first8: [],
        "author-link8": ["author8-link"],
        last9: ["author9"],
        first9: [],
        "author-link9": ["author9-link"],
        "author-mask": [],
        "display-authors": [],
        "name-list-style": [],
    },
    dateParams: [],
    paramOrder: [
        "url",
        "title",
        "last",
        "first",
        "author-link",
        "last2",
        "first2",
        "author-link2",
        "date",
        "work",
        "publisher",
        "newspaper",
        "access-date",
        "others",
        "year",
        "orig-date",
        "editor-last",
        "editor-first",
        "editor-link",
        "issue",
        "department",
        "place",
        "publication-place",
        "publication-date",
        "edition",
        "volume",
        "page",
        "pages",
        "no-pp",
        "at",
        "language",
        "trans-title",
        "type",
        "format",
        "arxiv",
        "asin",
        "asin-tld",
        "bibcode",
        "doi",
        "doi-broken-date",
        "isbn",
        "issn",
        "jfm",
        "jstor",
        "lccn",
        "mr",
        "oclc",
        "ol",
        "osti",
        "pmc",
        "pmid",
        "rfc",
        "ssrn",
        "zbl",
        "id",
        "archive-url",
        "archive-date",
        "url-status",
        "quote",
        "ref",
        "postscript",
        "last3",
        "first3",
        "author-link3",
        "last4",
        "first4",
        "author-link4",
        "last5",
        "first5",
        "author-link5",
        "last6",
        "first6",
        "author-link6",
        "last7",
        "first7",
        "author-link7",
        "last8",
        "first8",
        "author-link8",
        "last9",
        "first9",
        "author-link9",
        "author-mask",
        "display-authors",
        "name-list-style",
    ],
};

export default templateData;
